// Created by Crowbar 0.19.0.0

$modelname "player/pyro_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_y" -1 1 0
$poseparameter "move_x" -1 1 0

$cdmaterials "models\player\pyro\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 120

$animation "a_reference" "pyro_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "pyro_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "pyro_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "pyro_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "pyro_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "pyro_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "pyro_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "pyro_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "pyro_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "pyro_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "pyro_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "pyro_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "pyro_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "pyro_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "pyro_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "pyro_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "pyro_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "pyro_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "pyro_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_neutral" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_walk_down_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_down_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_down_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_mid_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_mid_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_mid_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_up_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_up_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_up_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_walk_straight_up" "pyro_animations_anims\a_PRIMARY_aimmatrix_walk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "pyro_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "pyro_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "pyro_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "pyro_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "pyro_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_neutral" "pyro_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "pyro_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "pyro_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "pyro_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "pyro_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "pyro_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "pyro_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "pyro_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "pyro_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "pyro_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "pyro_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "pyro_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "pyro_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "pyro_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "pyro_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "pyro_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "pyro_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "pyro_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "pyro_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "pyro_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "pyro_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "pyro_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "pyro_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "pyro_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "pyro_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "pyro_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "pyro_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "pyro_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "pyro_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "pyro_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "pyro_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "pyro_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "pyro_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "pyro_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "pyro_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "pyro_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "pyro_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "pyro_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "pyro_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "pyro_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "pyro_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "pyro_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "pyro_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "pyro_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "pyro_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "pyro_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "pyro_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "pyro_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "pyro_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "pyro_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "pyro_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "pyro_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "pyro_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "pyro_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "pyro_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "pyro_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "pyro_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "pyro_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "pyro_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "pyro_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "pyro_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "pyro_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "pyro_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "pyro_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "pyro_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "pyro_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "pyro_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "pyro_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "pyro_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "pyro_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "pyro_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "pyro_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "pyro_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "pyro_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "pyro_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "pyro_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_MELEE_ALLCLASS" "pyro_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "pyro_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "pyro_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "pyro_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "pyro_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "pyro_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "pyro_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "pyro_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "pyro_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "pyro_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "pyro_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "pyro_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "pyro_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "pyro_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "pyro_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "pyro_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "pyro_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "pyro_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "pyro_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "pyro_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "pyro_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "pyro_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "pyro_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "pyro_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "pyro_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "pyro_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "pyro_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "pyro_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "pyro_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "pyro_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "pyro_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "pyro_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "pyro_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "pyro_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "pyro_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "pyro_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "pyro_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedCenter_PRIMARY" "pyro_animations_anims\a_deployedCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedS_PRIMARY" "pyro_animations_anims\a_deployedS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSE_PRIMARY" "pyro_animations_anims\a_deployedSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedE_PRIMARY" "pyro_animations_anims\a_deployedE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNE_PRIMARY" "pyro_animations_anims\a_deployedNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedN_PRIMARY" "pyro_animations_anims\a_deployedN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNW_PRIMARY" "pyro_animations_anims\a_deployedNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedW_PRIMARY" "pyro_animations_anims\a_deployedW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSW_PRIMARY" "pyro_animations_anims\a_deployedSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "pyro_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "pyro_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "pyro_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "pyro_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "pyro_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "pyro_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "pyro_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "pyro_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "pyro_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "pyro_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "pyro_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "pyro_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "pyro_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "pyro_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "pyro_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "pyro_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "pyro_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "pyro_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY" "pyro_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY" "pyro_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "pyro_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "pyro_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "pyro_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "pyro_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "pyro_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "pyro_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "pyro_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "pyro_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "pyro_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "pyro_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "pyro_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "pyro_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "pyro_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "pyro_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "pyro_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "pyro_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "pyro_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "pyro_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "pyro_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "pyro_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "pyro_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "pyro_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "pyro_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "pyro_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "pyro_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "pyro_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "pyro_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "pyro_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "pyro_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "pyro_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "pyro_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "pyro_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "pyro_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "pyro_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "pyro_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "pyro_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "pyro_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "pyro_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "pyro_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "pyro_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "pyro_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_stun_startpose" "pyro_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "pyro_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "pyro_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "pyro_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_walk" {
	"a_PRIMARY_aimmatrix_walk_straight_up"
	"a_PRIMARY_aimmatrix_walk_straight_up"
	"a_PRIMARY_aimmatrix_walk_straight_up"
	"a_PRIMARY_aimmatrix_walk_up_right"
	"a_PRIMARY_aimmatrix_walk_up_center"
	"a_PRIMARY_aimmatrix_walk_up_left"
	"a_PRIMARY_aimmatrix_walk_mid_right"
	"a_PRIMARY_aimmatrix_walk_mid_center"
	"a_PRIMARY_aimmatrix_walk_mid_left"
	"a_PRIMARY_aimmatrix_walk_down_right"
	"a_PRIMARY_aimmatrix_walk_down_center"
	"a_PRIMARY_aimmatrix_walk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ReloadStand_PRIMARY" "pyro_animations_anims\ReloadStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
}

$sequence "ReloadCrouch_PRIMARY" "pyro_animations_anims\ReloadCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
}

$sequence "ReloadSwim_PRIMARY" "pyro_animations_anims\ReloadSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
}

$sequence "a_flinch01" "pyro_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "primary_fire" "pyro_animations_anims\primary_fire.smd" {
	fps 30
}

$sequence "AttackCrouch_PRIMARY" "pyro_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	loop
	// delta
}

$sequence "AttackCrouch_PRIMARY_spoolup" "pyro_animations_anims\AttackCrouch_PRIMARY_spoolup.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PREFIRE" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY_spooldown" "pyro_animations_anims\AttackCrouch_PRIMARY_spooldown.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_POSTFIRE" 1
	// delta
}

$sequence "SECONDARYAttackCrouch_PRIMARY" "pyro_animations_anims\SECONDARYAttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARYFIRE" 1
	// delta
}

$sequence "AttackStand_PRIMARY" "pyro_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "AttackStand_primary_spoolup" "pyro_animations_anims\AttackStand_primary_spoolup.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PREFIRE" 1
	// delta
}

$sequence "AttackStand_primary_spooldown" "pyro_animations_anims\AttackStand_primary_spooldown.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_POSTFIRE" 1
	// delta
}

$sequence "SECONDARYAttackStand_PRIMARY" "pyro_animations_anims\SECONDARYAttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARYFIRE" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "pyro_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_primary_spoolup" "pyro_animations_anims\AttackSwim_primary_spoolup.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PREFIRE" 1
	// delta
}

$sequence "AttackSwim_primary_spooldown" "pyro_animations_anims\AttackSwim_primary_spooldown.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_POSTFIRE" 1
	// delta
}

$sequence "SECONDARYAttackSwim_PRIMARY" "pyro_animations_anims\SECONDARYAttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARYFIRE" 1
	// delta
}

$sequence "layer_placeSapper_ArmL" "pyro_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "pyro_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "pyro_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "pyro_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "pyro_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "ReloadStand_SECONDARY" "pyro_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
}

$sequence "ReloadCrouch_SECONDARY" "pyro_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
}

$sequence "ReloadSwim_SECONDARY" "pyro_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
}

$sequence "a_secondary_reload" "pyro_animations_anims\a_secondary_reload.smd" {
	fps 30
}

$sequence "a_secondary_reload_loop" "pyro_animations_anims\a_secondary_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_LOOP" 1
	// delta
}

$sequence "a_secondary_reload_end" "pyro_animations_anims\a_secondary_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_END" 1
	// delta
}

$sequence "a_secondary_crouch_reload_loop" "pyro_animations_anims\a_secondary_crouch_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP" 1
	// delta
}

$sequence "a_secondary_crouch_reload_end" "pyro_animations_anims\a_secondary_crouch_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_END" 1
	// delta
	fadeout 1
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_reload_flaregun_arms_ITEM1" "pyro_animations_anims\layer_reload_flaregun_arms_ITEM1.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_flaregun_airwalk_ITEM1" "pyro_animations_anims\layer_reload_flaregun_airwalk_ITEM1.smd" {
	fps 30
	hidden
}

$sequence "AttackStand_ITEM1" "pyro_animations_anims\AttackStand_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// delta
	// addlayer "layer_reload_flaregun_arms_ITEM1"
	{ event AE_CL_BODYGROUP_SET_VALUE_CMODEL_WPN 20.0000005960464 "shell 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE_CMODEL_WPN 34.9999988079071 "shell 0" }
}

$sequence "AttackCrouch_ITEM1" "pyro_animations_anims\AttackCrouch_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM1" 1
	// delta
	// addlayer "layer_reload_flaregun_arms_ITEM1"
}

$sequence "AttackSwim_ITEM1" "pyro_animations_anims\AttackSwim_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_ITEM1" 1
	// delta
	// addlayer "layer_reload_flaregun_arms_ITEM1"
}

$sequence "AttackAirwalk_ITEM1" "pyro_animations_anims\AttackAirwalk_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_Airwalk_ITEM1" 1
	// delta
	// addlayer "layer_reload_flaregun_airwalk_ITEM1"
}

$sequence "a_ITEM1_reload_airwalk" "pyro_animations_anims\a_ITEM1_reload_airwalk.smd" {
	fps 30
}

$sequence "layer_reload_arms_ITEM1" "pyro_animations_anims\layer_reload_arms_ITEM1.smd" {
	fps 30
	hidden
}

$sequence "ITEM1_reload_airwalk" "pyro_animations_anims\ITEM1_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_ITEM1" 1
	// delta
	// addlayer "layer_reload_arms_ITEM1"
}

$sequence "layer_reload_arms_ITEM1_loop" "pyro_animations_anims\layer_reload_arms_ITEM1_loop.smd" {
	fps 30
	hidden
}

$sequence "ITEM1_reload_airwalk_loop" "pyro_animations_anims\ITEM1_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_ITEM1_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_ITEM1_loop"
}

$sequence "layer_reload_arms_ITEM1_end" "pyro_animations_anims\layer_reload_arms_ITEM1_end.smd" {
	fps 30
	hidden
}

$sequence "ITEM1_reload_airwalk_end" "pyro_animations_anims\ITEM1_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_ITEM1_END" 1
	// delta
	// addlayer "layer_reload_arms_ITEM1_end"
	fadeout 1
}

$sequence "a_ITEM1_reload_swim" "pyro_animations_anims\a_ITEM1_reload_swim.smd" {
	fps 30
}

$sequence "layer_reload_arms_ITEM1_swim" "pyro_animations_anims\layer_reload_arms_ITEM1_swim.smd" {
	fps 30
	hidden
}

$sequence "ITEM1_reload_swim" "pyro_animations_anims\ITEM1_reload_swim.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_ITEM1" 1
	// delta
	// addlayer "layer_reload_arms_ITEM1_swim"
}

$sequence "layer_reload_arms_ITEM1_loop_swim" "pyro_animations_anims\layer_reload_arms_ITEM1_loop_swim.smd" {
	fps 30
	hidden
}

$sequence "a_SECONDARY_reload_airwalk" "pyro_animations_anims\a_SECONDARY_reload_airwalk.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY" "pyro_animations_anims\layer_reload_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk" "pyro_animations_anims\SECONDARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY"
}

$sequence "layer_reload_arms_SECONDARY_loop" "pyro_animations_anims\layer_reload_arms_SECONDARY_loop.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk_loop" "pyro_animations_anims\SECONDARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_loop"
}

$sequence "layer_reload_arms_SECONDARY_end" "pyro_animations_anims\layer_reload_arms_SECONDARY_end.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk_end" "pyro_animations_anims\SECONDARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_end"
	fadeout 1
}

$sequence "a_SECONDARY_reload_swim" "pyro_animations_anims\a_SECONDARY_reload_swim.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY_swim" "pyro_animations_anims\layer_reload_arms_SECONDARY_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim" "pyro_animations_anims\SECONDARY_reload_swim.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_swim"
}

$sequence "layer_reload_arms_SECONDARY_loop_swim" "pyro_animations_anims\layer_reload_arms_SECONDARY_loop_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim_loop" "pyro_animations_anims\SECONDARY_reload_swim_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_loop_swim"
}

$sequence "layer_reload_arms_SECONDARY_end_swim" "pyro_animations_anims\layer_reload_arms_SECONDARY_end_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim_end" "pyro_animations_anims\SECONDARY_reload_swim_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_end_swim"
	fadeout 1
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_Melee" "pyro_animations_anims\AttackStand_Melee.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// delta
}

$sequence "AttackCrouch_Melee" "pyro_animations_anims\AttackCrouch_Melee.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// delta
}

$sequence "AttackSwim_MELEE" "pyro_animations_anims\AttackSwim_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// delta
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_Melee_allclass" "pyro_animations_anims\AttackStand_Melee_allclass.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "AttackCrouch_Melee_allclass" "pyro_animations_anims\AttackCrouch_Melee_allclass.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "AttackSwim_MELEE_allclass" "pyro_animations_anims\AttackSwim_MELEE_allclass.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "stand_PRIMARY" "pyro_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "pyro_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "pyro_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "pyro_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "pyro_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "pyro_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "pyro_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "pyro_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "pyro_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "pyro_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "pyro_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "pyro_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "a_jumpstart_PRIMARY" "pyro_animations_anims\a_jumpstart_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
}

$sequence "a_jumpfloat_PRIMARY" "pyro_animations_anims\a_jumpfloat_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
}

$sequence "jumplandPose_PRIMARY" "pyro_animations_anims\jumplandPose_PRIMARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_PRIMARY" "pyro_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "a_jumpstart_SECONDARY" "pyro_animations_anims\a_jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "a_jumpfloat_SECONDARY" "pyro_animations_anims\a_jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumplandPose_SECONDARY" "pyro_animations_anims\jumplandPose_SECONDARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_SECONDARY" "pyro_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "pyro_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "pyro_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "pyro_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "pyro_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "pyro_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "pyro_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "pyro_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "pyro_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "pyro_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "pyro_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "pyro_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "pyro_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "a_jumpstart_ITEM1" "pyro_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "a_jumpfloat_ITEM1" "pyro_animations_anims\a_jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumplandPose_ITEM1" "pyro_animations_anims\jumplandPose_ITEM1.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM1" "pyro_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.9999995231628 "left" }
}

$sequence "crouch_deployed_PRIMARY" "pyro_animations_anims\crouch_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "stand_deployed_PRIMARY" "pyro_animations_anims\stand_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "PRIMARY_deployed_movement" {
	"a_deployedSW_PRIMARY"
	"a_deployedS_PRIMARY"
	"a_deployedSE_PRIMARY"
	"a_deployedW_PRIMARY"
	"a_deployedCenter_PRIMARY"
	"a_deployedE_PRIMARY"
	"a_deployedNW_PRIMARY"
	"a_deployedN_PRIMARY"
	"a_deployedNE_PRIMARY"
	fps 30
	"ACT_MP_DEPLOYED_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.9999995231628 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_crouch_walk_SECONDARY"
	"a_crouch_walkS_crouch_walk_SECONDARY"
	"a_crouch_walkSE_crouch_walk_SECONDARY"
	"a_crouch_walkW_crouch_walk_SECONDARY"
	"a_crouch_walkCenter_crouch_walk_SECONDARY"
	"a_crouch_walkE_crouch_walk_SECONDARY"
	"a_crouch_walkNW_crouch_walk_SECONDARY"
	"a_crouch_walkN_crouch_walk_SECONDARY"
	"a_crouch_walkNE_crouch_walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "airwalk_PRIMARY" "pyro_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_SECONDARY" "pyro_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "airwalk_MELEE" "pyro_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "airwalk_MELEE_ALLCLASS" "pyro_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "pyro_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "pyro_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "layer_gesture_primary_go_armL" "pyro_animations_anims\layer_gesture_primary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_go" "pyro_animations_anims\gesture_primary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_go_armL"
}

$sequence "layer_gesture_primary_cheer_armL" "pyro_animations_anims\layer_gesture_primary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_cheer" "pyro_animations_anims\gesture_primary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_cheer_armL"
}

$sequence "layer_gesture_primary_positive_armL" "pyro_animations_anims\layer_gesture_primary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_positive" "pyro_animations_anims\gesture_primary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_positive_armL"
}

$sequence "layer_gesture_primary_help_armL" "pyro_animations_anims\layer_gesture_primary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_help" "pyro_animations_anims\gesture_primary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_help_armL"
}

$sequence "layer_gesture_secondary_go_armL" "pyro_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "pyro_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_go_armL"
}

$sequence "layer_gesture_secondary_cheer_armL" "pyro_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "pyro_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_help_armL" "pyro_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "pyro_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_secondary_positive_armL" "pyro_animations_anims\layer_gesture_secondary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_positive" "pyro_animations_anims\gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_positive_armL"
}

$sequence "layer_gesture_melee_go_armL" "pyro_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "pyro_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_go_armL"
}

$sequence "layer_gesture_melee_cheer_armL" "pyro_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "pyro_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_cheer_armL"
}

$sequence "layer_gesture_melee_help_armL" "pyro_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "pyro_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_help_armL"
}

$sequence "layer_gesture_melee_positive_armL" "pyro_animations_anims\layer_gesture_melee_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_positive" "pyro_animations_anims\gesture_melee_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_positive_armL"
}

$sequence "layer_gesture_item1_go_armL" "pyro_animations_anims\layer_gesture_item1_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_item1_go" "pyro_animations_anims\gesture_item1_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_item1" 1
	// delta
	// addlayer "layer_gesture_item1_go_armL"
}

$sequence "layer_gesture_item1_cheer_armL" "pyro_animations_anims\layer_gesture_item1_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_item1_cheer" "pyro_animations_anims\gesture_item1_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_item1" 1
	// delta
	// addlayer "layer_gesture_item1_cheer_armL"
}

$sequence "layer_gesture_item1_help_armL" "pyro_animations_anims\layer_gesture_item1_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_item1_help" "pyro_animations_anims\gesture_item1_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_item1" 1
	// delta
	// addlayer "layer_gesture_item1_help_armL"
}

$sequence "layer_gesture_item1_positive_armL" "pyro_animations_anims\layer_gesture_item1_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_item1_positive" "pyro_animations_anims\gesture_item1_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_item1" 1
	// delta
	// addlayer "layer_gesture_item1_positive_armL"
}

$sequence "layer_PRIMARY_Stun_begin" "pyro_animations_anims\layer_PRIMARY_Stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "pyro_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_Stun_end" "pyro_animations_anims\layer_PRIMARY_Stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_Stun_begin" "pyro_animations_anims\PRIMARY_Stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_begin"
}

$sequence "PRIMARY_stun_middle" "pyro_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "pyro_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_end"
}

$sequence "primary_death_headshot" "pyro_animations_anims\primary_death_headshot.smd" {
	fps 30
}

$sequence "primary_death_backstab" "pyro_animations_anims\primary_death_backstab.smd" {
	fps 30
}

$sequence "layer_dieviolent" "pyro_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "pyro_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "selectionMenu_StartPose" "pyro_animations_anims\selectionMenu_StartPose.smd" {
	fps 30
}

$sequence "selectionMenu_Anim01" "pyro_animations_anims\selectionMenu_Anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 4.00000002235174 "Selection.PyroFootStomp" }
	{ event AE_CL_PLAYSOUND 7.00000010430813 "Selection.PyroClothesRustle" }
	{ event AE_CL_PLAYSOUND 9.00000050663948 "Selection.PyroEquipment1" }
	{ event AE_CL_PLAYSOUND 32.0000001788139 "Selection.PyroEquipment2" }
}

$sequence "selectionMenu_Idle" "pyro_animations_anims\selectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "armslayer_throw_fire" "pyro_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "pyro_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "pyro_animations_anims\layer_taunt01.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "pyro_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt01"
	{ event 5004 15.000000461936 "Taunt.Pyro01FootStomp" }
	{ event 5004 11.9999999701977 "Taunt.Pyro01Equipment2" }
	{ event 5004 24.9999991059303 "Taunt.Pyro01Equipment1" }
	{ event 5004 34.9999987483025 "Taunt.Pyro01Equipment1" }
	{ event 5004 44.9999983906746 "Taunt.Pyro01Equipment1" }
}

$sequence "layer_taunt02" "pyro_animations_anims\layer_taunt02.smd" {
	fps 46
	hidden
}

$sequence "taunt02" "pyro_animations_anims\taunt02.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt02"
	{ event AE_WPN_HIDE 1.00000003818423 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 5.00000009313226 "pyrotaunt follow_attachment weapon_bone_L" }
	{ event AE_DOTAUNTATTACK 50.0000001490116 "pyro_fireball" }
	{ event AE_WPN_UNHIDE 105 "" }
	{ event 5004 60.000002682209 "Taunt.Pyro02Fire" }
}

$sequence "layer_taunt03" "pyro_animations_anims\layer_taunt03.smd" {
	fps 32
	hidden
}

$sequence "taunt03" "pyro_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt03"
	{ event 5004 15.9999999850988 "Taunt.Pyro03RockStar" }
	{ event 5004 66.0000019669533 "Taunt.Pyro03RockStarEnd" }
}

$sequence "taunt06" "pyro_animations_anims\taunt06.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "taunt_sit" "pyro_animations_anims\taunt_sit.smd" {
	fps 30
	{ event AE_WPN_HIDE 4.00000009685755 "" }
	{ event AE_WPN_UNHIDE 180 "" }
}

$sequence "layer_taunt_bubbles" "pyro_animations_anims\layer_taunt_bubbles.smd" {
	fps 46
	hidden
}

$sequence "taunt_bubbles" "pyro_animations_anims\taunt_bubbles.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_bubbles"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 18.9999997615814 "pyrotaunt_rainbow_bubbles_flame follow_attachment weapon_bone_L" }
	{ event 5004 1.00000002421439 "Taunt.PyroBalloonicorn" }
}

$sequence "layer_taunt_lollichop" "pyro_animations_anims\layer_taunt_lollichop.smd" {
	fps 24
	hidden
}

$sequence "taunt_lollichop" "pyro_animations_anims\taunt_lollichop.smd" {
	fps 24
	// subtract "a_reference" 0
	// addlayer "layer_taunt_lollichop"
}

$sequence "layer_taunt_scorch_shot" "pyro_animations_anims\layer_taunt_scorch_shot.smd" {
	fps 24
	hidden
}

$sequence "taunt_scorch_shot" "pyro_animations_anims\taunt_scorch_shot.smd" {
	fps 24
	// subtract "a_reference" 0
	// addlayer "layer_taunt_scorch_shot"
}

$sequence "taunt_brutallegendinterior" "pyro_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "pyro_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "pyro_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "pyro_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "pyro_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "pyro_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_highFiveSuccess" "pyro_animations_anims\taunt_highFiveSuccess.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000000093132 "" }
	{ event AE_WPN_UNHIDE 130 "" }
}

$sequence "taunt_highFiveSuccessFull" "pyro_animations_anims\taunt_highFiveSuccessFull.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 125 "" }
}

$sequence "taunt_highFiveStart" "pyro_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 86 "" }
}

$sequence "pyro_taunt_replay" "pyro_animations_anims\pyro_taunt_replay.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "pyro_taunt_replay2" "pyro_animations_anims\pyro_taunt_replay2.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "layer_taunt_laugh" "pyro_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "pyro_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.99999999627471 "" }
	{ event AE_WPN_UNHIDE 145 "" }
}

$sequence "taunt_conga" "pyro_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "pyro_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "pyro_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 183.999993145466 "taunt_pyro_dosido follow_attachment weapon_bone_L" }
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
	{ event AE_CL_PLAYSOUND 183.999993145466 "Taunt.Pyro02Fire" }
}

$sequence "layer_taunt_dosido_intro" "pyro_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "pyro_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
	{ event AE_CL_PLAYSOUND 33.0000003576279 "Taunt.MedicHardClap6" }
	{ event AE_CL_PLAYSOUND 48.9999992847443 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 64.0000011920929 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 77.9999978542328 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 92 "Taunt.MedicHardClap6" }
}

$sequence "taunt_flip_start" "pyro_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "pyro_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "pyro_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000005215406 "" }
	{ event AE_WPN_UNHIDE 110.000002384186 "" }
}

$sequence "layer_taunt_flip_success_receiver" "pyro_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "pyro_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 0.999999982304871 "" }
	{ event AE_WPN_UNHIDE 126.000000536442 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48.0000011622906 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 75.0000035762787 "taunt_flip_land follow_attachment foot_R" }
}

$sequence "taunt_rps_start" "pyro_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "pyro_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "pyro_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "pyro_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "pyro_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "pyro_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "pyro_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_rock_win" "pyro_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "pyro_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_paper_win" "pyro_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "pyro_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_scissors_win" "pyro_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "pyro_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_rock_lose" "pyro_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "pyro_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 203.999997138977 "" }
}

$sequence "layer_taunt_rps_paper_lose" "pyro_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "pyro_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 203.999997138977 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "pyro_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "pyro_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 203.999997138977 "" }
}

$sequence "layer_taunt_headbutt_start" "pyro_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "pyro_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 132 "" }
}

$sequence "layer_taunt_headbutt_success" "pyro_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "pyro_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 56.0000010728836 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 142 "" }
}

$sequence "layer_taunt_party_trick" "pyro_animations_anims\layer_taunt_party_trick.smd" {
	fps 30
	hidden
}

$sequence "taunt_party_trick" "pyro_animations_anims\taunt_party_trick.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_party_trick"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 8.00000035762787 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 112 "taunt_pyro_lighter follow_attachment weapon_bone_L" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 147 "taunt_pyro_balloon follow_attachment weapon_bone_4" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 189 "taunt_pyro_balloon_explosion follow_attachment weapon_bone_4" }
	{ event AE_WPN_HIDE 196.999996185303 "" }
}

$ikchain "rhand" "bip_hand_R" knee 0.812 0.583 0.005
$ikchain "lhand" "bip_hand_L" knee 0.794 -0.608 0.003
$ikchain "rfoot" "bip_foot_R" knee 0.528 0.001 0.85
$ikchain "lfoot" "bip_foot_L" knee 0.499 -0.001 0.867

