// Created by Crowbar 0.19.0.0

$modelname "player/spy_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_y" -1 1 0
$poseparameter "move_x" -1 1 0

$cdmaterials "models\player\spy\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "spy_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "spy_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "spy_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "spy_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "spy_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "spy_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "spy_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "spy_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "spy_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "spy_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "spy_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "spy_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "spy_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "spy_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "spy_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "spy_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "spy_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "spy_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "spy_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "spy_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "spy_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "spy_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "spy_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "spy_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "spy_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "spy_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "spy_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "spy_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "spy_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "spy_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "spy_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "spy_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "spy_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "spy_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "spy_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "spy_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "spy_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "spy_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "spy_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "spy_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "spy_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "spy_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "spy_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "spy_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "spy_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "spy_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "spy_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "spy_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "spy_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "spy_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "spy_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_Swing" "spy_animations_anims\a_Melee_Swing.smd" {
	fps 30
}
$animation "a_Melee_Crouch_Swing" "spy_animations_anims\a_Melee_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Melee_Overhand_Swing" "spy_animations_anims\a_Melee_Overhand_Swing.smd" {
	fps 30
}
$animation "a_Melee_Swim_Swing" "spy_animations_anims\a_Melee_Swim_Swing.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_idle_neutral" "spy_animations_anims\a_PDA_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_idle_down_right" "spy_animations_anims\a_PDA_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_down_center" "spy_animations_anims\a_PDA_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_down_left" "spy_animations_anims\a_PDA_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_right" "spy_animations_anims\a_PDA_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_center" "spy_animations_anims\a_PDA_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_left" "spy_animations_anims\a_PDA_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_right" "spy_animations_anims\a_PDA_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_center" "spy_animations_anims\a_PDA_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_left" "spy_animations_anims\a_PDA_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_straight_up" "spy_animations_anims\a_PDA_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_neutral" "spy_animations_anims\a_PDA_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_run_down_right" "spy_animations_anims\a_PDA_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_down_center" "spy_animations_anims\a_PDA_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_down_left" "spy_animations_anims\a_PDA_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_right" "spy_animations_anims\a_PDA_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_center" "spy_animations_anims\a_PDA_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_left" "spy_animations_anims\a_PDA_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_right" "spy_animations_anims\a_PDA_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_center" "spy_animations_anims\a_PDA_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_left" "spy_animations_anims\a_PDA_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_straight_up" "spy_animations_anims\a_PDA_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_PDA_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_fire" "spy_animations_anims\a_PDA_fire.smd" {
	fps 30
}
$animation "a_PDA_run_fire" "spy_animations_anims\a_PDA_run_fire.smd" {
	fps 30
}
$animation "a_PDA_Crouch_fire" "spy_animations_anims\a_PDA_Crouch_fire.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_swing" "spy_animations_anims\a_MELEE_ALLCLASS_swing.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_crouch_swing" "spy_animations_anims\a_MELEE_ALLCLASS_crouch_swing.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_swim_swing" "spy_animations_anims\a_MELEE_ALLCLASS_swim_swing.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "spy_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "spy_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "spy_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "spy_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "spy_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "spy_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "spy_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "spy_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "spy_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "spy_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "spy_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_neutral" "spy_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "spy_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "spy_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "spy_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "spy_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "spy_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "spy_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "spy_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "spy_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "spy_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "spy_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_Swing" "spy_animations_anims\a_ITEM1_Swing.smd" {
	fps 30
}
$animation "a_ITEM1_Crouch_Swing" "spy_animations_anims\a_ITEM1_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Item1_Overhand_Swing" "spy_animations_anims\a_Item1_Overhand_Swing.smd" {
	fps 30
}
$animation "a_ITEM1_Swim_Swing" "spy_animations_anims\a_ITEM1_Swim_Swing.smd" {
	fps 30
}
$animation "a_SAPPER_aimmatrix_idle_neutral" "spy_animations_anims\a_SAPPER_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SAPPER_aimmatrix_idle_down_right" "spy_animations_anims\a_SAPPER_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_down_center" "spy_animations_anims\a_SAPPER_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_down_left" "spy_animations_anims\a_SAPPER_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_mid_right" "spy_animations_anims\a_SAPPER_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_mid_center" "spy_animations_anims\a_SAPPER_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_mid_left" "spy_animations_anims\a_SAPPER_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_up_right" "spy_animations_anims\a_SAPPER_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_up_center" "spy_animations_anims\a_SAPPER_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_up_left" "spy_animations_anims\a_SAPPER_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_idle_straight_up" "spy_animations_anims\a_SAPPER_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_neutral" "spy_animations_anims\a_SAPPER_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SAPPER_aimmatrix_run_down_right" "spy_animations_anims\a_SAPPER_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_down_center" "spy_animations_anims\a_SAPPER_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_down_left" "spy_animations_anims\a_SAPPER_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_mid_right" "spy_animations_anims\a_SAPPER_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_mid_center" "spy_animations_anims\a_SAPPER_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_mid_left" "spy_animations_anims\a_SAPPER_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_up_right" "spy_animations_anims\a_SAPPER_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_up_center" "spy_animations_anims\a_SAPPER_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_up_left" "spy_animations_anims\a_SAPPER_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_run_straight_up" "spy_animations_anims\a_SAPPER_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_neutral" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SAPPER_aimmatrix_crouch_idle_down_right" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_down_center" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_down_left" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_mid_right" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_mid_center" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_mid_left" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_up_right" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_up_center" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_up_left" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_crouch_idle_straight_up" "spy_animations_anims\a_SAPPER_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "spy_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "spy_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "spy_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "spy_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "spy_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "spy_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "spy_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "spy_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "spy_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "spy_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "spy_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "spy_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "spy_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "spy_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "spy_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "spy_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "spy_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "spy_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "spy_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "spy_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "spy_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "spy_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "spy_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "spy_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "spy_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "spy_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "spy_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "spy_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "spy_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "spy_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "spy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "spy_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "spy_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "spy_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "spy_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "spy_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "spy_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "spy_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "spy_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "spy_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "spy_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "spy_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "spy_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "spy_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "spy_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "spy_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "spy_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "spy_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "spy_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "spy_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "spy_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "spy_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "spy_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "spy_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "spy_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "spy_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "spy_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "spy_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "spy_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "spy_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_PDA_aimmatrix_swim_neutral" "spy_animations_anims\a_PDA_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_swim_down_right" "spy_animations_anims\a_PDA_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_down_center" "spy_animations_anims\a_PDA_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_down_left" "spy_animations_anims\a_PDA_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_right" "spy_animations_anims\a_PDA_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_center" "spy_animations_anims\a_PDA_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_left" "spy_animations_anims\a_PDA_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_right" "spy_animations_anims\a_PDA_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_center" "spy_animations_anims\a_PDA_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_left" "spy_animations_anims\a_PDA_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_straight_up" "spy_animations_anims\a_PDA_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PDA" "spy_animations_anims\a_swimCenter_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimS_PDA" "spy_animations_anims\a_swimS_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PDA" "spy_animations_anims\a_swimSE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimE_PDA" "spy_animations_anims\a_swimE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PDA" "spy_animations_anims\a_swimNE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimN_PDA" "spy_animations_anims\a_swimN_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PDA" "spy_animations_anims\a_swimNW_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimW_PDA" "spy_animations_anims\a_swimW_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PDA" "spy_animations_anims\a_swimSW_PDA.smd" {
	fps 30
	loop
}
$animation "a_SAPPER_aimmatrix_swim_neutral" "spy_animations_anims\a_SAPPER_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SAPPER_aimmatrix_swim_down_right" "spy_animations_anims\a_SAPPER_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_down_center" "spy_animations_anims\a_SAPPER_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_down_left" "spy_animations_anims\a_SAPPER_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_mid_right" "spy_animations_anims\a_SAPPER_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_mid_center" "spy_animations_anims\a_SAPPER_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_mid_left" "spy_animations_anims\a_SAPPER_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_up_right" "spy_animations_anims\a_SAPPER_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_up_center" "spy_animations_anims\a_SAPPER_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_up_left" "spy_animations_anims\a_SAPPER_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SAPPER_aimmatrix_swim_straight_up" "spy_animations_anims\a_SAPPER_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SAPPER" "spy_animations_anims\a_swimCenter_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimS_SAPPER" "spy_animations_anims\a_swimS_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SAPPER" "spy_animations_anims\a_swimSE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimE_SAPPER" "spy_animations_anims\a_swimE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SAPPER" "spy_animations_anims\a_swimNE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimN_SAPPER" "spy_animations_anims\a_swimN_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SAPPER" "spy_animations_anims\a_swimNW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimW_SAPPER" "spy_animations_anims\a_swimW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SAPPER" "spy_animations_anims\a_swimSW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "spy_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "spy_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "spy_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "spy_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "spy_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "spy_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "spy_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "spy_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "spy_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "spy_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "spy_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "spy_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "spy_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "spy_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "spy_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "spy_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "spy_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "spy_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY" "spy_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY" "spy_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "spy_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "spy_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "spy_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "spy_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "spy_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "spy_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "spy_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "spy_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "spy_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_MELEE" "spy_animations_anims\a_crouch_walkCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_MELEE" "spy_animations_anims\a_crouch_walkS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_MELEE" "spy_animations_anims\a_crouch_walkSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_MELEE" "spy_animations_anims\a_crouch_walkE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_MELEE" "spy_animations_anims\a_crouch_walkNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_MELEE" "spy_animations_anims\a_crouch_walkN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_MELEE" "spy_animations_anims\a_crouch_walkNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_MELEE" "spy_animations_anims\a_crouch_walkW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_MELEE" "spy_animations_anims\a_crouch_walkSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "spy_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "spy_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "spy_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "spy_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "spy_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "spy_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "spy_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "spy_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "spy_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "spy_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "spy_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "spy_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "spy_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "spy_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "spy_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "spy_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "spy_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "spy_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "spy_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "spy_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "spy_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "spy_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "spy_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "spy_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "spy_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "spy_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "spy_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "spy_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "spy_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "spy_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PDA" "spy_animations_anims\a_runCenter_PDA.smd" {
	fps 30
	loop
}
$animation "a_runS_PDA" "spy_animations_anims\a_runS_PDA.smd" {
	fps 30
	loop
}
$animation "a_runSE_PDA" "spy_animations_anims\a_runSE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runE_PDA" "spy_animations_anims\a_runE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runNE_PDA" "spy_animations_anims\a_runNE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runN_PDA" "spy_animations_anims\a_runN_PDA.smd" {
	fps 30
	loop
}
$animation "a_runNW_PDA" "spy_animations_anims\a_runNW_PDA.smd" {
	fps 30
	loop
}
$animation "a_runW_PDA" "spy_animations_anims\a_runW_PDA.smd" {
	fps 30
	loop
}
$animation "a_runSW_PDA" "spy_animations_anims\a_runSW_PDA.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_PDA" "spy_animations_anims\a_blend_crouchN_crouch_walk_PDA.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkCenter_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkS_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkSE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkNE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkN_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkNW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_PDA" "spy_animations_anims\a_crouch_walkSW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SAPPER" "spy_animations_anims\a_runCenter_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runS_SAPPER" "spy_animations_anims\a_runS_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runSE_SAPPER" "spy_animations_anims\a_runSE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runE_SAPPER" "spy_animations_anims\a_runE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runNE_SAPPER" "spy_animations_anims\a_runNE_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runN_SAPPER" "spy_animations_anims\a_runN_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runNW_SAPPER" "spy_animations_anims\a_runNW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runW_SAPPER" "spy_animations_anims\a_runW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_runSW_SAPPER" "spy_animations_anims\a_runSW_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SAPPER" "spy_animations_anims\a_blend_crouchN_crouch_walk_SAPPER.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkCenter_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkS_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkSE_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkE_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkNE_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkN_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkNW_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkW_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SAPPER" "spy_animations_anims\a_crouch_walkSW_crouch_walk_SAPPER.smd" {
	fps 30
	loop
}
$animation "a_stun_startpose" "spy_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "spy_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "spy_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "test_swingBlend" "spy_animations_anims\test_swingBlend.smd" {
	fps 30
	worldspace
}

$sequence "ragdollspawn" "spy_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "spy_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "spy_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "spy_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "layer_reload_standing_arms_SECONDARY" "spy_animations_anims\layer_reload_standing_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_crouching_arms_SECONDARY" "spy_animations_anims\layer_reload_crouching_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_swimming_arms_SECONDARY" "spy_animations_anims\layer_reload_swimming_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_airwalk_arms_SECONDARY" "spy_animations_anims\layer_reload_airwalk_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY" "spy_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "ReloadCrouch_SECONDARY" "spy_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	// addlayer "layer_reload_crouching_arms_SECONDARY"
}

$sequence "ReloadSwim_SECONDARY" "spy_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_swimming_arms_SECONDARY"
}

$sequence "ReloadAirwalk_SECONDARY" "spy_animations_anims\ReloadAirwalk_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_airwalk_arms_SECONDARY"
}

$sequence "a_flinch01" "spy_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "layer_placeSapper_ArmL" "spy_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_placeSapper" "spy_animations_anims\SECONDARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_melee_swing" "spy_animations_anims\armslayer_melee_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swing" "spy_animations_anims\bodylayer_Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swing" "spy_animations_anims\Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// addlayer "bodylayer_Melee_Swing"
	// addlayer "armslayer_melee_swing"
}

$sequence "armslayer_melee_Crouch_swing" "spy_animations_anims\armslayer_melee_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Crouch_Swing" "spy_animations_anims\bodylayer_Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Crouch_Swing" "spy_animations_anims\Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// addlayer "bodylayer_Melee_Crouch_Swing"
	// addlayer "armslayer_melee_Crouch_swing"
}

$sequence "armslayer_melee_Overhand_swing" "spy_animations_anims\armslayer_melee_Overhand_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Overhand_Swing" "spy_animations_anims\bodylayer_Melee_Overhand_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Overhand_Swing" "spy_animations_anims\Melee_Overhand_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_SECONDARY" 1
	// addlayer "bodylayer_Melee_Overhand_Swing"
	// addlayer "armslayer_melee_Overhand_swing"
}

$sequence "armslayer_melee_Swim_swing" "spy_animations_anims\armslayer_melee_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swim_Swing" "spy_animations_anims\bodylayer_Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swim_Swing" "spy_animations_anims\Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// addlayer "bodylayer_Melee_Swim_Swing"
	// addlayer "armslayer_melee_Swim_swing"
}

$sequence "PDA_aimmatrix_idle" {
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_up_right"
	"a_PDA_aimmatrix_idle_up_center"
	"a_PDA_aimmatrix_idle_up_left"
	"a_PDA_aimmatrix_idle_mid_right"
	"a_PDA_aimmatrix_idle_mid_center"
	"a_PDA_aimmatrix_idle_mid_left"
	"a_PDA_aimmatrix_idle_down_right"
	"a_PDA_aimmatrix_idle_down_center"
	"a_PDA_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PDA_aimmatrix_run" {
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_up_right"
	"a_PDA_aimmatrix_run_up_center"
	"a_PDA_aimmatrix_run_up_left"
	"a_PDA_aimmatrix_run_mid_right"
	"a_PDA_aimmatrix_run_mid_center"
	"a_PDA_aimmatrix_run_mid_left"
	"a_PDA_aimmatrix_run_down_right"
	"a_PDA_aimmatrix_run_down_center"
	"a_PDA_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PDA_aimmatrix_crouch_idle" {
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_up_right"
	"a_PDA_aimmatrix_crouch_idle_up_center"
	"a_PDA_aimmatrix_crouch_idle_up_left"
	"a_PDA_aimmatrix_crouch_idle_mid_right"
	"a_PDA_aimmatrix_crouch_idle_mid_center"
	"a_PDA_aimmatrix_crouch_idle_mid_left"
	"a_PDA_aimmatrix_crouch_idle_down_right"
	"a_PDA_aimmatrix_crouch_idle_down_center"
	"a_PDA_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_PDA_fire" "spy_animations_anims\armslayer_PDA_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_fire" "spy_animations_anims\bodylayer_PDA_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_fire" "spy_animations_anims\PDA_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PDA" 1
	// addlayer "bodylayer_PDA_fire"
	// addlayer "armslayer_PDA_fire"
}

$sequence "armslayer_PDA_run_fire" "spy_animations_anims\armslayer_PDA_run_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_run_fire" "spy_animations_anims\bodylayer_PDA_run_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_run_fire" "spy_animations_anims\PDA_run_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_RUN_PDA" 1
	// addlayer "bodylayer_PDA_run_fire"
	// addlayer "armslayer_PDA_run_fire"
}

$sequence "armslayer_PDA_Crouch_fire" "spy_animations_anims\armslayer_PDA_Crouch_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_Crouch_fire" "spy_animations_anims\bodylayer_PDA_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_Crouch_fire" "spy_animations_anims\PDA_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PDA" 1
	// addlayer "bodylayer_PDA_Crouch_fire"
	// addlayer "armslayer_PDA_Crouch_fire"
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_MELEE_ALLCLASS_swing" "spy_animations_anims\armslayer_MELEE_ALLCLASS_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_MELEE_ALLCLASS_swing" "spy_animations_anims\bodylayer_MELEE_ALLCLASS_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "MELEE_ALLCLASS_swing" "spy_animations_anims\MELEE_ALLCLASS_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_MELEE_ALLCLASS_swing"
	// addlayer "armslayer_MELEE_ALLCLASS_swing"
	// addlayer "r_handposes"
}

$sequence "armslayer_MELEE_ALLCLASS_crouch_swing" "spy_animations_anims\armslayer_MELEE_ALLCLASS_crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_MELEE_ALLCLASS_crouch_swing" "spy_animations_anims\bodylayer_MELEE_ALLCLASS_crouch_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "MELEE_ALLCLASS_crouch_swing" "spy_animations_anims\MELEE_ALLCLASS_crouch_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_MELEE_ALLCLASS_crouch_swing"
	// addlayer "armslayer_MELEE_ALLCLASS_crouch_swing"
	// addlayer "r_handposes"
}

$sequence "armslayer_MELEE_ALLCLASS_swim_swing" "spy_animations_anims\armslayer_MELEE_ALLCLASS_swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_MELEE_ALLCLASS_swim_swing" "spy_animations_anims\bodylayer_MELEE_ALLCLASS_swim_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "MELEE_ALLCLASS_swim_swing" "spy_animations_anims\MELEE_ALLCLASS_swim_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_MELEE_ALLCLASS_swim_swing"
	// addlayer "armslayer_MELEE_ALLCLASS_swim_swing"
	// addlayer "r_handposes"
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_ITEM1_swing" "spy_animations_anims\armslayer_ITEM1_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_Swing" "spy_animations_anims\bodylayer_ITEM1_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_Swing" "spy_animations_anims\ITEM1_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// addlayer "bodylayer_ITEM1_Swing"
	// addlayer "armslayer_ITEM1_swing"
}

$sequence "armslayer_ITEM1_Crouch_swing" "spy_animations_anims\armslayer_ITEM1_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_Crouch_Swing" "spy_animations_anims\bodylayer_ITEM1_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_Crouch_Swing" "spy_animations_anims\ITEM1_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM1" 1
	// addlayer "bodylayer_ITEM1_Crouch_Swing"
	// addlayer "armslayer_ITEM1_Crouch_swing"
}

$sequence "armslayer_Item1_Overhand_swing" "spy_animations_anims\armslayer_Item1_Overhand_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Item1_Overhand_Swing" "spy_animations_anims\bodylayer_Item1_Overhand_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Item1_Overhand_Swing" "spy_animations_anims\Item1_Overhand_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1_SECONDARY" 1
	// addlayer "bodylayer_Item1_Overhand_Swing"
	// addlayer "armslayer_Item1_Overhand_swing"
}

$sequence "armslayer_ITEM1_Swim_swing" "spy_animations_anims\armslayer_ITEM1_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_Swim_Swing" "spy_animations_anims\bodylayer_ITEM1_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_Swim_Swing" "spy_animations_anims\ITEM1_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_ITEM1" 1
	// addlayer "bodylayer_ITEM1_Swim_Swing"
	// addlayer "armslayer_ITEM1_Swim_swing"
}

$sequence "SAPPER_aimmatrix_idle" {
	"a_SAPPER_aimmatrix_idle_straight_up"
	"a_SAPPER_aimmatrix_idle_straight_up"
	"a_SAPPER_aimmatrix_idle_straight_up"
	"a_SAPPER_aimmatrix_idle_up_right"
	"a_SAPPER_aimmatrix_idle_up_center"
	"a_SAPPER_aimmatrix_idle_up_left"
	"a_SAPPER_aimmatrix_idle_mid_right"
	"a_SAPPER_aimmatrix_idle_mid_center"
	"a_SAPPER_aimmatrix_idle_mid_left"
	"a_SAPPER_aimmatrix_idle_down_right"
	"a_SAPPER_aimmatrix_idle_down_center"
	"a_SAPPER_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SAPPER_aimmatrix_run" {
	"a_SAPPER_aimmatrix_run_straight_up"
	"a_SAPPER_aimmatrix_run_straight_up"
	"a_SAPPER_aimmatrix_run_straight_up"
	"a_SAPPER_aimmatrix_run_up_right"
	"a_SAPPER_aimmatrix_run_up_center"
	"a_SAPPER_aimmatrix_run_up_left"
	"a_SAPPER_aimmatrix_run_mid_right"
	"a_SAPPER_aimmatrix_run_mid_center"
	"a_SAPPER_aimmatrix_run_mid_left"
	"a_SAPPER_aimmatrix_run_down_right"
	"a_SAPPER_aimmatrix_run_down_center"
	"a_SAPPER_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SAPPER_aimmatrix_crouch_idle" {
	"a_SAPPER_aimmatrix_crouch_idle_straight_up"
	"a_SAPPER_aimmatrix_crouch_idle_straight_up"
	"a_SAPPER_aimmatrix_crouch_idle_straight_up"
	"a_SAPPER_aimmatrix_crouch_idle_up_right"
	"a_SAPPER_aimmatrix_crouch_idle_up_center"
	"a_SAPPER_aimmatrix_crouch_idle_up_left"
	"a_SAPPER_aimmatrix_crouch_idle_mid_right"
	"a_SAPPER_aimmatrix_crouch_idle_mid_center"
	"a_SAPPER_aimmatrix_crouch_idle_mid_left"
	"a_SAPPER_aimmatrix_crouch_idle_down_right"
	"a_SAPPER_aimmatrix_crouch_idle_down_center"
	"a_SAPPER_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_a_placeSapper_ArmL" "spy_animations_anims\layer_a_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "SAPPER_placeSapper" "spy_animations_anims\SAPPER_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE_BUILDING" 1
	// delta
	// addlayer "layer_a_placeSapper_ArmL"
}

$sequence "stand_SECONDARY" "spy_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "spy_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "spy_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "spy_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "spy_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "stand_PDA" "spy_animations_anims\stand_PDA.smd" {
	fps 30
	"ACT_MP_STAND_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_idle"
}

$sequence "stand_SAPPER" "spy_animations_anims\stand_SAPPER.smd" {
	fps 30
	"ACT_MP_STAND_BUILDING" 1
	loop
	// addlayer "SAPPER_aimmatrix_idle"
}

$sequence "crouch_SECONDARY" "spy_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "spy_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "spy_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "spy_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "spy_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "crouch_PDA" "spy_animations_anims\crouch_PDA.smd" {
	fps 30
	"ACT_MP_CROUCH_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_crouch_idle"
}

$sequence "crouch_SAPPER" "spy_animations_anims\crouch_SAPPER.smd" {
	fps 30
	"ACT_MP_CROUCH_BUILDING" 1
	loop
	// addlayer "SAPPER_aimmatrix_crouch_idle"
}

$sequence "a_jumpstart_SECONDARY" "spy_animations_anims\a_jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "a_jumpfloat_SECONDARY" "spy_animations_anims\a_jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumplandPose_SECONDARY" "spy_animations_anims\jumplandPose_SECONDARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_SECONDARY" "spy_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "spy_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "spy_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "spy_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "spy_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "spy_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "spy_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "spy_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "spy_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "spy_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "spy_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "spy_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "spy_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "a_jumpstart_ITEM1" "spy_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "a_jumpfloat_ITEM1" "spy_animations_anims\a_jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumplandPose_ITEM1" "spy_animations_anims\jumplandPose_ITEM1.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM1" "spy_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "a_jumpstart_PDA" "spy_animations_anims\a_jumpstart_PDA.smd" {
	fps 30
	"ACT_MP_JUMP_START_PDA" 1
}

$sequence "a_jumpfloat_PDA" "spy_animations_anims\a_jumpfloat_PDA.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PDA" 1
	loop
}

$sequence "jumplandPose_PDA" "spy_animations_anims\jumplandPose_PDA.smd" {
	fps 30
	loop
}

$sequence "jumpland_PDA" "spy_animations_anims\jumpland_PDA.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PDA" 1
	// delta
}

$sequence "a_jumpstart_SAPPER" "spy_animations_anims\a_jumpstart_SAPPER.smd" {
	fps 30
	"ACT_MP_JUMP_START_BUILDING" 1
}

$sequence "a_jumpfloat_SAPPER" "spy_animations_anims\a_jumpfloat_SAPPER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_BUILDING" 1
	loop
}

$sequence "jumplandPose_SAPPER" "spy_animations_anims\jumplandPose_SAPPER.smd" {
	fps 30
	loop
}

$sequence "jumpland_SAPPER" "spy_animations_anims\jumpland_SAPPER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_BUILDING" 1
	// delta
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "PDA_aimmatrix_swim" {
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_up_right"
	"a_PDA_aimmatrix_swim_up_center"
	"a_PDA_aimmatrix_swim_up_left"
	"a_PDA_aimmatrix_swim_mid_right"
	"a_PDA_aimmatrix_swim_mid_center"
	"a_PDA_aimmatrix_swim_mid_left"
	"a_PDA_aimmatrix_swim_down_right"
	"a_PDA_aimmatrix_swim_down_center"
	"a_PDA_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PDA" {
	"a_swimCenter_PDA"
	fps 30
	loop
}

$sequence "swim_PDA" {
	"a_swimSW_PDA"
	"a_swimS_PDA"
	"a_swimSE_PDA"
	"a_swimW_PDA"
	"a_swimCenter_PDA"
	"a_swimE_PDA"
	"a_swimNW_PDA"
	"a_swimN_PDA"
	"a_swimNE_PDA"
	fps 30
	"ACT_MP_SWIM_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_swim"
}

$sequence "SAPPER_aimmatrix_swim" {
	"a_SAPPER_aimmatrix_swim_straight_up"
	"a_SAPPER_aimmatrix_swim_straight_up"
	"a_SAPPER_aimmatrix_swim_straight_up"
	"a_SAPPER_aimmatrix_swim_up_right"
	"a_SAPPER_aimmatrix_swim_up_center"
	"a_SAPPER_aimmatrix_swim_up_left"
	"a_SAPPER_aimmatrix_swim_mid_right"
	"a_SAPPER_aimmatrix_swim_mid_center"
	"a_SAPPER_aimmatrix_swim_mid_left"
	"a_SAPPER_aimmatrix_swim_down_right"
	"a_SAPPER_aimmatrix_swim_down_center"
	"a_SAPPER_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SAPPER" {
	"a_swimCenter_SAPPER"
	fps 30
	loop
}

$sequence "swim_SAPPER" {
	"a_swimSW_SAPPER"
	"a_swimS_SAPPER"
	"a_swimSE_SAPPER"
	"a_swimW_SAPPER"
	"a_swimCenter_SAPPER"
	"a_swimE_SAPPER"
	"a_swimNW_SAPPER"
	"a_swimN_SAPPER"
	"a_swimNE_SAPPER"
	fps 30
	"ACT_MP_SWIM_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SAPPER_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_crouch_walk_SECONDARY"
	"a_crouch_walkS_crouch_walk_SECONDARY"
	"a_crouch_walkSE_crouch_walk_SECONDARY"
	"a_crouch_walkW_crouch_walk_SECONDARY"
	"a_crouch_walkCenter_crouch_walk_SECONDARY"
	"a_crouch_walkE_crouch_walk_SECONDARY"
	"a_crouch_walkNW_crouch_walk_SECONDARY"
	"a_crouch_walkN_crouch_walk_SECONDARY"
	"a_crouch_walkNE_crouch_walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_MELEE"
	"a_crouch_walkS_MELEE"
	"a_crouch_walkSE_MELEE"
	"a_crouch_walkW_MELEE"
	"a_crouch_walkCenter_MELEE"
	"a_crouch_walkE_MELEE"
	"a_crouch_walkNW_MELEE"
	"a_crouch_walkN_MELEE"
	"a_crouch_walkNE_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "run_PDA" {
	"a_runSW_PDA"
	"a_runS_PDA"
	"a_runSE_PDA"
	"a_runW_PDA"
	"a_runCenter_PDA"
	"a_runE_PDA"
	"a_runNW_PDA"
	"a_runN_PDA"
	"a_runNE_PDA"
	fps 30
	"ACT_MP_RUN_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_PDA" {
	"a_crouch_walkSW_crouch_walk_PDA"
	"a_crouch_walkS_crouch_walk_PDA"
	"a_crouch_walkSE_crouch_walk_PDA"
	"a_crouch_walkW_crouch_walk_PDA"
	"a_crouch_walkCenter_crouch_walk_PDA"
	"a_crouch_walkE_crouch_walk_PDA"
	"a_crouch_walkNW_crouch_walk_PDA"
	"a_crouch_walkN_crouch_walk_PDA"
	"a_crouch_walkNE_crouch_walk_PDA"
	fps 30
	"ACT_MP_CROUCHWALK_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_crouch_idle"
}

$sequence "x_runS_PDA" "spy_animations_anims\x_runS_PDA.smd" {
	fps 30
}

$sequence "x_runSE_PDA" "spy_animations_anims\x_runSE_PDA.smd" {
	fps 30
}

$sequence "x_runSW_PDA" "spy_animations_anims\x_runSW_PDA.smd" {
	fps 30
}

$sequence "run_SAPPER" {
	"a_runSW_SAPPER"
	"a_runS_SAPPER"
	"a_runSE_SAPPER"
	"a_runW_SAPPER"
	"a_runCenter_SAPPER"
	"a_runE_SAPPER"
	"a_runNW_SAPPER"
	"a_runN_SAPPER"
	"a_runNE_SAPPER"
	fps 30
	"ACT_MP_RUN_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SAPPER_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_SAPPER" {
	"a_crouch_walkSW_crouch_walk_SAPPER"
	"a_crouch_walkS_crouch_walk_SAPPER"
	"a_crouch_walkSE_crouch_walk_SAPPER"
	"a_crouch_walkW_crouch_walk_SAPPER"
	"a_crouch_walkCenter_crouch_walk_SAPPER"
	"a_crouch_walkE_crouch_walk_SAPPER"
	"a_crouch_walkNW_crouch_walk_SAPPER"
	"a_crouch_walkN_crouch_walk_SAPPER"
	"a_crouch_walkNE_crouch_walk_SAPPER"
	fps 30
	"ACT_MP_CROUCHWALK_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SAPPER_aimmatrix_crouch_idle"
}

$sequence "airwalk_SECONDARY" "spy_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "airwalk_MELEE" "spy_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "airwalk_MELEE_ALLCLASS" "spy_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "spy_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "spy_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "airwalk_PDA" "spy_animations_anims\airwalk_PDA.smd" {
	fps 30
	"ACT_MP_AIRWALK_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_idle"
}

$sequence "airwalk_SAPPER" "spy_animations_anims\airwalk_SAPPER.smd" {
	fps 30
	"ACT_MP_AIRWALK_BUILDING" 1
	loop
	// addlayer "SAPPER_aimmatrix_idle"
}

$sequence "layer_gesture_secondary_go_armL" "spy_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_secondary_go_runN_armL" "spy_animations_anims\layer_gesture_secondary_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "spy_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_secondary_go_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_secondary_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_secondary_go_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_secondary_cheer_armL" "spy_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "spy_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_help_armL" "spy_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "spy_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_secondary_positive_armL" "spy_animations_anims\layer_gesture_secondary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_positive" "spy_animations_anims\gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_positive_armL"
}

$sequence "layer_gesture_melee_go_armL" "spy_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_melee_go_runN_armL" "spy_animations_anims\layer_gesture_melee_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "spy_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_melee" 1
	// delta
	blendlayer "layer_gesture_melee_go_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_melee_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_melee_go_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_melee_cheer_armL" "spy_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_melee_cheer_runN_armL" "spy_animations_anims\layer_gesture_melee_cheer_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "spy_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_melee" 1
	// delta
	blendlayer "layer_gesture_melee_cheer_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_melee_cheer_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_melee_cheer_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_melee_help_armL" "spy_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_melee_help_runN_armL" "spy_animations_anims\layer_gesture_melee_help_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "spy_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_melee" 1
	// delta
	blendlayer "layer_gesture_melee_help_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_melee_help_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_melee_help_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_melee_positive_armL" "spy_animations_anims\layer_gesture_melee_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_melee_positive_runN_armL" "spy_animations_anims\layer_gesture_melee_positive_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_positive" "spy_animations_anims\gesture_melee_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_melee" 1
	// delta
	blendlayer "layer_gesture_melee_positive_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_melee_positive_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_melee_positive_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PDA_go_armL" "spy_animations_anims\layer_gesture_PDA_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PDA_go_runN_armL" "spy_animations_anims\layer_gesture_PDA_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_go" "spy_animations_anims\gesture_PDA_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PDA" 1
	// delta
	blendlayer "layer_gesture_PDA_go_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_go_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PDA_cheer_armL" "spy_animations_anims\layer_gesture_PDA_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PDA_cheer_runN_armL" "spy_animations_anims\layer_gesture_PDA_cheer_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_cheer" "spy_animations_anims\gesture_PDA_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PDA" 1
	// delta
	blendlayer "layer_gesture_PDA_cheer_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_cheer_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_cheer_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PDA_help_armL" "spy_animations_anims\layer_gesture_PDA_help_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PDA_help_runN_armL" "spy_animations_anims\layer_gesture_PDA_help_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_help" "spy_animations_anims\gesture_PDA_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PDA" 1
	// delta
	blendlayer "layer_gesture_PDA_help_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_help_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_help_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PDA_positive_armL" "spy_animations_anims\layer_gesture_PDA_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PDA_positive_runN_armL" "spy_animations_anims\layer_gesture_PDA_positive_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_positive" "spy_animations_anims\gesture_PDA_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PDA" 1
	// delta
	blendlayer "layer_gesture_PDA_positive_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_positive_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PDA_positive_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_PRIMARY_Stun_begin" "spy_animations_anims\layer_PRIMARY_Stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "spy_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_Stun_end" "spy_animations_anims\layer_PRIMARY_Stun_end.smd" {
	fps 30
	hidden
}

$sequence "layer_dieviolent" "spy_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "spy_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "primary_death_headshot" "spy_animations_anims\primary_death_headshot.smd" {
	fps 30
}

$sequence "primary_death_backstab" "spy_animations_anims\primary_death_backstab.smd" {
	fps 30
}

$sequence "primary_death_burning" "spy_animations_anims\primary_death_burning.smd" {
	fps 30
}

$sequence "PRIMARY_Stun_begin" "spy_animations_anims\PRIMARY_Stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_begin"
}

$sequence "PRIMARY_stun_middle" "spy_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "spy_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_end"
}

$sequence "SelectionMenu_StartPose" "spy_animations_anims\SelectionMenu_StartPose.smd" {
	fps 30
}

$sequence "SelectionMenu_Anim01" "spy_animations_anims\SelectionMenu_Anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 3.00000015646219 "Selection.SpyClothesRustle1" }
	{ event AE_CL_PLAYSOUND 19.0000002086163 "Selection.SpyPuff" }
	{ event AE_CL_PLAYSOUND 66.0000014305115 "Selection.SpyPuffAh" }
	{ event AE_CL_PLAYSOUND 62.9999989271164 "Selection.SpyClothesRustle2" }
}

$sequence "SelectionMenu_Idle" "spy_animations_anims\SelectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "armslayer_throw_fire" "spy_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "spy_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "secondary_taunt" "spy_animations_anims\secondary_taunt.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "spy_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "secondary_taunt"
	{ event 5004 37.9999988973141 "Taunt.Spy01ClothesSwipe" }
	{ event 5004 54.9999993145466 "Taunt.Spy01ClothesSwipe" }
	{ event 5004 90.9999972581863 "Taunt.Spy01TieFix" }
}

$sequence "layer_taunt03" "spy_animations_anims\layer_taunt03.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "spy_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt03"
	{ event 5004 16.9999999403954 "Taunt.Spy03KnifeCatch" }
	{ event 5004 17.9999998062849 "Taunt.Spy03FootStomp" }
	{ event 5004 29.000000551343 "Taunt.Spy03FootStomp" }
	{ event 5004 47.9999980032444 "Taunt.Spy03FootStomp" }
	{ event 5004 58.9999987483025 "Taunt.Spy03FootStomp" }
	{ event 5004 62.0000005662441 "Taunt.Spy03FootStomp" }
	{ event 5004 69.000001847744 "Taunt.Spy03FootStomp" }
	{ event 5004 87.0000038743019 "Taunt.Spy03FootStomp" }
	{ event 5004 105.99999910593 "Taunt.Spy03FootStomp" }
	{ event 5004 117.999997496605 "Taunt.Spy03FootStomp" }
	{ event 5004 120.00000166893 "Taunt.Spy03FootStomp" }
	{ event 5004 142.999996364117 "Taunt.Spy03FootStomp" }
}

$sequence "layer_taunt04" "spy_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "spy_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
	{ event 7000 69.9999985098839 "cig_eject" }
	{ event 5004 69.0000039339066 "Taunt.Spy04CigFlick" }
}

$sequence "layer_taunt05" "spy_animations_anims\layer_taunt05.smd" {
	fps 30
	hidden
}

$sequence "taunt05" "spy_animations_anims\taunt05.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt05"
}

$sequence "taunt06" "spy_animations_anims\taunt06.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "spy_replay_taunt" "spy_animations_anims\spy_replay_taunt.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "layer_taunt_laugh" "spy_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "spy_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.999999977648258 "" }
	{ event AE_WPN_UNHIDE 199.000000953674 "" }
}

$sequence "taunt_brutallegendinterior" "spy_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "spy_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "spy_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "spy_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "spy_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "spy_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_hifiveSuccess" "spy_animations_anims\taunt_hifiveSuccess.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000005122274 "" }
	{ event AE_WPN_UNHIDE 119 "" }
}

$sequence "taunt_hifiveSuccessFull" "spy_animations_anims\taunt_hifiveSuccessFull.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.0000000228174 "" }
	{ event AE_WPN_UNHIDE 139 "" }
}

$sequence "taunt_highFiveStart" "spy_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 86 "" }
}

$sequence "spy_taunt_replay" "spy_animations_anims\spy_taunt_replay.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "taunt_conga" "spy_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "spy_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "spy_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
}

$sequence "layer_taunt_dosido_intro" "spy_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "spy_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 152 "" }
}

$sequence "taunt_flip_start" "spy_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "spy_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "spy_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000002514571 "" }
	{ event AE_WPN_UNHIDE 124.000002622604 "" }
}

$sequence "layer_taunt_flip_success_receiver" "spy_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "spy_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 115.99999666214 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 39.9999991059303 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 59.9999986588955 "taunt_flip_land follow_attachment foot_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 72.9999989271164 "taunt_spy_flip_dirt follow_attachment effect_hand_R" }
}

$sequence "taunt_rps_start" "spy_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "spy_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "spy_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "spy_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "spy_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "spy_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "spy_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors_win" "spy_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "spy_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_rps_rock_win" "spy_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "spy_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_rps_paper_win" "spy_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "spy_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_rps_rock_lose" "spy_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "spy_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_rps_paper_lose" "spy_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "spy_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "spy_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "spy_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 208 "" }
}

$sequence "layer_taunt_headbutt_start" "spy_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "spy_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 153 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_smoke follow_attachment taunt_spy_headbutt_cig_burn" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_burn follow_attachment taunt_spy_headbutt_cig_smoke" }
}

$sequence "layer_taunt_headbutt_success" "spy_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "spy_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 56.0000003278255 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 141 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_smoke follow_attachment taunt_spy_headbutt_cig_burn" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_burn follow_attachment taunt_spy_headbutt_cig_smoke" }
}

$sequence "layer_taunt_buy_a_life" "spy_animations_anims\layer_taunt_buy_a_life.smd" {
	fps 24
	hidden
}

$sequence "taunt_buy_a_life" "spy_animations_anims\taunt_buy_a_life.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_buy_a_life"
	{ event AE_WPN_HIDE 1.00000001024455 "" }
	{ event AE_WPN_UNHIDE 22.9999997019768 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 118.000004410744 "taunt_spy_cash follow_attachment head" }
	{ event AE_WPN_HIDE 178.999999165535 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_smoke follow_attachment taunt_spy_headbutt_cig_burn" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "cig_burn follow_attachment taunt_spy_headbutt_cig_smoke" }
}

$ikchain "rhand" "bip_hand_R" knee 0.738 0.675 0.001
$ikchain "lhand" "bip_hand_L" knee 0.719 -0.695 0.001
$ikchain "rfoot" "bip_foot_R" knee 0.738 -0.675 0.001
$ikchain "lfoot" "bip_foot_L" knee 0.721 -0.001 0.693

