// Created by Crowbar 0.19.0.0

$modelname "player/scout_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_x" -1 1 0
$poseparameter "move_y" -1 1 0

$cdmaterials "models\player\scout\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 121

$animation "a_reference" "scout_animations_anims\a_reference.smd" {
	fps 30
}
$animation "b_reference" "scout_animations_anims\b_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "scout_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "scout_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "scout_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "scout_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "scout_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "scout_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "scout_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "scout_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "scout_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "scout_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "scout_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "scout_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "scout_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "scout_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "scout_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "scout_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "scout_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "scout_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "scout_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "scout_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "scout_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "scout_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "scout_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "scout_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "scout_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "scout_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "scout_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "scout_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_reload_startpose" "scout_animations_anims\a_reload_startpose.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "scout_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "scout_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "scout_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "scout_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "scout_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "scout_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "scout_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "scout_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "scout_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "scout_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "scout_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "scout_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_neutral" "scout_animations_anims\a_ITEM2_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_idle_down_right" "scout_animations_anims\a_ITEM2_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_center" "scout_animations_anims\a_ITEM2_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_left" "scout_animations_anims\a_ITEM2_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_right" "scout_animations_anims\a_ITEM2_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_center" "scout_animations_anims\a_ITEM2_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_left" "scout_animations_anims\a_ITEM2_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_right" "scout_animations_anims\a_ITEM2_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_center" "scout_animations_anims\a_ITEM2_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_left" "scout_animations_anims\a_ITEM2_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_straight_up" "scout_animations_anims\a_ITEM2_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_neutral" "scout_animations_anims\a_ITEM2_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_run_down_right" "scout_animations_anims\a_ITEM2_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_center" "scout_animations_anims\a_ITEM2_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_left" "scout_animations_anims\a_ITEM2_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_right" "scout_animations_anims\a_ITEM2_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_center" "scout_animations_anims\a_ITEM2_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_left" "scout_animations_anims\a_ITEM2_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_right" "scout_animations_anims\a_ITEM2_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_center" "scout_animations_anims\a_ITEM2_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_left" "scout_animations_anims\a_ITEM2_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_straight_up" "scout_animations_anims\a_ITEM2_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_ITEM2_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "scout_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "scout_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "scout_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "scout_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "scout_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "scout_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "scout_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "scout_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "scout_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "scout_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "scout_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "scout_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "scout_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "scout_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "scout_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "scout_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "scout_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "scout_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "scout_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "scout_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "scout_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "scout_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_neutral" "scout_animations_anims\a_STUN_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_STUN_aimmatrix_idle_down_right" "scout_animations_anims\a_STUN_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_down_center" "scout_animations_anims\a_STUN_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_down_left" "scout_animations_anims\a_STUN_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_mid_right" "scout_animations_anims\a_STUN_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_mid_center" "scout_animations_anims\a_STUN_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_mid_left" "scout_animations_anims\a_STUN_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_up_right" "scout_animations_anims\a_STUN_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_up_center" "scout_animations_anims\a_STUN_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_up_left" "scout_animations_anims\a_STUN_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_idle_straight_up" "scout_animations_anims\a_STUN_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_neutral" "scout_animations_anims\a_STUN_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_STUN_aimmatrix_run_down_right" "scout_animations_anims\a_STUN_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_down_center" "scout_animations_anims\a_STUN_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_down_left" "scout_animations_anims\a_STUN_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_mid_right" "scout_animations_anims\a_STUN_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_mid_center" "scout_animations_anims\a_STUN_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_mid_left" "scout_animations_anims\a_STUN_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_up_right" "scout_animations_anims\a_STUN_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_up_center" "scout_animations_anims\a_STUN_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_up_left" "scout_animations_anims\a_STUN_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_run_straight_up" "scout_animations_anims\a_STUN_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_STUN_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_STUN_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_STUN_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "scout_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "scout_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "scout_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "scout_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "scout_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "scout_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "scout_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "scout_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "scout_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "scout_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "scout_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_neutral" "scout_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "scout_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "scout_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "scout_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "scout_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "scout_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "scout_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "scout_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "scout_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "scout_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "scout_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "scout_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_fire" "scout_animations_anims\a_ITEM1_fire.smd" {
	fps 30
}
$animation "a_ITEM1_Crouch_fire" "scout_animations_anims\a_ITEM1_Crouch_fire.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "scout_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "scout_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "scout_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "scout_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "scout_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "scout_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "scout_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "scout_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "scout_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "scout_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_SECONDARY" "scout_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "scout_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "scout_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "scout_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "scout_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "scout_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "scout_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "scout_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "scout_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_MELEE" "scout_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "scout_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "scout_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "scout_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "scout_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "scout_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "scout_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "scout_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "scout_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_MELEE_ALLCLASS" "scout_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "scout_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "scout_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "scout_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "scout_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "scout_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "scout_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "scout_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "scout_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_ITEM1" "scout_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "scout_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "scout_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "scout_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "scout_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "scout_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "scout_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "scout_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "scout_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_ITEM2_aimmatrix_swim_neutral" "scout_animations_anims\a_ITEM2_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_swim_down_right" "scout_animations_anims\a_ITEM2_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_center" "scout_animations_anims\a_ITEM2_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_left" "scout_animations_anims\a_ITEM2_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_right" "scout_animations_anims\a_ITEM2_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_center" "scout_animations_anims\a_ITEM2_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_left" "scout_animations_anims\a_ITEM2_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_right" "scout_animations_anims\a_ITEM2_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_center" "scout_animations_anims\a_ITEM2_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_left" "scout_animations_anims\a_ITEM2_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_straight_up" "scout_animations_anims\a_ITEM2_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM2" "scout_animations_anims\a_swimCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM2" "scout_animations_anims\a_swimS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM2" "scout_animations_anims\a_swimSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM2" "scout_animations_anims\a_swimE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM2" "scout_animations_anims\a_swimNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM2" "scout_animations_anims\a_swimN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM2" "scout_animations_anims\a_swimNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM2" "scout_animations_anims\a_swimW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM2" "scout_animations_anims\a_swimSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "scout_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "scout_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "scout_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "scout_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "scout_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "scout_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "scout_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "scout_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "scout_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "scout_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "scout_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "scout_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "scout_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "scout_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "scout_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "scout_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "scout_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "scout_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_aimmatrix_runS_neutral" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_runS_down_right" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_down_center" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_down_left" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_mid_right" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_mid_center" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_mid_left" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_up_right" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_up_center" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_up_left" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_runS_straight_up" "scout_animations_anims\a_PRIMARY_aimmatrix_runS_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_crouch_walkCenter_PRIMARY" "scout_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "scout_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "scout_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "scout_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "scout_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "scout_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "scout_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "scout_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "scout_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "scout_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "scout_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "scout_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "scout_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "scout_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "scout_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "scout_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "scout_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "scout_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_Walk_SECONDARY" "scout_animations_anims\a_blend_crouchN_crouch_Walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkCenter_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkS_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkSE_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkE_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkNE_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkN_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkNW_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkW_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_Walk_SECONDARY" "scout_animations_anims\a_crouch_walkSW_crouch_Walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "scout_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "scout_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "scout_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "scout_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "scout_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "scout_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "scout_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "scout_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "scout_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "scout_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "scout_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "scout_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "scout_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "scout_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "scout_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "scout_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "scout_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "scout_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "scout_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "scout_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "scout_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "scout_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "scout_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "scout_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "scout_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "scout_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "scout_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "scout_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "scout_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "scout_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "scout_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "scout_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "scout_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "scout_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "scout_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "scout_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "scout_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "scout_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "scout_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "scout_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "scout_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM2" "scout_animations_anims\a_runCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM2" "scout_animations_anims\a_runS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM2" "scout_animations_anims\a_runSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM2" "scout_animations_anims\a_runE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM2" "scout_animations_anims\a_runNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM2" "scout_animations_anims\a_runN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM2" "scout_animations_anims\a_runNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM2" "scout_animations_anims\a_runW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM2" "scout_animations_anims\a_runSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_ITEM2_aimmatrix_runS_neutral" "scout_animations_anims\a_ITEM2_aimmatrix_runS_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_runS_down_right" "scout_animations_anims\a_ITEM2_aimmatrix_runS_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_down_center" "scout_animations_anims\a_ITEM2_aimmatrix_runS_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_down_left" "scout_animations_anims\a_ITEM2_aimmatrix_runS_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_mid_right" "scout_animations_anims\a_ITEM2_aimmatrix_runS_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_mid_center" "scout_animations_anims\a_ITEM2_aimmatrix_runS_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_mid_left" "scout_animations_anims\a_ITEM2_aimmatrix_runS_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_up_right" "scout_animations_anims\a_ITEM2_aimmatrix_runS_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_up_center" "scout_animations_anims\a_ITEM2_aimmatrix_runS_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_up_left" "scout_animations_anims\a_ITEM2_aimmatrix_runS_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_runS_straight_up" "scout_animations_anims\a_ITEM2_aimmatrix_runS_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_blend_crouchN_crouch_walk_ITEM2" "scout_animations_anims\a_blend_crouchN_crouch_walk_ITEM2.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkS_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkSE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkNE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkN_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkNW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM2" "scout_animations_anims\a_crouch_walkSW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_primary" "scout_animations_anims\a_jumpstart_primary.smd" {
	fps 30
}
$animation "a_jumpstart_N_primary" "scout_animations_anims\a_jumpstart_N_primary.smd" {
	fps 30
}
$animation "a_jumpstart_NE_primary" "scout_animations_anims\a_jumpstart_NE_primary.smd" {
	fps 30
}
$animation "a_jumpstart_NW_primary" "scout_animations_anims\a_jumpstart_NW_primary.smd" {
	fps 30
}
$animation "a_jumpstart_E_primary" "scout_animations_anims\a_jumpstart_E_primary.smd" {
	fps 30
}
$animation "a_jumpstart_SE_primary" "scout_animations_anims\a_jumpstart_SE_primary.smd" {
	fps 30
}
$animation "a_jumpstart_W_primary" "scout_animations_anims\a_jumpstart_W_primary.smd" {
	fps 30
}
$animation "a_jumpstart_SW_primary" "scout_animations_anims\a_jumpstart_SW_primary.smd" {
	fps 30
}
$animation "a_jumpstart_S_primary" "scout_animations_anims\a_jumpstart_S_primary.smd" {
	fps 30
}
$animation "a_jumpFloat_primary" "scout_animations_anims\a_jumpFloat_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_primary" "scout_animations_anims\a_jumpFloat_N_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_primary" "scout_animations_anims\a_jumpFloat_NE_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_primary" "scout_animations_anims\a_jumpFloat_NW_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_primary" "scout_animations_anims\a_jumpFloat_E_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_primary" "scout_animations_anims\a_jumpFloat_SE_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_primary" "scout_animations_anims\a_jumpFloat_W_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_primary" "scout_animations_anims\a_jumpFloat_SW_primary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_primary" "scout_animations_anims\a_jumpFloat_S_primary.smd" {
	fps 30
	loop
}
$animation "a_crouchjump_center_primary" "scout_animations_anims\a_crouchjump_center_primary.smd" {
	fps 30
}
$animation "a_crouchjump_N_primary" "scout_animations_anims\a_crouchjump_N_primary.smd" {
	fps 30
}
$animation "a_crouchjump_NE_primary" "scout_animations_anims\a_crouchjump_NE_primary.smd" {
	fps 30
}
$animation "a_crouchjump_NW_primary" "scout_animations_anims\a_crouchjump_NW_primary.smd" {
	fps 30
}
$animation "a_crouchjump_E_primary" "scout_animations_anims\a_crouchjump_E_primary.smd" {
	fps 30
}
$animation "a_crouchjump_SE_primary" "scout_animations_anims\a_crouchjump_SE_primary.smd" {
	fps 30
}
$animation "a_crouchjump_W_primary" "scout_animations_anims\a_crouchjump_W_primary.smd" {
	fps 30
}
$animation "a_crouchjump_SW_primary" "scout_animations_anims\a_crouchjump_SW_primary.smd" {
	fps 30
}
$animation "a_crouchjump_S_primary" "scout_animations_anims\a_crouchjump_S_primary.smd" {
	fps 30
}
$animation "a_jumpstart_secondary" "scout_animations_anims\a_jumpstart_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_N_secondary" "scout_animations_anims\a_jumpstart_N_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_NE_secondary" "scout_animations_anims\a_jumpstart_NE_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_NW_secondary" "scout_animations_anims\a_jumpstart_NW_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_E_secondary" "scout_animations_anims\a_jumpstart_E_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_SE_secondary" "scout_animations_anims\a_jumpstart_SE_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_W_secondary" "scout_animations_anims\a_jumpstart_W_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_SW_secondary" "scout_animations_anims\a_jumpstart_SW_secondary.smd" {
	fps 30
}
$animation "a_jumpstart_S_secondary" "scout_animations_anims\a_jumpstart_S_secondary.smd" {
	fps 30
}
$animation "a_jumpFloat_secondary" "scout_animations_anims\a_jumpFloat_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_secondary" "scout_animations_anims\a_jumpFloat_N_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_secondary" "scout_animations_anims\a_jumpFloat_NE_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_secondary" "scout_animations_anims\a_jumpFloat_NW_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_secondary" "scout_animations_anims\a_jumpFloat_E_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_secondary" "scout_animations_anims\a_jumpFloat_SE_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_secondary" "scout_animations_anims\a_jumpFloat_W_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_secondary" "scout_animations_anims\a_jumpFloat_SW_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_secondary" "scout_animations_anims\a_jumpFloat_S_secondary.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_melee" "scout_animations_anims\a_jumpstart_melee.smd" {
	fps 30
}
$animation "a_jumpstart_N_melee" "scout_animations_anims\a_jumpstart_N_melee.smd" {
	fps 30
}
$animation "a_jumpstart_NE_melee" "scout_animations_anims\a_jumpstart_NE_melee.smd" {
	fps 30
}
$animation "a_jumpstart_NW_melee" "scout_animations_anims\a_jumpstart_NW_melee.smd" {
	fps 30
}
$animation "a_jumpstart_E_melee" "scout_animations_anims\a_jumpstart_E_melee.smd" {
	fps 30
}
$animation "a_jumpstart_SE_melee" "scout_animations_anims\a_jumpstart_SE_melee.smd" {
	fps 30
}
$animation "a_jumpstart_W_melee" "scout_animations_anims\a_jumpstart_W_melee.smd" {
	fps 30
}
$animation "a_jumpstart_SW_melee" "scout_animations_anims\a_jumpstart_SW_melee.smd" {
	fps 30
}
$animation "a_jumpstart_S_melee" "scout_animations_anims\a_jumpstart_S_melee.smd" {
	fps 30
}
$animation "a_jumpFloat_melee" "scout_animations_anims\a_jumpFloat_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_melee" "scout_animations_anims\a_jumpFloat_N_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_melee" "scout_animations_anims\a_jumpFloat_NE_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_melee" "scout_animations_anims\a_jumpFloat_NW_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_melee" "scout_animations_anims\a_jumpFloat_E_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_melee" "scout_animations_anims\a_jumpFloat_SE_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_melee" "scout_animations_anims\a_jumpFloat_W_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_melee" "scout_animations_anims\a_jumpFloat_SW_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_melee" "scout_animations_anims\a_jumpFloat_S_melee.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_N_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_N_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_NE_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_NE_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_NW_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_NW_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_E_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_E_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_SE_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_SE_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_W_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_W_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_SW_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_SW_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpstart_S_MELEE_ALLCLASS" "scout_animations_anims\a_jumpstart_S_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_jumpFloat_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_N_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_NE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_NW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_E_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_SE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_W_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_SW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_MELEE_ALLCLASS" "scout_animations_anims\a_jumpFloat_S_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_ITEM1" "scout_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_N_ITEM1" "scout_animations_anims\a_jumpstart_N_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_NE_ITEM1" "scout_animations_anims\a_jumpstart_NE_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_NW_ITEM1" "scout_animations_anims\a_jumpstart_NW_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_E_ITEM1" "scout_animations_anims\a_jumpstart_E_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_SE_ITEM1" "scout_animations_anims\a_jumpstart_SE_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_W_ITEM1" "scout_animations_anims\a_jumpstart_W_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_SW_ITEM1" "scout_animations_anims\a_jumpstart_SW_ITEM1.smd" {
	fps 30
}
$animation "a_jumpstart_S_ITEM1" "scout_animations_anims\a_jumpstart_S_ITEM1.smd" {
	fps 30
}
$animation "a_jumpFloat_ITEM1" "scout_animations_anims\a_jumpFloat_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_ITEM1" "scout_animations_anims\a_jumpFloat_N_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_ITEM1" "scout_animations_anims\a_jumpFloat_NE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_ITEM1" "scout_animations_anims\a_jumpFloat_NW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_ITEM1" "scout_animations_anims\a_jumpFloat_E_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_ITEM1" "scout_animations_anims\a_jumpFloat_SE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_ITEM1" "scout_animations_anims\a_jumpFloat_W_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_ITEM1" "scout_animations_anims\a_jumpFloat_SW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_ITEM1" "scout_animations_anims\a_jumpFloat_S_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_ITEM2" "scout_animations_anims\a_jumpstart_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_N_ITEM2" "scout_animations_anims\a_jumpstart_N_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_NE_ITEM2" "scout_animations_anims\a_jumpstart_NE_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_NW_ITEM2" "scout_animations_anims\a_jumpstart_NW_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_E_ITEM2" "scout_animations_anims\a_jumpstart_E_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_SE_ITEM2" "scout_animations_anims\a_jumpstart_SE_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_W_ITEM2" "scout_animations_anims\a_jumpstart_W_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_SW_ITEM2" "scout_animations_anims\a_jumpstart_SW_ITEM2.smd" {
	fps 30
}
$animation "a_jumpstart_S_ITEM2" "scout_animations_anims\a_jumpstart_S_ITEM2.smd" {
	fps 30
}
$animation "a_jumpFloat_ITEM2" "scout_animations_anims\a_jumpFloat_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_ITEM2" "scout_animations_anims\a_jumpFloat_N_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_ITEM2" "scout_animations_anims\a_jumpFloat_NE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_ITEM2" "scout_animations_anims\a_jumpFloat_NW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_ITEM2" "scout_animations_anims\a_jumpFloat_E_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_ITEM2" "scout_animations_anims\a_jumpFloat_SE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_ITEM2" "scout_animations_anims\a_jumpFloat_W_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_ITEM2" "scout_animations_anims\a_jumpFloat_SW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_ITEM2" "scout_animations_anims\a_jumpFloat_S_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_jumpstart_loser" "scout_animations_anims\a_jumpstart_loser.smd" {
	fps 30
}
$animation "a_jumpstart_N_loser" "scout_animations_anims\a_jumpstart_N_loser.smd" {
	fps 30
}
$animation "a_jumpstart_NE_loser" "scout_animations_anims\a_jumpstart_NE_loser.smd" {
	fps 30
}
$animation "a_jumpstart_NW_loser" "scout_animations_anims\a_jumpstart_NW_loser.smd" {
	fps 30
}
$animation "a_jumpstart_E_loser" "scout_animations_anims\a_jumpstart_E_loser.smd" {
	fps 30
}
$animation "a_jumpstart_SE_loser" "scout_animations_anims\a_jumpstart_SE_loser.smd" {
	fps 30
}
$animation "a_jumpstart_W_loser" "scout_animations_anims\a_jumpstart_W_loser.smd" {
	fps 30
}
$animation "a_jumpstart_SW_loser" "scout_animations_anims\a_jumpstart_SW_loser.smd" {
	fps 30
}
$animation "a_jumpstart_S_loser" "scout_animations_anims\a_jumpstart_S_loser.smd" {
	fps 30
}
$animation "a_jumpFloat_loser" "scout_animations_anims\a_jumpFloat_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_N_loser" "scout_animations_anims\a_jumpFloat_N_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NE_loser" "scout_animations_anims\a_jumpFloat_NE_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_NW_loser" "scout_animations_anims\a_jumpFloat_NW_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_E_loser" "scout_animations_anims\a_jumpFloat_E_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SE_loser" "scout_animations_anims\a_jumpFloat_SE_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_W_loser" "scout_animations_anims\a_jumpFloat_W_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_SW_loser" "scout_animations_anims\a_jumpFloat_SW_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpFloat_S_loser" "scout_animations_anims\a_jumpFloat_S_loser.smd" {
	fps 30
	loop
}
$animation "a_jumpDouble_center_primary" "scout_animations_anims\a_jumpDouble_center_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_N_primary" "scout_animations_anims\a_jumpDouble_N_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_NE_primary" "scout_animations_anims\a_jumpDouble_NE_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_NW_primary" "scout_animations_anims\a_jumpDouble_NW_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_E_primary" "scout_animations_anims\a_jumpDouble_E_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_S_primary" "scout_animations_anims\a_jumpDouble_S_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_W_primary" "scout_animations_anims\a_jumpDouble_W_primary.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_center_loser" "scout_animations_anims\a_jumpDouble_center_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_N_loser" "scout_animations_anims\a_jumpDouble_N_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_NE_loser" "scout_animations_anims\a_jumpDouble_NE_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_NW_loser" "scout_animations_anims\a_jumpDouble_NW_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_E_loser" "scout_animations_anims\a_jumpDouble_E_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_S_loser" "scout_animations_anims\a_jumpDouble_S_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_jumpDouble_W_loser" "scout_animations_anims\a_jumpDouble_W_loser.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_stun_startpose" "scout_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "scout_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "scout_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "scout_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_PRIMARY" "scout_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	snap
	// delta
}

$sequence "AttackCrouch_PRIMARY" "scout_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "scout_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "layer_reload_standing_arms_primary_start" "scout_animations_anims\layer_reload_standing_arms_primary_start.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_standing_arms_primary_loop" "scout_animations_anims\layer_reload_standing_arms_primary_loop.smd" {
	fps 30
	loop
	hidden
}

$sequence "layer_reload_standing_arms_primary_end" "scout_animations_anims\layer_reload_standing_arms_primary_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_start" "scout_animations_anims\PRIMARY_reload_start.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_start"
}

$sequence "PRIMARY_reload_loop" "scout_animations_anims\PRIMARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_primary_loop"
}

$sequence "PRIMARY_reload_end" "scout_animations_anims\PRIMARY_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_end"
}

$sequence "PRIMARY_crouch_reload_start" "scout_animations_anims\PRIMARY_crouch_reload_start.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_start"
}

$sequence "PRIMARY_crouch_reload_loop" "scout_animations_anims\PRIMARY_crouch_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_primary_loop"
}

$sequence "PRIMARY_crouch_reload_end" "scout_animations_anims\PRIMARY_crouch_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_end"
}

$sequence "PRIMARY_swim_reload_start" "scout_animations_anims\PRIMARY_swim_reload_start.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_start"
}

$sequence "PRIMARY_swim_reload_loop" "scout_animations_anims\PRIMARY_swim_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_primary_loop"
}

$sequence "PRIMARY_swim_reload_end" "scout_animations_anims\PRIMARY_swim_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_end"
}

$sequence "PRIMARY_airwalk_reload_start" "scout_animations_anims\PRIMARY_airwalk_reload_start.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_start"
}

$sequence "PRIMARY_airwalk_reload_loop" "scout_animations_anims\PRIMARY_airwalk_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_primary_loop"
}

$sequence "PRIMARY_airwalk_reload_end" "scout_animations_anims\PRIMARY_airwalk_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_standing_arms_primary_end"
}

$sequence "layer_placeSapper_ArmL" "scout_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "scout_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "scout_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "scout_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "scout_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "layer_reload_standing_arms_secondary" "scout_animations_anims\layer_reload_standing_arms_secondary.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY" "scout_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary"
}

$sequence "ReloadCrouch_SECONDARY" "scout_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary"
}

$sequence "ReloadSwim_SECONDARY" "scout_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary"
}

$sequence "ReloadAirwalk_SECONDARY" "scout_animations_anims\ReloadAirwalk_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary"
}

$sequence "layer_SECONDARY_WepGrip" "scout_animations_anims\layer_SECONDARY_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "ITEM2_aimmatrix_idle" {
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_up_right"
	"a_ITEM2_aimmatrix_idle_up_center"
	"a_ITEM2_aimmatrix_idle_up_left"
	"a_ITEM2_aimmatrix_idle_mid_right"
	"a_ITEM2_aimmatrix_idle_mid_center"
	"a_ITEM2_aimmatrix_idle_mid_left"
	"a_ITEM2_aimmatrix_idle_down_right"
	"a_ITEM2_aimmatrix_idle_down_center"
	"a_ITEM2_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_run" {
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_up_right"
	"a_ITEM2_aimmatrix_run_up_center"
	"a_ITEM2_aimmatrix_run_up_left"
	"a_ITEM2_aimmatrix_run_mid_right"
	"a_ITEM2_aimmatrix_run_mid_center"
	"a_ITEM2_aimmatrix_run_mid_left"
	"a_ITEM2_aimmatrix_run_down_right"
	"a_ITEM2_aimmatrix_run_down_center"
	"a_ITEM2_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_crouch_idle" {
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_up_right"
	"a_ITEM2_aimmatrix_crouch_idle_up_center"
	"a_ITEM2_aimmatrix_crouch_idle_up_left"
	"a_ITEM2_aimmatrix_crouch_idle_mid_right"
	"a_ITEM2_aimmatrix_crouch_idle_mid_center"
	"a_ITEM2_aimmatrix_crouch_idle_mid_left"
	"a_ITEM2_aimmatrix_crouch_idle_down_right"
	"a_ITEM2_aimmatrix_crouch_idle_down_center"
	"a_ITEM2_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_ITEM2" "scout_animations_anims\AttackStand_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM2" 1
	// delta
}

$sequence "AttackCrouch_ITEM2" "scout_animations_anims\AttackCrouch_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM2" 1
	// delta
}

$sequence "AttackSwim_ITEM2" "scout_animations_anims\AttackSwim_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_ITEM2" 1
	// delta
}

$sequence "layer_reload_standing_arms_item2" "scout_animations_anims\layer_reload_standing_arms_item2.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_ITEM2" "scout_animations_anims\ReloadStand_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_ITEM2" 1
	// delta
	// addlayer "layer_reload_standing_arms_item2"
}

$sequence "ReloadCrouch_ITEM2" "scout_animations_anims\ReloadCrouch_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_ITEM2" 1
	// delta
	// addlayer "layer_reload_standing_arms_item2"
}

$sequence "ReloadSwim_ITEM2" "scout_animations_anims\ReloadSwim_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_ITEM2" 1
	// delta
	// addlayer "layer_reload_standing_arms_item2"
}

$sequence "ReloadAirwalk_ITEM2" "scout_animations_anims\ReloadAirwalk_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_ITEM2" 1
	// delta
	// addlayer "layer_reload_standing_arms_item2"
}

$sequence "layer_ITEM2_WepGrip" "scout_animations_anims\layer_ITEM2_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "layer_reload_standing_arms_secondary_2" "scout_animations_anims\layer_reload_standing_arms_secondary_2.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY_2" "scout_animations_anims\ReloadStand_SECONDARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary_2"
}

$sequence "ReloadCrouch_SECONDARY_2" "scout_animations_anims\ReloadCrouch_SECONDARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary_2"
}

$sequence "ReloadSwim_SECONDARY_2" "scout_animations_anims\ReloadSwim_SECONDARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary_2"
}

$sequence "ReloadAirwalk_SECONDARY_2" "scout_animations_anims\ReloadAirwalk_SECONDARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_secondary_2"
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_AttackStandMelee_arms" "scout_animations_anims\layer_AttackStandMelee_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_melee_swing" "scout_animations_anims\layer_melee_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_AttackStandMelee_arms"
}

$sequence "layer_AttackStandMelee_runS_arms" "scout_animations_anims\layer_AttackStandMelee_runS_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_melee_swing_runS" "scout_animations_anims\layer_melee_swing_runS.smd" {
	fps 60
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_AttackStandMelee_runS_arms"
}

$sequence "MELEE_swing" "scout_animations_anims\MELEE_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	blendlayer "layer_melee_swing" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_melee_swing_runS" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "MELEE_crouch_swing" "scout_animations_anims\MELEE_crouch_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// addlayer "layer_melee_swing"
}

$sequence "AttackSwim_MELEE" "scout_animations_anims\AttackSwim_MELEE.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// delta
}

$sequence "layer_MELEE_WepGrip" "scout_animations_anims\layer_MELEE_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "a_flinch01" "scout_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_AttackStandMelee_allclass_arms" "scout_animations_anims\layer_AttackStandMelee_allclass_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_melee_allclass_swing" "scout_animations_anims\layer_melee_allclass_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_AttackStandMelee_allclass_arms"
}

$sequence "layer_AttackStandMelee_allclass_runS_arms" "scout_animations_anims\layer_AttackStandMelee_allclass_runS_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_melee_allclass_swing_runS" "scout_animations_anims\layer_melee_allclass_swing_runS.smd" {
	fps 60
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_AttackStandMelee_allclass_runS_arms"
}

$sequence "MELEE_allclass_swing" "scout_animations_anims\MELEE_allclass_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	blendlayer "layer_melee_allclass_swing" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_melee_allclass_swing_runS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	// addlayer "r_handposes"
}

$sequence "MELEE_allclass_crouch_swing" "scout_animations_anims\MELEE_allclass_crouch_swing.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// addlayer "layer_melee_allclass_swing"
	// addlayer "r_handposes"
}

$sequence "AttackSwim_MELEE_allclass" "scout_animations_anims\AttackSwim_MELEE_allclass.smd" {
	fps 60
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "layer_MELEE_allclass_WepGrip" "scout_animations_anims\layer_MELEE_allclass_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "STUN_aimmatrix_idle" {
	"a_STUN_aimmatrix_idle_straight_up"
	"a_STUN_aimmatrix_idle_straight_up"
	"a_STUN_aimmatrix_idle_straight_up"
	"a_STUN_aimmatrix_idle_up_right"
	"a_STUN_aimmatrix_idle_up_center"
	"a_STUN_aimmatrix_idle_up_left"
	"a_STUN_aimmatrix_idle_mid_right"
	"a_STUN_aimmatrix_idle_mid_center"
	"a_STUN_aimmatrix_idle_mid_left"
	"a_STUN_aimmatrix_idle_down_right"
	"a_STUN_aimmatrix_idle_down_center"
	"a_STUN_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "STUN_aimmatrix_run" {
	"a_STUN_aimmatrix_run_straight_up"
	"a_STUN_aimmatrix_run_straight_up"
	"a_STUN_aimmatrix_run_straight_up"
	"a_STUN_aimmatrix_run_up_right"
	"a_STUN_aimmatrix_run_up_center"
	"a_STUN_aimmatrix_run_up_left"
	"a_STUN_aimmatrix_run_mid_right"
	"a_STUN_aimmatrix_run_mid_center"
	"a_STUN_aimmatrix_run_mid_left"
	"a_STUN_aimmatrix_run_down_right"
	"a_STUN_aimmatrix_run_down_center"
	"a_STUN_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "STUN_aimmatrix_crouch_idle" {
	"a_STUN_aimmatrix_crouch_idle_straight_up"
	"a_STUN_aimmatrix_crouch_idle_straight_up"
	"a_STUN_aimmatrix_crouch_idle_straight_up"
	"a_STUN_aimmatrix_crouch_idle_up_right"
	"a_STUN_aimmatrix_crouch_idle_up_center"
	"a_STUN_aimmatrix_crouch_idle_up_left"
	"a_STUN_aimmatrix_crouch_idle_mid_right"
	"a_STUN_aimmatrix_crouch_idle_mid_center"
	"a_STUN_aimmatrix_crouch_idle_mid_left"
	"a_STUN_aimmatrix_crouch_idle_down_right"
	"a_STUN_aimmatrix_crouch_idle_down_center"
	"a_STUN_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_stun_swing_arms" "scout_animations_anims\layer_stun_swing_arms.smd" {
	fps 30
	hidden
}

$sequence "layer_stun_swing" "scout_animations_anims\layer_stun_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_stun_swing_arms"
}

$sequence "layer_stun_swing_arm_s" "scout_animations_anims\layer_stun_swing_arm_s.smd" {
	fps 30
	hidden
}

$sequence "layer_stun_swing_S" "scout_animations_anims\layer_stun_swing_S.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_stun_swing_arm_s"
}

$sequence "stun_swing" "scout_animations_anims\stun_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_SECONDARY" 1
	blendlayer "layer_stun_swing" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_stun_swing_S" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "stun_swing_crouch" "scout_animations_anims\stun_swing_crouch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_SECONDARY" 11
	// addlayer "layer_stun_swing_arms"
}

$sequence "layer_STUN_WepGrip" "scout_animations_anims\layer_STUN_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_ITEM1_fire" "scout_animations_anims\armslayer_ITEM1_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_fire" "scout_animations_anims\bodylayer_ITEM1_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_fire" "scout_animations_anims\ITEM1_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// addlayer "bodylayer_ITEM1_fire"
	// addlayer "armslayer_ITEM1_fire"
}

$sequence "armslayer_ITEM1_Crouch_fire" "scout_animations_anims\armslayer_ITEM1_Crouch_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_Crouch_fire" "scout_animations_anims\bodylayer_ITEM1_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_Crouch_fire" "scout_animations_anims\ITEM1_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM1" 1
	// addlayer "bodylayer_ITEM1_Crouch_fire"
	// addlayer "armslayer_ITEM1_Crouch_fire"
}

$sequence "layer_ITEM1_WepGrip" "scout_animations_anims\layer_ITEM1_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "layer_gesture_primary_go_armL" "scout_animations_anims\layer_gesture_primary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_primary_go_runN_armL" "scout_animations_anims\layer_gesture_primary_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_go" "scout_animations_anims\gesture_primary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
	blendlayer "layer_gesture_primary_go_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_primary_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_primary_help_armL" "scout_animations_anims\layer_gesture_primary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_help" "scout_animations_anims\gesture_primary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_help_armL"
}

$sequence "layer_gesture_primary_cheer_armL" "scout_animations_anims\layer_gesture_primary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_cheer" "scout_animations_anims\gesture_primary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_cheer_armL"
}

$sequence "layer_gesture_primary_positive_armL" "scout_animations_anims\layer_gesture_primary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_positive" "scout_animations_anims\gesture_primary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_positive_armL"
}

$sequence "layer_gesture_secondary_go_armL" "scout_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_secondary_go_runN_armL" "scout_animations_anims\layer_gesture_secondary_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "scout_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_secondary_go_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_secondary_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_secondary_help_armL" "scout_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "scout_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_secondary_cheer_armL" "scout_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "scout_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_positive_armL" "scout_animations_anims\layer_gesture_secondary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_secondary_positive" "scout_animations_anims\layer_gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	// addlayer "layer_gesture_secondary_positive_armL"
}

$sequence "layer_gesture_secondary_positive_runN_armL" "scout_animations_anims\layer_gesture_secondary_positive_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_secondary_positive_runN" "scout_animations_anims\layer_gesture_secondary_positive_runN.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendlayer "layer_gesture_secondary_positive_runN_armL" 0 0.15 0.85 1 spline
}

$sequence "gesture_secondary_positive" "scout_animations_anims\gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY" 1
	blendlayer "layer_gesture_secondary_positive_runN" -2 -1 -0.8 -0.2 spline poseparameter move_x
	blendlayer "layer_gesture_secondary_positive" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_secondary_positive_runN" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_melee_go_armL" "scout_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "scout_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_go_armL"
}

$sequence "layer_gesture_melee_help_armL" "scout_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "scout_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_help_armL"
}

$sequence "layer_gesture_melee_cheer_armL" "scout_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "scout_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_cheer_armL"
}

$sequence "layer_gesture_melee_positive_armL" "scout_animations_anims\layer_gesture_melee_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_positive" "scout_animations_anims\gesture_melee_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_positive_armL"
}

$sequence "layer_gesture_ITEM1_go_armL" "scout_animations_anims\layer_gesture_ITEM1_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM1_go" "scout_animations_anims\gesture_ITEM1_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_ITEM1" 1
	// delta
	// addlayer "layer_gesture_ITEM1_go_armL"
}

$sequence "layer_gesture_ITEM1_help_armL" "scout_animations_anims\layer_gesture_ITEM1_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM1_help" "scout_animations_anims\gesture_ITEM1_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_ITEM1" 1
	// delta
	// addlayer "layer_gesture_ITEM1_help_armL"
}

$sequence "layer_gesture_ITEM1_cheer_armL" "scout_animations_anims\layer_gesture_ITEM1_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM1_cheer" "scout_animations_anims\gesture_ITEM1_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_ITEM1" 1
	// delta
	// addlayer "layer_gesture_ITEM1_cheer_armL"
}

$sequence "layer_gesture_ITEM1_positive_armL" "scout_animations_anims\layer_gesture_ITEM1_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM1_positive" "scout_animations_anims\gesture_ITEM1_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_ITEM1" 1
	// delta
	// addlayer "layer_gesture_ITEM1_positive_armL"
}

$sequence "layer_gesture_ITEM2_go_armL" "scout_animations_anims\layer_gesture_ITEM2_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_ITEM2_go_runN_armL" "scout_animations_anims\layer_gesture_ITEM2_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM2_go" "scout_animations_anims\gesture_ITEM2_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_ITEM2" 1
	// delta
	blendlayer "layer_gesture_ITEM2_go_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_ITEM2_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_ITEM2_help_armL" "scout_animations_anims\layer_gesture_ITEM2_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM2_help" "scout_animations_anims\gesture_ITEM2_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_ITEM2" 1
	// delta
	// addlayer "layer_gesture_ITEM2_help_armL"
}

$sequence "layer_gesture_ITEM2_cheer_armL" "scout_animations_anims\layer_gesture_ITEM2_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM2_cheer" "scout_animations_anims\gesture_ITEM2_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_ITEM2" 1
	// delta
	// addlayer "layer_gesture_ITEM2_cheer_armL"
}

$sequence "layer_gesture_ITEM2_positive_armL" "scout_animations_anims\layer_gesture_ITEM2_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_ITEM2_positive" "scout_animations_anims\gesture_ITEM2_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_ITEM2" 1
	// delta
	// addlayer "layer_gesture_ITEM2_positive_armL"
}

$sequence "layer_idleNoise" "scout_animations_anims\layer_idleNoise.smd" {
	fps 30
	// subtract "a_reference" 0
	loop
	// delta
	hidden
}

$sequence "stand_PRIMARY" "scout_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
	// addlayer "layer_idleNoise"
}

$sequence "stand_SECONDARY" "scout_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
	// addlayer "layer_idleNoise"
}

$sequence "stand_MELEE" "scout_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "scout_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "scout_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "scout_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "stand_ITEM2" "scout_animations_anims\stand_ITEM2.smd" {
	fps 30
	"ACT_MP_STAND_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
	// addlayer "layer_idleNoise"
}

$sequence "stand_STUN" "scout_animations_anims\stand_STUN.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "STUN_aimmatrix_idle"
}

$sequence "layer_null" "scout_animations_anims\layer_null.smd" {
	fps 30
	// subtract "a_reference" 0
	hidden
}

$sequence "crouch_PRIMARY" "scout_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "crouch_SECONDARY" "scout_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "scout_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "scout_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "scout_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "scout_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "crouch_ITEM2" "scout_animations_anims\crouch_ITEM2.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "layer_swim_SECONDARY_wepGrip" "scout_animations_anims\layer_swim_SECONDARY_wepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "Swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
	// addlayer "layer_swim_SECONDARY_wepGrip"
}

$sequence "layer_swim_MELEE_wepGrip" "scout_animations_anims\layer_swim_MELEE_wepGrip.smd" {
	fps 15
	loop
	hidden
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "Swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_idle"
	// addlayer "layer_swim_MELEE_wepGrip"
}

$sequence "layer_swim_MELEE_ALLCLASS_wepGrip" "scout_animations_anims\layer_swim_MELEE_ALLCLASS_wepGrip.smd" {
	fps 15
	loop
	hidden
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "Swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "layer_swim_MELEE_ALLCLASS_wepGrip"
}

$sequence "layer_swim_ITEM1_wepGrip" "scout_animations_anims\layer_swim_ITEM1_wepGrip.smd" {
	fps 15
	loop
	hidden
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "Swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_idle"
	// addlayer "layer_swim_ITEM1_wepGrip"
}

$sequence "ITEM2_aimmatrix_swim" {
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_up_right"
	"a_ITEM2_aimmatrix_swim_up_center"
	"a_ITEM2_aimmatrix_swim_up_left"
	"a_ITEM2_aimmatrix_swim_mid_right"
	"a_ITEM2_aimmatrix_swim_mid_center"
	"a_ITEM2_aimmatrix_swim_mid_left"
	"a_ITEM2_aimmatrix_swim_down_right"
	"a_ITEM2_aimmatrix_swim_down_center"
	"a_ITEM2_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM2" {
	"a_swimCenter_ITEM2"
	fps 30
	loop
}

$sequence "swim_ITEM2" {
	"a_swimSW_ITEM2"
	"a_swimS_ITEM2"
	"a_swimSE_ITEM2"
	"a_swimW_ITEM2"
	"a_swimCenter_ITEM2"
	"a_swimE_ITEM2"
	"a_swimNW_ITEM2"
	"a_swimN_ITEM2"
	"a_swimNE_ITEM2"
	fps 30
	"ACT_MP_SWIM_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "PRIMARY_aimmatrix_runS" {
	"a_PRIMARY_aimmatrix_runS_straight_up"
	"a_PRIMARY_aimmatrix_runS_straight_up"
	"a_PRIMARY_aimmatrix_runS_straight_up"
	"a_PRIMARY_aimmatrix_runS_up_right"
	"a_PRIMARY_aimmatrix_runS_up_center"
	"a_PRIMARY_aimmatrix_runS_up_left"
	"a_PRIMARY_aimmatrix_runS_mid_right"
	"a_PRIMARY_aimmatrix_runS_mid_center"
	"a_PRIMARY_aimmatrix_runS_mid_left"
	"a_PRIMARY_aimmatrix_runS_down_right"
	"a_PRIMARY_aimmatrix_runS_down_center"
	"a_PRIMARY_aimmatrix_runS_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	blendlayer "PRIMARY_aimmatrix_run" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "PRIMARY_aimmatrix_runS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_Walk_SECONDARY" {
	"a_crouch_walkSW_crouch_Walk_SECONDARY"
	"a_crouch_walkS_crouch_Walk_SECONDARY"
	"a_crouch_walkSE_crouch_Walk_SECONDARY"
	"a_crouch_walkW_crouch_Walk_SECONDARY"
	"a_crouch_walkCenter_crouch_Walk_SECONDARY"
	"a_crouch_walkE_crouch_Walk_SECONDARY"
	"a_crouch_walkNW_crouch_Walk_SECONDARY"
	"a_crouch_walkN_crouch_Walk_SECONDARY"
	"a_crouch_walkNE_crouch_Walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_idle"
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_idle"
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "ITEM2_aimmatrix_runS" {
	"a_ITEM2_aimmatrix_runS_straight_up"
	"a_ITEM2_aimmatrix_runS_straight_up"
	"a_ITEM2_aimmatrix_runS_straight_up"
	"a_ITEM2_aimmatrix_runS_up_right"
	"a_ITEM2_aimmatrix_runS_up_center"
	"a_ITEM2_aimmatrix_runS_up_left"
	"a_ITEM2_aimmatrix_runS_mid_right"
	"a_ITEM2_aimmatrix_runS_mid_center"
	"a_ITEM2_aimmatrix_runS_mid_left"
	"a_ITEM2_aimmatrix_runS_down_right"
	"a_ITEM2_aimmatrix_runS_down_center"
	"a_ITEM2_aimmatrix_runS_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "run_ITEM2" {
	"a_runSW_ITEM2"
	"a_runS_ITEM2"
	"a_runSE_ITEM2"
	"a_runW_ITEM2"
	"a_runCenter_ITEM2"
	"a_runE_ITEM2"
	"a_runNW_ITEM2"
	"a_runN_ITEM2"
	"a_runNE_ITEM2"
	fps 30
	"ACT_MP_RUN_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	blendlayer "ITEM2_aimmatrix_run" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "ITEM2_aimmatrix_runS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	{ event 7001 1.00000002980232 "right" }
	{ event 7001 6.99999976158142 "left" }
	{ event 7001 13.0000004768372 "right" }
	{ event 7001 19.0000004768372 "left" }
	{ event 7001 24.9999990463257 "right" }
	{ event 7001 30.9999990463257 "left" }
	{ event 7001 36.9999990463257 "right" }
	{ event 7001 42.9999990463257 "left" }
}

$sequence "crouch_walk_ITEM2" {
	"a_crouch_walkSW_crouch_walk_ITEM2"
	"a_crouch_walkS_crouch_walk_ITEM2"
	"a_crouch_walkSE_crouch_walk_ITEM2"
	"a_crouch_walkW_crouch_walk_ITEM2"
	"a_crouch_walkCenter_crouch_walk_ITEM2"
	"a_crouch_walkE_crouch_walk_ITEM2"
	"a_crouch_walkNW_crouch_walk_ITEM2"
	"a_crouch_walkN_crouch_walk_ITEM2"
	"a_crouch_walkNE_crouch_walk_ITEM2"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_crouch_idle"
}

$sequence "Jump_Start_primary" {
	"a_jumpstart_SW_primary"
	"a_jumpstart_S_primary"
	"a_jumpstart_SE_primary"
	"a_jumpstart_W_primary"
	"a_jumpstart_primary"
	"a_jumpstart_E_primary"
	"a_jumpstart_NW_primary"
	"a_jumpstart_N_primary"
	"a_jumpstart_NE_primary"
	fps 30
	"ACT_MP_JUMP_START_primary" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "jumpTest" "scout_animations_anims\jumpTest.smd" {
	fps 30
}

$sequence "layer_primary_jump_floatNoise" "scout_animations_anims\layer_primary_jump_floatNoise.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	realtime
}

$sequence "Jump_Float_primary" {
	"a_jumpFloat_SW_primary"
	"a_jumpFloat_S_primary"
	"a_jumpFloat_SE_primary"
	"a_jumpFloat_W_primary"
	"a_jumpFloat_primary"
	"a_jumpFloat_E_primary"
	"a_jumpFloat_NW_primary"
	"a_jumpFloat_N_primary"
	"a_jumpFloat_NE_primary"
	fps 30
	"ACT_MP_JUMP_FLOAT_primary" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "Jump_crouchjump_primary" {
	"a_crouchjump_SW_primary"
	"a_crouchjump_S_primary"
	"a_crouchjump_SE_primary"
	"a_crouchjump_W_primary"
	"a_crouchjump_center_primary"
	"a_crouchjump_E_primary"
	"a_crouchjump_NW_primary"
	"a_crouchjump_N_primary"
	"a_crouchjump_NE_primary"
	fps 30
	"ACT_MP_DOUBLEJUMP_CROUCH_PRIMARY" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "Jump_Start_secondary" {
	"a_jumpstart_SW_secondary"
	"a_jumpstart_S_secondary"
	"a_jumpstart_SE_secondary"
	"a_jumpstart_W_secondary"
	"a_jumpstart_secondary"
	"a_jumpstart_E_secondary"
	"a_jumpstart_NW_secondary"
	"a_jumpstart_N_secondary"
	"a_jumpstart_NE_secondary"
	fps 30
	"ACT_MP_JUMP_START_secondary" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "Jump_Float_secondary" {
	"a_jumpFloat_SW_secondary"
	"a_jumpFloat_S_secondary"
	"a_jumpFloat_SE_secondary"
	"a_jumpFloat_W_secondary"
	"a_jumpFloat_secondary"
	"a_jumpFloat_E_secondary"
	"a_jumpFloat_NW_secondary"
	"a_jumpFloat_N_secondary"
	"a_jumpFloat_NE_secondary"
	fps 30
	"ACT_MP_JUMP_FLOAT_secondary" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "Jump_Start_melee" {
	"a_jumpstart_SW_melee"
	"a_jumpstart_S_melee"
	"a_jumpstart_SE_melee"
	"a_jumpstart_W_melee"
	"a_jumpstart_melee"
	"a_jumpstart_E_melee"
	"a_jumpstart_NW_melee"
	"a_jumpstart_N_melee"
	"a_jumpstart_NE_melee"
	fps 30
	"ACT_MP_JUMP_START_melee" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "Jump_Float_melee" {
	"a_jumpFloat_SW_melee"
	"a_jumpFloat_S_melee"
	"a_jumpFloat_SE_melee"
	"a_jumpFloat_W_melee"
	"a_jumpFloat_melee"
	"a_jumpFloat_E_melee"
	"a_jumpFloat_NW_melee"
	"a_jumpFloat_N_melee"
	"a_jumpFloat_NE_melee"
	fps 30
	"ACT_MP_JUMP_FLOAT_melee" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "Jump_Start_MELEE_ALLCLASS" {
	"a_jumpstart_SW_MELEE_ALLCLASS"
	"a_jumpstart_S_MELEE_ALLCLASS"
	"a_jumpstart_SE_MELEE_ALLCLASS"
	"a_jumpstart_W_MELEE_ALLCLASS"
	"a_jumpstart_MELEE_ALLCLASS"
	"a_jumpstart_E_MELEE_ALLCLASS"
	"a_jumpstart_NW_MELEE_ALLCLASS"
	"a_jumpstart_N_MELEE_ALLCLASS"
	"a_jumpstart_NE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "Jump_Float_MELEE_ALLCLASS" {
	"a_jumpFloat_SW_MELEE_ALLCLASS"
	"a_jumpFloat_S_MELEE_ALLCLASS"
	"a_jumpFloat_SE_MELEE_ALLCLASS"
	"a_jumpFloat_W_MELEE_ALLCLASS"
	"a_jumpFloat_MELEE_ALLCLASS"
	"a_jumpFloat_E_MELEE_ALLCLASS"
	"a_jumpFloat_NW_MELEE_ALLCLASS"
	"a_jumpFloat_N_MELEE_ALLCLASS"
	"a_jumpFloat_NE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "Jump_Start_ITEM1" {
	"a_jumpstart_SW_ITEM1"
	"a_jumpstart_S_ITEM1"
	"a_jumpstart_SE_ITEM1"
	"a_jumpstart_W_ITEM1"
	"a_jumpstart_ITEM1"
	"a_jumpstart_E_ITEM1"
	"a_jumpstart_NW_ITEM1"
	"a_jumpstart_N_ITEM1"
	"a_jumpstart_NE_ITEM1"
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "Jump_Float_ITEM1" {
	"a_jumpFloat_SW_ITEM1"
	"a_jumpFloat_S_ITEM1"
	"a_jumpFloat_SE_ITEM1"
	"a_jumpFloat_W_ITEM1"
	"a_jumpFloat_ITEM1"
	"a_jumpFloat_E_ITEM1"
	"a_jumpFloat_NW_ITEM1"
	"a_jumpFloat_N_ITEM1"
	"a_jumpFloat_NE_ITEM1"
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "Jump_Start_ITEM2" {
	"a_jumpstart_SW_ITEM2"
	"a_jumpstart_S_ITEM2"
	"a_jumpstart_SE_ITEM2"
	"a_jumpstart_W_ITEM2"
	"a_jumpstart_ITEM2"
	"a_jumpstart_E_ITEM2"
	"a_jumpstart_NW_ITEM2"
	"a_jumpstart_N_ITEM2"
	"a_jumpstart_NE_ITEM2"
	fps 30
	"ACT_MP_JUMP_START_ITEM2" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "Jump_Float_ITEM2" {
	"a_jumpFloat_SW_ITEM2"
	"a_jumpFloat_S_ITEM2"
	"a_jumpFloat_SE_ITEM2"
	"a_jumpFloat_W_ITEM2"
	"a_jumpFloat_ITEM2"
	"a_jumpFloat_E_ITEM2"
	"a_jumpFloat_NW_ITEM2"
	"a_jumpFloat_N_ITEM2"
	"a_jumpFloat_NE_ITEM2"
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_idle"
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "Jump_Start_loser" {
	"a_jumpstart_SW_loser"
	"a_jumpstart_S_loser"
	"a_jumpstart_SE_loser"
	"a_jumpstart_W_loser"
	"a_jumpstart_loser"
	"a_jumpstart_E_loser"
	"a_jumpstart_NW_loser"
	"a_jumpstart_N_loser"
	"a_jumpstart_NE_loser"
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "Jump_Float_loser" {
	"a_jumpFloat_SW_loser"
	"a_jumpFloat_S_loser"
	"a_jumpFloat_SE_loser"
	"a_jumpFloat_W_loser"
	"a_jumpFloat_loser"
	"a_jumpFloat_E_loser"
	"a_jumpFloat_NW_loser"
	"a_jumpFloat_N_loser"
	"a_jumpFloat_NE_loser"
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "layer_primary_jump_floatNoise"
}

$sequence "jump_double_primary" {
	"a_jumpDouble_S_primary"
	"a_jumpDouble_S_primary"
	"a_jumpDouble_S_primary"
	"a_jumpDouble_W_primary"
	"a_jumpDouble_center_primary"
	"a_jumpDouble_E_primary"
	"a_jumpDouble_NW_primary"
	"a_jumpDouble_N_primary"
	"a_jumpDouble_NE_primary"
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_DOUBLEJUMP" 1
	// delta
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1.00000000372529 "doublejump_puff follow_attachment doublejumpfx" }
}

$sequence "jump_double_loser" {
	"a_jumpDouble_S_loser"
	"a_jumpDouble_S_loser"
	"a_jumpDouble_S_loser"
	"a_jumpDouble_W_loser"
	"a_jumpDouble_center_loser"
	"a_jumpDouble_E_loser"
	"a_jumpDouble_NW_loser"
	"a_jumpDouble_N_loser"
	"a_jumpDouble_NE_loser"
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_DOUBLEJUMP_LOSERSTATE" 1
	// delta
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1.00000000372529 "doublejump_puff follow_attachment doublejumpfx" }
}

$sequence "jumplandPose_primary" "scout_animations_anims\jumplandPose_primary.smd" {
	fps 30
	loop
}

$sequence "jumpland_primary" "scout_animations_anims\jumpland_primary.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_primary" 1
	// delta
}

$sequence "jumpland_secondary" "scout_animations_anims\jumpland_secondary.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "jumpland_melee" "scout_animations_anims\jumpland_melee.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "jumpland_ITEM1" "scout_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "jumpland_ITEM2" "scout_animations_anims\jumpland_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM2" 1
	// delta
}

$sequence "jumpland_loser" "scout_animations_anims\jumpland_loser.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "jumpland_MELEE_ALLCLASS" "scout_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_PRIMARY" "scout_animations_anims\airwalk_PRIMARY.smd" {
	fps 36
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_SECONDARY" "scout_animations_anims\airwalk_SECONDARY.smd" {
	fps 36
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "layer_swim_SECONDARY_wepGrip"
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_MELEE" "scout_animations_anims\airwalk_MELEE.smd" {
	fps 36
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "layer_swim_MELEE_wepGrip"
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_MELEE_ALLCLASS" "scout_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 36
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "layer_swim_MELEE_ALLCLASS_wepGrip"
	// addlayer "PRIMARY_aimmatrix_swim"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "scout_animations_anims\airwalk_LOSER.smd" {
	fps 36
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "scout_animations_anims\airwalk_ITEM1.smd" {
	fps 36
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "layer_swim_ITEM1_wepGrip"
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_ITEM2" "scout_animations_anims\airwalk_ITEM2.smd" {
	fps 36
	"ACT_MP_AIRWALK_ITEM2" 1
	loop
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "layer_dieviolent" "scout_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "scout_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "primary_death_headshot" "scout_animations_anims\primary_death_headshot.smd" {
	fps 30
}

$sequence "primary_death_backstab" "scout_animations_anims\primary_death_backstab.smd" {
	fps 30
}

$sequence "primary_death_burning" "scout_animations_anims\primary_death_burning.smd" {
	fps 30
}

$sequence "layer_PRIMARY_Stun_begin" "scout_animations_anims\layer_PRIMARY_Stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "scout_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_Stun_end" "scout_animations_anims\layer_PRIMARY_Stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_Stun_begin" "scout_animations_anims\PRIMARY_Stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_begin"
}

$sequence "PRIMARY_stun_middle" "scout_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "scout_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_end"
}

$sequence "selectionMenu_StartPose" "scout_animations_anims\selectionMenu_StartPose.smd" {
	fps 30
}

$sequence "selectionMenu_Anim01" "scout_animations_anims\selectionMenu_Anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 42.0000020861626 "Selection.ScoutShotgunTwirl" }
	{ event AE_CL_PLAYSOUND 59.0000021457672 "Selection.ScoutShotgunShoulder" }
}

$sequence "selectionMenu_Idle" "scout_animations_anims\selectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "selectionMenu_all" "scout_animations_anims\selectionMenu_all.smd" {
	fps 30
}

$sequence "armslayer_throw_fire" "scout_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "scout_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "taunt01" "scout_animations_anims\taunt01.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.944444 1 1 1 spline
	{ event AE_CL_PLAYSOUND 12.0000006258488 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 14.0000005066395 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 24.0000012516975 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 26.0000011324883 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 38.0000004172325 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 40.0000002980232 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 50.0000023841858 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 52.9999995231628 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 64.9999988079071 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 66.9999986886978 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 76.000000834465 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 78.0000007152557 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 88.9999973773956 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 13.0000005662441 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 26.0000011324883 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 42.0000001788139 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 54.9999994039536 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 68.0000013113022 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 78.9999979734421 "Taunt.Scout01HandSmack" }
}

$sequence "taunt01_Alt" "scout_animations_anims\taunt01_Alt.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.944444 1 1 1 spline
	{ event AE_CL_PLAYSOUND 12.0000006258488 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 14.0000005066395 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 24.0000012516975 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 26.0000011324883 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 38.0000004172325 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 40.0000002980232 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 50.0000023841858 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 52.9999995231628 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 64.9999988079071 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 66.9999986886978 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 76.000000834465 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 78.0000007152557 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 88.9999973773956 "Taunt.Scout01Run" }
	{ event AE_CL_PLAYSOUND 13.0000005662441 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 26.0000011324883 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 42.0000001788139 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 54.9999994039536 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 68.0000013113022 "Taunt.Scout01HandSmack" }
	{ event AE_CL_PLAYSOUND 78.9999979734421 "Taunt.Scout01HandSmack" }
}

$sequence "taunt02" "scout_animations_anims\taunt02.smd" {
	fps 30
	// addlayer "SECONDARY_aimmatrix_idle"
	blendlayer "SECONDARY_aimmatrix_idle" 0.876923 0.938462 1.007692 1.007692 spline
	{ event AE_CL_PLAYSOUND 22.0000006258488 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 29.0000002086163 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 39.0000015497208 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 48.000001013279 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 56.0000005364418 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 65 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 72.9999995231628 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 82.0000028610229 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 90.9999984502792 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 98.9999979734421 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 106.999997496605 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 116.999996900558 "Taunt.Scout02Run" }
	{ event AE_WPN_HIDE 10.000000372529 "" }
	{ event AE_WPN_UNHIDE 116.000000834465 "" }
}

$sequence "taunt03" "scout_animations_anims\taunt03.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.897436 1 1 1 spline
	{ event AE_CL_PLAYSOUND 28.0000000745058 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 35.0000014007092 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 55.0000002086163 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 61.0000033378601 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 94.0000013709068 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 107.000000596046 "Taunt.Scout03Run" }
}

$sequence "layer_taunt04" "scout_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "scout_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
	{ event AE_CL_PLAYSOUND 6.0000001937151 "Scout.DodgeCanDrinkFast" }
}

$sequence "taunt05" "scout_animations_anims\taunt05.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.944828 1 1 1 spline
	{ event AE_CL_PLAYSOUND 44.0000019967556 "Taunt.Demo02EquipmentJingle3" }
	{ event AE_CL_PLAYSOUND 86.0000029206276 "Taunt.Scout02Run" }
	{ event AE_CL_PLAYSOUND 113.000000119209 "Taunt.Scout03Run" }
	{ event AE_CL_PLAYSOUND 117.000002264977 "Weapon_Bat.Miss" }
	{ event AE_CL_PLAYSOUND 121.999996304512 "Taunt.Demo02EquipmentJingle3" }
}

$sequence "taunt06" "scout_animations_anims\taunt06.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 59.000001847744 "" }
}

$sequence "scout_taunt_replay" "scout_animations_anims\scout_taunt_replay.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "layer_taunt_come_and_get_me" "scout_animations_anims\layer_taunt_come_and_get_me.smd" {
	fps 24
	hidden
}

$sequence "taunt_come_and_get_me" "scout_animations_anims\taunt_come_and_get_me.smd" {
	fps 24
	// subtract "a_reference" 0
	// addlayer "layer_taunt_come_and_get_me"
}

$sequence "taunt_brutallegendinterior" "scout_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "scout_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "scout_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "scout_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "scout_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "scout_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_highFiveStart" "scout_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "taunt_highFiveStart_idle" "scout_animations_anims\taunt_highFiveStart_idle.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
}

$sequence "layer_taunt_highFiveSuccess" "scout_animations_anims\layer_taunt_highFiveSuccess.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccess" "scout_animations_anims\taunt_highFiveSuccess.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccess"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 125 "" }
}

$sequence "layer_taunt_highFiveSuccessFull" "scout_animations_anims\layer_taunt_highFiveSuccessFull.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccessFull" "scout_animations_anims\taunt_highFiveSuccessFull.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccessFull"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 125 "" }
}

$sequence "layer_taunt_laugh" "scout_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "scout_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 148 "" }
}

$sequence "taunt_conga" "scout_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "scout_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "scout_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
}

$sequence "layer_taunt_dosido_intro" "scout_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "scout_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
}

$sequence "taunt_flip_start" "scout_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "scout_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "scout_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000000745058 "" }
	{ event AE_WPN_UNHIDE 105.000000357628 "" }
}

$sequence "layer_taunt_flip_success_receiver" "scout_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "scout_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 0.999999992083758 "" }
	{ event AE_WPN_UNHIDE 127.999998986721 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 8.99999999254942 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 37.0000005364418 "taunt_flip_trail follow_attachment foot_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 56.9999996125698 "taunt_flip_land follow_attachment foot_R" }
}

$sequence "taunt_rps_start" "scout_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_paper_win" "scout_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "scout_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.999994039536 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 109.000000953674 "rps_scout_win follow_attachment doublejumpfx" }
}

$sequence "layer_taunt_rps_scissors_win" "scout_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "scout_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.999994039536 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 109.000000953674 "rps_scout_win follow_attachment doublejumpfx" }
}

$sequence "layer_taunt_rps_rock_win" "scout_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "scout_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.999994039536 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 109.000000953674 "rps_scout_win follow_attachment doublejumpfx" }
}

$sequence "layer_taunt_rps_rock_lose" "scout_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "scout_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.000004768372 "" }
}

$sequence "layer_taunt_rps_paper_lose" "scout_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "scout_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.000004768372 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "scout_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "scout_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 206.000004768372 "" }
}

$sequence "layer_taunt_headbutt_start" "scout_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "scout_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 197 "" }
}

$sequence "layer_taunt_headbutt_success" "scout_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "scout_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55.9999980032444 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 135 "" }
}

$sequence "layer_taunt_bat_man" "scout_animations_anims\layer_taunt_bat_man.smd" {
	fps 30
	hidden
}

$sequence "taunt_bat_man" "scout_animations_anims\taunt_bat_man.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_bat_man"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 13.0000001937151 "taunt_scout_bat_trail follow_attachment effect_hand_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 13.0000001937151 "taunt_scout_bat_trail follow_attachment effect_hand_L" }
}

$sequence "layer_taunt_chicken" "scout_animations_anims\layer_taunt_chicken.smd" {
	fps 24
	hidden
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 12 "" }
	{ event AE_WPN_HIDE 124 "" }
}

$sequence "taunt_chicken" "scout_animations_anims\taunt_chicken.smd" {
	fps 24
	// subtract "a_reference" 0
	// addlayer "layer_taunt_chicken"
}

$ikchain "rhand" "bip_hand_R" knee 0.861 0.509 0.003
$ikchain "lhand" "bip_hand_L" knee 0.818 -0.001 -0.575
$ikchain "rfoot" "bip_foot_R" knee 0.692 -0.722 0
$ikchain "lfoot" "bip_foot_L" knee 0.686 0 0.727

