// Created by Crowbar 0.19.0.0

$modelname "player/sniper_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_x" -1 1 0
$poseparameter "move_y" -1 1 0

$cdmaterials "models\player\sniper\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "sniper_animations_anims\a_reference.smd" {
	fps 30
}
$animation "b_reference" "sniper_animations_anims\b_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "sniper_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "sniper_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "sniper_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "sniper_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "sniper_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "sniper_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "sniper_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "sniper_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "sniper_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "sniper_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "sniper_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "sniper_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "sniper_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "sniper_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "sniper_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "sniper_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "sniper_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "sniper_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_neutral" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_deployed_down_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_down_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_down_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_straight_up" "sniper_animations_anims\a_PRIMARY_aimmatrix_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_neutral" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_down_right" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_down_center" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_down_left" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_mid_right" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_mid_center" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_mid_left" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_up_right" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_up_center" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_up_left" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_crouch_aimmatrix_deployed_straight_up" "sniper_animations_anims\a_PRIMARY_crouch_aimmatrix_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "sniper_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "sniper_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "sniper_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "sniper_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "sniper_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "sniper_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "sniper_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "sniper_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "sniper_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "sniper_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "sniper_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "sniper_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "sniper_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "sniper_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "sniper_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "sniper_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "sniper_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "sniper_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "sniper_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "sniper_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "sniper_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "sniper_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "sniper_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "sniper_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_Swing" "sniper_animations_anims\a_Melee_Swing.smd" {
	fps 30
}
$animation "a_Melee_Crouch_Swing" "sniper_animations_anims\a_Melee_Crouch_Swing.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_allclass_Swing" "sniper_animations_anims\a_Melee_allclass_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Crouch_Swing" "sniper_animations_anims\a_Melee_allclass_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Item1_aimmatrix_idle_neutral" "sniper_animations_anims\a_Item1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_Item1_aimmatrix_idle_down_right" "sniper_animations_anims\a_Item1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_down_center" "sniper_animations_anims\a_Item1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_down_left" "sniper_animations_anims\a_Item1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_mid_right" "sniper_animations_anims\a_Item1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_mid_center" "sniper_animations_anims\a_Item1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_mid_left" "sniper_animations_anims\a_Item1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_up_right" "sniper_animations_anims\a_Item1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_up_center" "sniper_animations_anims\a_Item1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_up_left" "sniper_animations_anims\a_Item1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_idle_straight_up" "sniper_animations_anims\a_Item1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_neutral" "sniper_animations_anims\a_Item1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_Item1_aimmatrix_run_down_right" "sniper_animations_anims\a_Item1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_down_center" "sniper_animations_anims\a_Item1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_down_left" "sniper_animations_anims\a_Item1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_mid_right" "sniper_animations_anims\a_Item1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_mid_center" "sniper_animations_anims\a_Item1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_mid_left" "sniper_animations_anims\a_Item1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_up_right" "sniper_animations_anims\a_Item1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_up_center" "sniper_animations_anims\a_Item1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_up_left" "sniper_animations_anims\a_Item1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_run_straight_up" "sniper_animations_anims\a_Item1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_Item1_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Item1_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_Item1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_fire" "sniper_animations_anims\a_ITEM1_fire.smd" {
	fps 30
}
$animation "a_ITEM1_Crouch_fire" "sniper_animations_anims\a_ITEM1_Crouch_fire.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_idle_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_idle_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_run_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_deployed_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_deployed_walk_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_deployed_walk_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_deployed_walk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_neutral" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_down_right" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_down_center" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_down_left" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_mid_right" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_mid_center" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_mid_left" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_up_right" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_up_center" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_up_left" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_crouch_aimmatrix_deployed_straight_up" "sniper_animations_anims\a_ITEM2_crouch_aimmatrix_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_stun_startpose" "sniper_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "sniper_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "sniper_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "sniper_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "sniper_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "sniper_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "sniper_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "sniper_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "sniper_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "sniper_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "sniper_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "sniper_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "sniper_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "sniper_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "sniper_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "sniper_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "sniper_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "sniper_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "sniper_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "sniper_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "sniper_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "sniper_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "sniper_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "sniper_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "sniper_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "sniper_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "sniper_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "sniper_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "sniper_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "sniper_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "sniper_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "sniper_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "sniper_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "sniper_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "sniper_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "sniper_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "sniper_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "sniper_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "sniper_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "sniper_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "sniper_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "sniper_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "sniper_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "sniper_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "sniper_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "sniper_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "sniper_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "sniper_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "sniper_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "sniper_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "sniper_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "sniper_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "sniper_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "sniper_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "sniper_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "sniper_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "sniper_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "sniper_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "sniper_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "sniper_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "sniper_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "sniper_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_ITEM2_aimmatrix_swim_neutral" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_swim_down_right" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_center" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_left" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_right" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_center" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_left" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_right" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_center" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_left" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_straight_up" "sniper_animations_anims\a_ITEM2_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM2" "sniper_animations_anims\a_swimCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM2" "sniper_animations_anims\a_swimS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM2" "sniper_animations_anims\a_swimSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM2" "sniper_animations_anims\a_swimE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM2" "sniper_animations_anims\a_swimNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM2" "sniper_animations_anims\a_swimN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM2" "sniper_animations_anims\a_swimNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM2" "sniper_animations_anims\a_swimW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM2" "sniper_animations_anims\a_swimSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_neutral" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_down_right" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_down_center" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_down_left" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_right" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_center" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_left" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_up_right" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_up_center" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_up_left" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_DEPLOYED_aimmatrix_swim_straight_up" "sniper_animations_anims\a_PRIMARY_DEPLOYED_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimCenter_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimS_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimSE_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimE_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimNE_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimN_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimNW_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimW_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY_DEPLOYED" "sniper_animations_anims\a_swimSW_PRIMARY_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "sniper_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "sniper_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "sniper_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "sniper_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "sniper_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "sniper_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "sniper_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "sniper_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "sniper_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_deployedCenter_PRIMARY" "sniper_animations_anims\a_deployedCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedS_PRIMARY" "sniper_animations_anims\a_deployedS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSE_PRIMARY" "sniper_animations_anims\a_deployedSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedE_PRIMARY" "sniper_animations_anims\a_deployedE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNE_PRIMARY" "sniper_animations_anims\a_deployedNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedN_PRIMARY" "sniper_animations_anims\a_deployedN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNW_PRIMARY" "sniper_animations_anims\a_deployedNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedW_PRIMARY" "sniper_animations_anims\a_deployedW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSW_PRIMARY" "sniper_animations_anims\a_deployedSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_blend_crouchN_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkCenter_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkS_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkSE_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkE_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkNE_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkN_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkNW_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkW_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_deployed_crouch_walk_PRIMARY" "sniper_animations_anims\a_crouch_walkSW_deployed_crouch_walk_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "sniper_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "sniper_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "sniper_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "sniper_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "sniper_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "sniper_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "sniper_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "sniper_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "sniper_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "sniper_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "sniper_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "sniper_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "sniper_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "sniper_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "sniper_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "sniper_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "sniper_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "sniper_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "sniper_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "sniper_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "sniper_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "sniper_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "sniper_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "sniper_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "sniper_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "sniper_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "sniper_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY" "sniper_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "sniper_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "sniper_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "sniper_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "sniper_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "sniper_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "sniper_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "sniper_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "sniper_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "sniper_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "sniper_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "sniper_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "sniper_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "sniper_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "sniper_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "sniper_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "sniper_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "sniper_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "sniper_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "sniper_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "sniper_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "sniper_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "sniper_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "sniper_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "sniper_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "sniper_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "sniper_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "sniper_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "sniper_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "sniper_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "sniper_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "sniper_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "sniper_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "sniper_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "sniper_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "sniper_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "sniper_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "sniper_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "sniper_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM2" "sniper_animations_anims\a_runCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM2" "sniper_animations_anims\a_runS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM2" "sniper_animations_anims\a_runSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM2" "sniper_animations_anims\a_runE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM2" "sniper_animations_anims\a_runNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM2" "sniper_animations_anims\a_runN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM2" "sniper_animations_anims\a_runNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM2" "sniper_animations_anims\a_runW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM2" "sniper_animations_anims\a_runSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM2" "sniper_animations_anims\a_blend_crouchN_crouch_walk_ITEM2.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkS_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkN_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM2" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedCenter_ITEM2" "sniper_animations_anims\a_deployedCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedS_ITEM2" "sniper_animations_anims\a_deployedS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedSE_ITEM2" "sniper_animations_anims\a_deployedSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedE_ITEM2" "sniper_animations_anims\a_deployedE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedNE_ITEM2" "sniper_animations_anims\a_deployedNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedN_ITEM2" "sniper_animations_anims\a_deployedN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedNW_ITEM2" "sniper_animations_anims\a_deployedNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedW_ITEM2" "sniper_animations_anims\a_deployedW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_deployedSW_ITEM2" "sniper_animations_anims\a_deployedSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_blend_crouchN_crouch_walk_ITEM2_deployed.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkS_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkSE_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkE_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkNE_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkN_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkNW_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkW_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM2_deployed" "sniper_animations_anims\a_crouch_walkSW_crouch_walk_ITEM2_deployed.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_airwalk_neutral" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_right" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_center" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_left" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_straight_up" "sniper_animations_anims\a_SECONDARY_aimmatrix_airwalk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_throw_fire" "sniper_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "sniper_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_deployed" {
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_up_right"
	"a_PRIMARY_aimmatrix_deployed_up_center"
	"a_PRIMARY_aimmatrix_deployed_up_left"
	"a_PRIMARY_aimmatrix_deployed_mid_right"
	"a_PRIMARY_aimmatrix_deployed_mid_center"
	"a_PRIMARY_aimmatrix_deployed_mid_left"
	"a_PRIMARY_aimmatrix_deployed_down_right"
	"a_PRIMARY_aimmatrix_deployed_down_center"
	"a_PRIMARY_aimmatrix_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_crouch_aimmatrix_deployed" {
	"a_PRIMARY_crouch_aimmatrix_deployed_straight_up"
	"a_PRIMARY_crouch_aimmatrix_deployed_straight_up"
	"a_PRIMARY_crouch_aimmatrix_deployed_straight_up"
	"a_PRIMARY_crouch_aimmatrix_deployed_up_right"
	"a_PRIMARY_crouch_aimmatrix_deployed_up_center"
	"a_PRIMARY_crouch_aimmatrix_deployed_up_left"
	"a_PRIMARY_crouch_aimmatrix_deployed_mid_right"
	"a_PRIMARY_crouch_aimmatrix_deployed_mid_center"
	"a_PRIMARY_crouch_aimmatrix_deployed_mid_left"
	"a_PRIMARY_crouch_aimmatrix_deployed_down_right"
	"a_PRIMARY_crouch_aimmatrix_deployed_down_center"
	"a_PRIMARY_crouch_aimmatrix_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_PRIMARY" "sniper_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY" "sniper_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "sniper_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY_DEPLOYED" "sniper_animations_anims\AttackCrouch_PRIMARY_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "AttackSwim_PRIMARY_DEPLOYED" "sniper_animations_anims\AttackSwim_PRIMARY_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "ReloadStand_PRIMARY_DEPLOYED" "sniper_animations_anims\ReloadStand_PRIMARY_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "ReloadCrouch_PRIMARY_DEPLOYED" "sniper_animations_anims\ReloadCrouch_PRIMARY_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "ReloadSwim_PRIMARY_DEPLOYED" "sniper_animations_anims\ReloadSwim_PRIMARY_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "ReloadStand_PRIMARY" "sniper_animations_anims\ReloadStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
}

$sequence "ReloadCrouch_PRIMARY" "sniper_animations_anims\ReloadCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
}

$sequence "ReloadSwim_PRIMARY" "sniper_animations_anims\ReloadSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
}

$sequence "attackstand_Primary_deployed_fire" "sniper_animations_anims\attackstand_Primary_deployed_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED" 1
	// delta
}

$sequence "a_flinch01" "sniper_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "layer_placeSapper_ArmL" "sniper_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "sniper_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "sniper_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "sniper_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "sniper_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "layer_reload_standing_arms_SECONDARY" "sniper_animations_anims\layer_reload_standing_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY" "sniper_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "ReloadAirwalk_SECONDARY" "sniper_animations_anims\ReloadAirwalk_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "ReloadCrouch_SECONDARY" "sniper_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "ReloadSwim_SECONDARY" "sniper_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_melee_swing" "sniper_animations_anims\armslayer_melee_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swing" "sniper_animations_anims\bodylayer_Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swing" "sniper_animations_anims\Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// addlayer "bodylayer_Melee_Swing"
	// addlayer "armslayer_melee_swing"
}

$sequence "armslayer_melee_Crouch_swing" "sniper_animations_anims\armslayer_melee_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Crouch_Swing" "sniper_animations_anims\bodylayer_Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Crouch_Swing" "sniper_animations_anims\Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// addlayer "bodylayer_Melee_Crouch_Swing"
	// addlayer "armslayer_melee_Crouch_swing"
}

$sequence "AttackSwim_MELEE" "sniper_animations_anims\AttackSwim_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
}

$sequence "layer_melee_swing_swimS" "sniper_animations_anims\layer_melee_swing_swimS.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
}

$sequence "MELEE_swim_swing" "sniper_animations_anims\MELEE_swim_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	blendlayer "AttackSwim_MELEE" 0 0.5 1 2 spline poseparameter move_x
	blendlayer "layer_melee_swing_swimS" -2 -1 0 0.5 spline poseparameter move_x
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_melee_allclass_swing" "sniper_animations_anims\armslayer_melee_allclass_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Swing" "sniper_animations_anims\bodylayer_Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Swing" "sniper_animations_anims\Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	blendlayer "bodylayer_Melee_allclass_Swing" 0 0.041667 0.833333 1 spline
	blendlayer "armslayer_melee_allclass_swing" 0 0.208333 0.833333 1 spline
}

$sequence "armslayer_melee_allclass_Crouch_swing" "sniper_animations_anims\armslayer_melee_allclass_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Crouch_Swing" "sniper_animations_anims\bodylayer_Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Crouch_Swing" "sniper_animations_anims\Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_Melee_allclass_Crouch_Swing"
	// addlayer "armslayer_melee_allclass_Crouch_swing"
}

$sequence "AttackSwim_MELEE_ALLCLASS" "sniper_animations_anims\AttackSwim_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
}

$sequence "layer_MELEE_ALLCLASS_swing_swimS" "sniper_animations_anims\layer_MELEE_ALLCLASS_swing_swimS.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
}

$sequence "MELEE_ALLCLASS_swim_swing" "sniper_animations_anims\MELEE_ALLCLASS_swim_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	blendlayer "AttackSwim_MELEE_ALLCLASS" 0 0.5 1 2 spline poseparameter move_x
	blendlayer "layer_MELEE_ALLCLASS_swing_swimS" -2 -1 0 0.5 spline poseparameter move_x
	// addlayer "r_handposes"
}

$sequence "Item1_aimmatrix_idle" {
	"a_Item1_aimmatrix_idle_straight_up"
	"a_Item1_aimmatrix_idle_straight_up"
	"a_Item1_aimmatrix_idle_straight_up"
	"a_Item1_aimmatrix_idle_up_right"
	"a_Item1_aimmatrix_idle_up_center"
	"a_Item1_aimmatrix_idle_up_left"
	"a_Item1_aimmatrix_idle_mid_right"
	"a_Item1_aimmatrix_idle_mid_center"
	"a_Item1_aimmatrix_idle_mid_left"
	"a_Item1_aimmatrix_idle_down_right"
	"a_Item1_aimmatrix_idle_down_center"
	"a_Item1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "Item1_aimmatrix_run" {
	"a_Item1_aimmatrix_run_straight_up"
	"a_Item1_aimmatrix_run_straight_up"
	"a_Item1_aimmatrix_run_straight_up"
	"a_Item1_aimmatrix_run_up_right"
	"a_Item1_aimmatrix_run_up_center"
	"a_Item1_aimmatrix_run_up_left"
	"a_Item1_aimmatrix_run_mid_right"
	"a_Item1_aimmatrix_run_mid_center"
	"a_Item1_aimmatrix_run_mid_left"
	"a_Item1_aimmatrix_run_down_right"
	"a_Item1_aimmatrix_run_down_center"
	"a_Item1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "Item1_aimmatrix_crouch_idle" {
	"a_Item1_aimmatrix_crouch_idle_straight_up"
	"a_Item1_aimmatrix_crouch_idle_straight_up"
	"a_Item1_aimmatrix_crouch_idle_straight_up"
	"a_Item1_aimmatrix_crouch_idle_up_right"
	"a_Item1_aimmatrix_crouch_idle_up_center"
	"a_Item1_aimmatrix_crouch_idle_up_left"
	"a_Item1_aimmatrix_crouch_idle_mid_right"
	"a_Item1_aimmatrix_crouch_idle_mid_center"
	"a_Item1_aimmatrix_crouch_idle_mid_left"
	"a_Item1_aimmatrix_crouch_idle_down_right"
	"a_Item1_aimmatrix_crouch_idle_down_center"
	"a_Item1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_ITEM1_fire" "sniper_animations_anims\armslayer_ITEM1_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_fire" "sniper_animations_anims\bodylayer_ITEM1_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_fire" "sniper_animations_anims\ITEM1_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// addlayer "bodylayer_ITEM1_fire"
	// addlayer "armslayer_ITEM1_fire"
}

$sequence "armslayer_ITEM1_Crouch_fire" "sniper_animations_anims\armslayer_ITEM1_Crouch_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_Crouch_fire" "sniper_animations_anims\bodylayer_ITEM1_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM1_Crouch_fire" "sniper_animations_anims\ITEM1_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM1" 1
	// addlayer "bodylayer_ITEM1_Crouch_fire"
	// addlayer "armslayer_ITEM1_Crouch_fire"
}

$sequence "layer_ITEM1_WepGrip" "sniper_animations_anims\layer_ITEM1_WepGrip.smd" {
	fps 30
	loop
	hidden
}

$sequence "ITEM2_aimmatrix_idle" {
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_up_right"
	"a_ITEM2_aimmatrix_idle_up_center"
	"a_ITEM2_aimmatrix_idle_up_left"
	"a_ITEM2_aimmatrix_idle_mid_right"
	"a_ITEM2_aimmatrix_idle_mid_center"
	"a_ITEM2_aimmatrix_idle_mid_left"
	"a_ITEM2_aimmatrix_idle_down_right"
	"a_ITEM2_aimmatrix_idle_down_center"
	"a_ITEM2_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_run" {
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_up_right"
	"a_ITEM2_aimmatrix_run_up_center"
	"a_ITEM2_aimmatrix_run_up_left"
	"a_ITEM2_aimmatrix_run_mid_right"
	"a_ITEM2_aimmatrix_run_mid_center"
	"a_ITEM2_aimmatrix_run_mid_left"
	"a_ITEM2_aimmatrix_run_down_right"
	"a_ITEM2_aimmatrix_run_down_center"
	"a_ITEM2_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_crouch_idle" {
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_up_right"
	"a_ITEM2_aimmatrix_crouch_idle_up_center"
	"a_ITEM2_aimmatrix_crouch_idle_up_left"
	"a_ITEM2_aimmatrix_crouch_idle_mid_right"
	"a_ITEM2_aimmatrix_crouch_idle_mid_center"
	"a_ITEM2_aimmatrix_crouch_idle_mid_left"
	"a_ITEM2_aimmatrix_crouch_idle_down_right"
	"a_ITEM2_aimmatrix_crouch_idle_down_center"
	"a_ITEM2_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_deployed" {
	"a_ITEM2_aimmatrix_deployed_straight_up"
	"a_ITEM2_aimmatrix_deployed_straight_up"
	"a_ITEM2_aimmatrix_deployed_straight_up"
	"a_ITEM2_aimmatrix_deployed_up_right"
	"a_ITEM2_aimmatrix_deployed_up_center"
	"a_ITEM2_aimmatrix_deployed_up_left"
	"a_ITEM2_aimmatrix_deployed_mid_right"
	"a_ITEM2_aimmatrix_deployed_mid_center"
	"a_ITEM2_aimmatrix_deployed_mid_left"
	"a_ITEM2_aimmatrix_deployed_down_right"
	"a_ITEM2_aimmatrix_deployed_down_center"
	"a_ITEM2_aimmatrix_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_deployed_walk" {
	"a_ITEM2_aimmatrix_deployed_walk_straight_up"
	"a_ITEM2_aimmatrix_deployed_walk_straight_up"
	"a_ITEM2_aimmatrix_deployed_walk_straight_up"
	"a_ITEM2_aimmatrix_deployed_walk_up_right"
	"a_ITEM2_aimmatrix_deployed_walk_up_center"
	"a_ITEM2_aimmatrix_deployed_walk_up_left"
	"a_ITEM2_aimmatrix_deployed_walk_mid_right"
	"a_ITEM2_aimmatrix_deployed_walk_mid_center"
	"a_ITEM2_aimmatrix_deployed_walk_mid_left"
	"a_ITEM2_aimmatrix_deployed_walk_down_right"
	"a_ITEM2_aimmatrix_deployed_walk_down_center"
	"a_ITEM2_aimmatrix_deployed_walk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_crouch_aimmatrix_deployed" {
	"a_ITEM2_crouch_aimmatrix_deployed_straight_up"
	"a_ITEM2_crouch_aimmatrix_deployed_straight_up"
	"a_ITEM2_crouch_aimmatrix_deployed_straight_up"
	"a_ITEM2_crouch_aimmatrix_deployed_up_right"
	"a_ITEM2_crouch_aimmatrix_deployed_up_center"
	"a_ITEM2_crouch_aimmatrix_deployed_up_left"
	"a_ITEM2_crouch_aimmatrix_deployed_mid_right"
	"a_ITEM2_crouch_aimmatrix_deployed_mid_center"
	"a_ITEM2_crouch_aimmatrix_deployed_mid_left"
	"a_ITEM2_crouch_aimmatrix_deployed_down_right"
	"a_ITEM2_crouch_aimmatrix_deployed_down_center"
	"a_ITEM2_crouch_aimmatrix_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_fire" "sniper_animations_anims\ITEM2_fire.smd" {
	fps 30
	"ACT_MP_ATTACK_STAND_ITEM2" 1
	// addlayer "ITEM2_aimmatrix_deployed_walk"
}

$sequence "ITEM2_reload" "sniper_animations_anims\ITEM2_reload.smd" {
	fps 30
	"ACT_MP_RELOAD_STAND_ITEM2" 1
	// addlayer "ITEM2_aimmatrix_deployed_walk"
}

$sequence "ITEM2_crouch_fire" "sniper_animations_anims\ITEM2_crouch_fire.smd" {
	fps 30
	"ACT_MP_ATTACK_CROUCH_ITEM2" 1
	// addlayer "ITEM2_crouch_aimmatrix_deployed"
}

$sequence "ITEM2_crouch_reload" "sniper_animations_anims\ITEM2_crouch_reload.smd" {
	fps 30
	"ACT_MP_RELOAD_CROUCH_ITEM2" 1
	// addlayer "ITEM2_crouch_aimmatrix_deployed"
}

$sequence "layer_gesture_primary_go_armL" "sniper_animations_anims\layer_gesture_primary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_go" "sniper_animations_anims\gesture_primary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_go_armL"
}

$sequence "layer_gesture_primary_cheer_armL" "sniper_animations_anims\layer_gesture_primary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_cheer" "sniper_animations_anims\gesture_primary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_cheer_armL"
}

$sequence "layer_gesture_primary_help_armL" "sniper_animations_anims\layer_gesture_primary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_help" "sniper_animations_anims\gesture_primary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_help_armL"
}

$sequence "layer_gesture_primary_positive_armL" "sniper_animations_anims\layer_gesture_primary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_positive" "sniper_animations_anims\gesture_primary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_positive_armL"
}

$sequence "layer_gesture_secondary_go_armL" "sniper_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "sniper_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_go_armL"
}

$sequence "layer_gesture_secondary_cheer_armL" "sniper_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "sniper_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_help_armL" "sniper_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "sniper_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_secondary_positive_armL" "sniper_animations_anims\layer_gesture_secondary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_positive" "sniper_animations_anims\gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_positive_armL"
}

$sequence "layer_gesture_melee_go_armL" "sniper_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "sniper_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_go_armL"
}

$sequence "layer_gesture_melee_cheer_armL" "sniper_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "sniper_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_cheer_armL"
}

$sequence "layer_gesture_primary_help_runN_armL" "sniper_animations_anims\layer_gesture_primary_help_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_melee_help_armL" "sniper_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "sniper_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_help_armL"
	blendlayer "layer_gesture_melee_help_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_primary_help_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_melee_positive_armL" "sniper_animations_anims\layer_gesture_melee_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_positive" "sniper_animations_anims\gesture_melee_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_positive_armL"
}

$sequence "primary_death_backstab" "sniper_animations_anims\primary_death_backstab.smd" {
	fps 30
}

$sequence "primary_death_headshot" "sniper_animations_anims\primary_death_headshot.smd" {
	fps 30
}

$sequence "primary_death_burning" "sniper_animations_anims\primary_death_burning.smd" {
	fps 30
}

$sequence "layer_dieviolent" "sniper_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "sniper_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "layer_PRIMARY_Stun_begin" "sniper_animations_anims\layer_PRIMARY_Stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "sniper_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_Stun_end" "sniper_animations_anims\layer_PRIMARY_Stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_Stun_begin" "sniper_animations_anims\PRIMARY_Stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_begin"
}

$sequence "PRIMARY_stun_middle" "sniper_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "sniper_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_end"
}

$sequence "SelectionMenu_StartPose" "sniper_animations_anims\SelectionMenu_StartPose.smd" {
	fps 30
}

$sequence "SelectionMenu_Anim01" "sniper_animations_anims\SelectionMenu_Anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 29.0000009536743 "Selection.SniperHatTip" }
}

$sequence "SelectionMenu_Idle" "sniper_animations_anims\SelectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "stand_PRIMARY" "sniper_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "sniper_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "sniper_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "sniper_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "sniper_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "sniper_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "Item1_aimmatrix_idle"
}

$sequence "stand_ITEM2" "sniper_animations_anims\stand_ITEM2.smd" {
	fps 30
	"ACT_MP_STAND_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "sniper_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "sniper_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "sniper_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "sniper_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "sniper_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "sniper_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "Item1_aimmatrix_crouch_idle"
}

$sequence "crouch_ITEM2" "sniper_animations_anims\crouch_ITEM2.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_crouch_idle"
}

$sequence "crouch_ITEM2_DEPLOYED" "sniper_animations_anims\crouch_ITEM2_DEPLOYED.smd" {
	fps 30
	"ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM2" 1
	loop
	// addlayer "ITEM2_crouch_aimmatrix_deployed"
}

$sequence "a_jumpstart_PRIMARY" "sniper_animations_anims\a_jumpstart_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
}

$sequence "a_jumpfloat_PRIMARY" "sniper_animations_anims\a_jumpfloat_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
}

$sequence "jumplandPose_PRIMARY" "sniper_animations_anims\jumplandPose_PRIMARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_PRIMARY" "sniper_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "a_jumpstart_SECONDARY" "sniper_animations_anims\a_jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "a_jumpfloat_SECONDARY" "sniper_animations_anims\a_jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumplandPose_SECONDARY" "sniper_animations_anims\jumplandPose_SECONDARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_SECONDARY" "sniper_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "sniper_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "sniper_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "sniper_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "sniper_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "sniper_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "sniper_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "sniper_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "sniper_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "sniper_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "sniper_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "sniper_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "sniper_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "a_jumpstart_ITEM1" "sniper_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "a_jumpfloat_ITEM1" "sniper_animations_anims\a_jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumplandPose_ITEM1" "sniper_animations_anims\jumplandPose_ITEM1.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM1" "sniper_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "a_jumpstart_ITEM2" "sniper_animations_anims\a_jumpstart_ITEM2.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM2" 1
}

$sequence "a_jumpfloat_ITEM2" "sniper_animations_anims\a_jumpfloat_ITEM2.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM2" 1
	loop
}

$sequence "jumplandPose_ITEM2" "sniper_animations_anims\jumplandPose_ITEM2.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM2" "sniper_animations_anims\jumpland_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM2" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "ITEM2_aimmatrix_swim" {
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_up_right"
	"a_ITEM2_aimmatrix_swim_up_center"
	"a_ITEM2_aimmatrix_swim_up_left"
	"a_ITEM2_aimmatrix_swim_mid_right"
	"a_ITEM2_aimmatrix_swim_mid_center"
	"a_ITEM2_aimmatrix_swim_mid_left"
	"a_ITEM2_aimmatrix_swim_down_right"
	"a_ITEM2_aimmatrix_swim_down_center"
	"a_ITEM2_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM2" {
	"a_swimCenter_ITEM2"
	fps 30
	loop
}

$sequence "swim_ITEM2" {
	"a_swimSW_ITEM2"
	"a_swimS_ITEM2"
	"a_swimSE_ITEM2"
	"a_swimW_ITEM2"
	"a_swimCenter_ITEM2"
	"a_swimE_ITEM2"
	"a_swimNW_ITEM2"
	"a_swimN_ITEM2"
	"a_swimNE_ITEM2"
	fps 30
	"ACT_MP_SWIM_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_swim"
}

$sequence "PRIMARY_DEPLOYED_aimmatrix_swim" {
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_straight_up"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_straight_up"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_straight_up"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_up_right"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_up_center"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_up_left"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_right"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_center"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_mid_left"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_down_right"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_down_center"
	"a_PRIMARY_DEPLOYED_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY_DEPLOYED" {
	"a_swimCenter_PRIMARY_DEPLOYED"
	fps 30
	loop
}

$sequence "swim_PRIMARY_DEPLOYED" {
	"a_swimSW_PRIMARY_DEPLOYED"
	"a_swimS_PRIMARY_DEPLOYED"
	"a_swimSE_PRIMARY_DEPLOYED"
	"a_swimW_PRIMARY_DEPLOYED"
	"a_swimCenter_PRIMARY_DEPLOYED"
	"a_swimE_PRIMARY_DEPLOYED"
	"a_swimNW_PRIMARY_DEPLOYED"
	"a_swimN_PRIMARY_DEPLOYED"
	"a_swimNE_PRIMARY_DEPLOYED"
	fps 30
	"ACT_MP_SWIM_DEPLOYED_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_DEPLOYED_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "crouch_deployed_PRIMARY" "sniper_animations_anims\crouch_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_crouch_aimmatrix_deployed"
}

$sequence "stand_deployed_PRIMARY" "sniper_animations_anims\stand_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_aimmatrix_deployed"
}

$sequence "PRIMARY_deployed_movement" {
	"a_deployedSW_PRIMARY"
	"a_deployedS_PRIMARY"
	"a_deployedSE_PRIMARY"
	"a_deployedW_PRIMARY"
	"a_deployedCenter_PRIMARY"
	"a_deployedE_PRIMARY"
	"a_deployedNW_PRIMARY"
	"a_deployedN_PRIMARY"
	"a_deployedNE_PRIMARY"
	fps 30
	"ACT_MP_DEPLOYED_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_deployed"
}

$sequence "deployed_crouch_walk_PRIMARY" {
	"a_crouch_walkSW_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkS_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkSE_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkW_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkCenter_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkE_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkNW_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkN_deployed_crouch_walk_PRIMARY"
	"a_crouch_walkNE_deployed_crouch_walk_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_DEPLOYED" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_crouch_aimmatrix_deployed"
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_crouch_walk_SECONDARY"
	"a_crouch_walkS_crouch_walk_SECONDARY"
	"a_crouch_walkSE_crouch_walk_SECONDARY"
	"a_crouch_walkW_crouch_walk_SECONDARY"
	"a_crouch_walkCenter_crouch_walk_SECONDARY"
	"a_crouch_walkE_crouch_walk_SECONDARY"
	"a_crouch_walkNW_crouch_walk_SECONDARY"
	"a_crouch_walkN_crouch_walk_SECONDARY"
	"a_crouch_walkNE_crouch_walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 1.00000000745058 "left" }
	{ event 7001 10.0000004768372 "right" }
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "Item1_aimmatrix_run"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "Item1_aimmatrix_crouch_idle"
}

$sequence "run_ITEM2" {
	"a_runSW_ITEM2"
	"a_runS_ITEM2"
	"a_runSE_ITEM2"
	"a_runW_ITEM2"
	"a_runCenter_ITEM2"
	"a_runE_ITEM2"
	"a_runNW_ITEM2"
	"a_runN_ITEM2"
	"a_runNE_ITEM2"
	fps 30
	"ACT_MP_RUN_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_run"
	{ event 7001 6.00000017881393 "right" }
	{ event 7001 14.9999996423721 "left" }
}

$sequence "crouch_walk_ITEM2" {
	"a_crouch_walkSW_crouch_walk_ITEM2"
	"a_crouch_walkS_crouch_walk_ITEM2"
	"a_crouch_walkSE_crouch_walk_ITEM2"
	"a_crouch_walkW_crouch_walk_ITEM2"
	"a_crouch_walkCenter_crouch_walk_ITEM2"
	"a_crouch_walkE_crouch_walk_ITEM2"
	"a_crouch_walkNW_crouch_walk_ITEM2"
	"a_crouch_walkN_crouch_walk_ITEM2"
	"a_crouch_walkNE_crouch_walk_ITEM2"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_crouch_idle"
}

$sequence "crouch_deployed_ITEM2" "sniper_animations_anims\crouch_deployed_ITEM2.smd" {
	fps 30
	"ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM2" 1
	loop
	// addlayer "ITEM2_crouch_aimmatrix_deployed"
}

$sequence "stand_deployed_ITEM2" "sniper_animations_anims\stand_deployed_ITEM2.smd" {
	fps 30
	"ACT_MP_DEPLOYED_IDLE_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_deployed"
}

$sequence "ITEM2_deployed_movement" {
	"a_deployedSW_ITEM2"
	"a_deployedS_ITEM2"
	"a_deployedSE_ITEM2"
	"a_deployedW_ITEM2"
	"a_deployedCenter_ITEM2"
	"a_deployedE_ITEM2"
	"a_deployedNW_ITEM2"
	"a_deployedN_ITEM2"
	"a_deployedNE_ITEM2"
	fps 30
	"ACT_MP_DEPLOYED_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_deployed_walk"
}

$sequence "crouch_walk_ITEM2_deployed" {
	"a_crouch_walkSW_crouch_walk_ITEM2_deployed"
	"a_crouch_walkS_crouch_walk_ITEM2_deployed"
	"a_crouch_walkSE_crouch_walk_ITEM2_deployed"
	"a_crouch_walkW_crouch_walk_ITEM2_deployed"
	"a_crouch_walkCenter_crouch_walk_ITEM2_deployed"
	"a_crouch_walkE_crouch_walk_ITEM2_deployed"
	"a_crouch_walkNW_crouch_walk_ITEM2_deployed"
	"a_crouch_walkN_crouch_walk_ITEM2_deployed"
	"a_crouch_walkNE_crouch_walk_ITEM2_deployed"
	fps 30
	"ACT_MP_CROUCHWALK_DEPLOYED_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_crouch_aimmatrix_deployed"
}

$sequence "airwalk_PRIMARY" "sniper_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "SECONDARY_aimmatrix_airwalk" {
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_up_right"
	"a_SECONDARY_aimmatrix_airwalk_up_center"
	"a_SECONDARY_aimmatrix_airwalk_up_left"
	"a_SECONDARY_aimmatrix_airwalk_mid_right"
	"a_SECONDARY_aimmatrix_airwalk_mid_center"
	"a_SECONDARY_aimmatrix_airwalk_mid_left"
	"a_SECONDARY_aimmatrix_airwalk_down_right"
	"a_SECONDARY_aimmatrix_airwalk_down_center"
	"a_SECONDARY_aimmatrix_airwalk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "airwalk_SECONDARY" "sniper_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_airwalk"
}

$sequence "airwalk_MELEE" "sniper_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "airwalk_MELEE_ALLCLASS" "sniper_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "sniper_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "sniper_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "Item1_aimmatrix_idle"
}

$sequence "airwalk_ITEM2" "sniper_animations_anims\airwalk_ITEM2.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "armslayer_throw_fire" "sniper_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "sniper_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "sniper_animations_anims\layer_taunt01.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "sniper_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt01"
}

$sequence "taunt02" "sniper_animations_anims\taunt02.smd" {
	fps 30
	// addlayer "SECONDARY_aimmatrix_idle"
	// addlayer "SECONDARY_aimmatrix_idle"
	{ event 5004 20.9999995529652 "Taunt.Sniper02HealClick" }
	{ event 5004 27.0000008046627 "Taunt.Sniper02FootStomp" }
	{ event 5004 29.9999990165234 "Taunt.Sniper02FootStomp" }
}

$sequence "melee_taunt" "sniper_animations_anims\melee_taunt.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "sniper_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "melee_taunt"
}

$sequence "layer_taunt04" "sniper_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "sniper_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
}

$sequence "taunt06" "sniper_animations_anims\taunt06.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "layer_taunt_replay" "sniper_animations_anims\layer_taunt_replay.smd" {
	fps 30
	hidden
}

$sequence "taunt_replay" "sniper_animations_anims\taunt_replay.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_replay"
	{ event AE_WPN_HIDE 0.999999977648258 "" }
	{ event AE_WPN_UNHIDE 99.0000009536743 "" }
}

$sequence "taunt_brutallegendinterior" "sniper_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "sniper_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "sniper_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "sniper_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "sniper_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "sniper_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_highFiveStart" "sniper_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 86 "" }
}

$sequence "layer_taunt_highFiveSuccess" "sniper_animations_anims\layer_taunt_highFiveSuccess.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccess" "sniper_animations_anims\taunt_highFiveSuccess.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccess"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 119.000000953674 "" }
}

$sequence "layer_taunt_highFiveSuccessFull" "sniper_animations_anims\layer_taunt_highFiveSuccessFull.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccessFull" "sniper_animations_anims\taunt_highFiveSuccessFull.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccessFull"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 112.999997019768 "" }
}

$sequence "layer_taunt_laugh" "sniper_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "sniper_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 1.00000003818423 "" }
	{ event AE_WPN_UNHIDE 104.000000059605 "" }
}

$sequence "taunt_conga" "sniper_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "sniper_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "sniper_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
}

$sequence "layer_taunt_dosido_intro" "sniper_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "sniper_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
}

$sequence "taunt_flip_start" "sniper_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "sniper_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "sniper_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000000745058 "" }
	{ event AE_WPN_UNHIDE 160.000001192093 "" }
}

$sequence "layer_taunt_flip_success_receiver" "sniper_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "sniper_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 1.00000005122274 "" }
	{ event AE_WPN_UNHIDE 110.000000536442 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 41.0000011026859 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 59.0000000298023 "taunt_flip_land follow_attachment foot_R" }
}

$sequence "taunt_RPS_start" "sniper_animations_anims\taunt_RPS_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "sniper_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "sniper_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "sniper_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "sniper_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "sniper_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "sniper_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_rock_win" "sniper_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "sniper_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.999994277954 "" }
}

$sequence "layer_taunt_rps_paper_win" "sniper_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "sniper_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.999994277954 "" }
}

$sequence "layer_taunt_rps_scissors_win" "sniper_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "sniper_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.999994277954 "" }
}

$sequence "layer_taunt_rps_rock_lose" "sniper_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "sniper_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.000001847744 "" }
}

$sequence "layer_taunt_rps_paper_lose" "sniper_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "sniper_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.000001847744 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "sniper_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "sniper_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 200.000001847744 "" }
}

$sequence "layer_taunt_headbutt_start" "sniper_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "sniper_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 191 "" }
}

$sequence "layer_taunt_headbutt_success" "sniper_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "sniper_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55.9999997913837 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 145 "" }
}

$sequence "layer_taunt_i_see_you_primary" "sniper_animations_anims\layer_taunt_i_see_you_primary.smd" {
	fps 30
	hidden
}

$sequence "taunt_i_see_you_primary" "sniper_animations_anims\taunt_i_see_you_primary.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_i_see_you_primary"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 97 "" }
}

$ikchain "rhand" "bip_hand_R" knee 0.753 0.658 0
$ikchain "lhand" "bip_hand_L" knee 0.653 -0.757 0
$ikchain "rfoot" "bip_foot_R" knee 0.628 0.001 0.779
$ikchain "lfoot" "bip_foot_L" knee 0.63 -0.001 0.776

