// Created by Crowbar 0.19.0.0

$modelname "player/heavy_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_x" -1 1 0
$poseparameter "move_y" -1 1 0

$cdmaterials "models\player\heavy\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "heavy_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "heavy_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "heavy_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "heavy_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "heavy_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "heavy_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "heavy_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "heavy_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "heavy_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "heavy_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "heavy_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "heavy_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "heavy_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "heavy_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "heavy_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "heavy_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "heavy_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_deployed_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_walk_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_crouch_walk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_deployed_crouch_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_deployed_crouch_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "heavy_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "heavy_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "heavy_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "heavy_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "heavy_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "heavy_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "heavy_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "heavy_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "heavy_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "heavy_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "heavy_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "heavy_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "heavy_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "heavy_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "heavy_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "heavy_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "heavy_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "heavy_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "heavy_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "heavy_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "heavy_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "heavy_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "heavy_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "heavy_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "heavy_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "heavy_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "heavy_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_neutral" "heavy_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "heavy_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "heavy_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "heavy_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "heavy_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "heavy_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "heavy_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "heavy_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "heavy_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "heavy_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "heavy_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "heavy_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_deployed_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_deployed_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimDeployedCenter_PRIMARY" "heavy_animations_anims\a_swimDeployedCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedS_PRIMARY" "heavy_animations_anims\a_swimDeployedS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedSE_PRIMARY" "heavy_animations_anims\a_swimDeployedSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedE_PRIMARY" "heavy_animations_anims\a_swimDeployedE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedNE_PRIMARY" "heavy_animations_anims\a_swimDeployedNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SwimDeployedN_PRIMARY" "heavy_animations_anims\a_SwimDeployedN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedNW_PRIMARY" "heavy_animations_anims\a_swimDeployedNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedW_PRIMARY" "heavy_animations_anims\a_swimDeployedW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimDeployedSW_PRIMARY" "heavy_animations_anims\a_swimDeployedSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "heavy_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "heavy_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "heavy_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "heavy_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "heavy_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "heavy_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "heavy_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "heavy_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "heavy_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "heavy_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "heavy_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "heavy_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "heavy_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "heavy_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "heavy_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "heavy_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "heavy_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "heavy_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "heavy_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "heavy_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "heavy_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "heavy_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "heavy_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "heavy_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "heavy_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "heavy_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "heavy_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "heavy_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "heavy_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "heavy_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "heavy_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "heavy_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "heavy_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "heavy_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "heavy_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "heavy_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "heavy_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "heavy_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "heavy_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "heavy_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "heavy_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "heavy_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "heavy_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "heavy_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "heavy_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "heavy_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "heavy_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "heavy_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "heavy_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "heavy_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "heavy_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "heavy_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "heavy_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "heavy_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "heavy_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "heavy_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "heavy_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "heavy_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "heavy_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "heavy_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "heavy_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "heavy_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "heavy_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "heavy_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "heavy_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "heavy_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "heavy_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "heavy_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "heavy_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "heavy_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "heavy_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "heavy_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "heavy_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "heavy_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "heavy_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "heavy_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "heavy_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "heavy_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedCenter_PRIMARY" "heavy_animations_anims\a_deployedCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedS_PRIMARY" "heavy_animations_anims\a_deployedS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSE_PRIMARY" "heavy_animations_anims\a_deployedSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedE_PRIMARY" "heavy_animations_anims\a_deployedE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNE_PRIMARY" "heavy_animations_anims\a_deployedNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedN_PRIMARY" "heavy_animations_anims\a_deployedN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedNW_PRIMARY" "heavy_animations_anims\a_deployedNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedW_PRIMARY" "heavy_animations_anims\a_deployedW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_deployedSW_PRIMARY" "heavy_animations_anims\a_deployedSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "heavy_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "heavy_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "heavy_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "heavy_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "heavy_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "heavy_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "heavy_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "heavy_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "heavy_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_neutral" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_down_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_down_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_down_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_mid_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_mid_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_mid_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_up_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_up_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_up_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkN_straight_up" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkN_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_neutral" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_down_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_down_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_down_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_mid_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_mid_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_mid_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_up_right" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_up_center" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_up_left" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimMatrix_crouch_walkS_straight_up" "heavy_animations_anims\a_PRIMARY_aimMatrix_crouch_walkS_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_runCenter_SECONDARY" "heavy_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "heavy_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "heavy_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "heavy_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "heavy_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "heavy_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "heavy_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "heavy_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "heavy_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_SECONDARY" "heavy_animations_anims\a_crouch_walkCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_SECONDARY" "heavy_animations_anims\a_crouch_walkS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_SECONDARY" "heavy_animations_anims\a_crouch_walkSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_SECONDARY" "heavy_animations_anims\a_crouch_walkE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_SECONDARY" "heavy_animations_anims\a_crouch_walkNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_SECONDARY" "heavy_animations_anims\a_crouch_walkN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_SECONDARY" "heavy_animations_anims\a_crouch_walkNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_SECONDARY" "heavy_animations_anims\a_crouch_walkW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_SECONDARY" "heavy_animations_anims\a_crouch_walkSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "heavy_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "heavy_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "heavy_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "heavy_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "heavy_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "heavy_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "heavy_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "heavy_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "heavy_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_MELEE" "heavy_animations_anims\a_crouch_walkCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_MELEE" "heavy_animations_anims\a_crouch_walkS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_MELEE" "heavy_animations_anims\a_crouch_walkSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_MELEE" "heavy_animations_anims\a_crouch_walkE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_MELEE" "heavy_animations_anims\a_crouch_walkNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_MELEE" "heavy_animations_anims\a_crouch_walkN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_MELEE" "heavy_animations_anims\a_crouch_walkNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_MELEE" "heavy_animations_anims\a_crouch_walkW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_MELEE" "heavy_animations_anims\a_crouch_walkSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "heavy_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "heavy_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "heavy_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "heavy_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "heavy_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "heavy_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "heavy_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "heavy_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "heavy_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_MELEE_ALLCLASS" "heavy_animations_anims\a_crouch_walkSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "heavy_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "heavy_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "heavy_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "heavy_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "heavy_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "heavy_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "heavy_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "heavy_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "heavy_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "heavy_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "heavy_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "heavy_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "heavy_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "heavy_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "heavy_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "heavy_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "heavy_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "heavy_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "heavy_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "heavy_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_airwalk_neutral" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_down_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_mid_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_right" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_center" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_up_left" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_airwalk_straight_up" "heavy_animations_anims\a_SECONDARY_aimmatrix_airwalk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_stun_startpose" "heavy_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "heavy_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "heavy_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "heavy_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "SPELL_arm_pose_raw" "heavy_animations_anims\SPELL_arm_pose_raw.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_deployed" {
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_straight_up"
	"a_PRIMARY_aimmatrix_deployed_up_right"
	"a_PRIMARY_aimmatrix_deployed_up_center"
	"a_PRIMARY_aimmatrix_deployed_up_left"
	"a_PRIMARY_aimmatrix_deployed_mid_right"
	"a_PRIMARY_aimmatrix_deployed_mid_center"
	"a_PRIMARY_aimmatrix_deployed_mid_left"
	"a_PRIMARY_aimmatrix_deployed_down_right"
	"a_PRIMARY_aimmatrix_deployed_down_center"
	"a_PRIMARY_aimmatrix_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_walk" {
	"a_PRIMARY_aimmatrix_crouch_walk_straight_up"
	"a_PRIMARY_aimmatrix_crouch_walk_straight_up"
	"a_PRIMARY_aimmatrix_crouch_walk_straight_up"
	"a_PRIMARY_aimmatrix_crouch_walk_up_right"
	"a_PRIMARY_aimmatrix_crouch_walk_up_center"
	"a_PRIMARY_aimmatrix_crouch_walk_up_left"
	"a_PRIMARY_aimmatrix_crouch_walk_mid_right"
	"a_PRIMARY_aimmatrix_crouch_walk_mid_center"
	"a_PRIMARY_aimmatrix_crouch_walk_mid_left"
	"a_PRIMARY_aimmatrix_crouch_walk_down_right"
	"a_PRIMARY_aimmatrix_crouch_walk_down_center"
	"a_PRIMARY_aimmatrix_crouch_walk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_deployed_crouch" {
	"a_PRIMARY_aimmatrix_deployed_crouch_straight_up"
	"a_PRIMARY_aimmatrix_deployed_crouch_straight_up"
	"a_PRIMARY_aimmatrix_deployed_crouch_straight_up"
	"a_PRIMARY_aimmatrix_deployed_crouch_up_right"
	"a_PRIMARY_aimmatrix_deployed_crouch_up_center"
	"a_PRIMARY_aimmatrix_deployed_crouch_up_left"
	"a_PRIMARY_aimmatrix_deployed_crouch_mid_right"
	"a_PRIMARY_aimmatrix_deployed_crouch_mid_center"
	"a_PRIMARY_aimmatrix_deployed_crouch_mid_left"
	"a_PRIMARY_aimmatrix_deployed_crouch_down_right"
	"a_PRIMARY_aimmatrix_deployed_crouch_down_center"
	"a_PRIMARY_aimmatrix_deployed_crouch_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "heavy_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "heavy_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "heavy_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "a_SECONDARY_reload" "heavy_animations_anims\a_SECONDARY_reload.smd" {
	fps 30
}

$sequence "SECONDARY_reload" "heavy_animations_anims\SECONDARY_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
}

$sequence "SECONDARY_reload_loop" "heavy_animations_anims\SECONDARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_LOOP" 1
	// delta
}

$sequence "a_SECONDARY_reload_end" "heavy_animations_anims\a_SECONDARY_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_crouch_reload" "heavy_animations_anims\a_SECONDARY_crouch_reload.smd" {
	fps 30
}

$sequence "SECONDARY_crouch_reload" "heavy_animations_anims\SECONDARY_crouch_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_crouch_reload_loop" "heavy_animations_anims\a_SECONDARY_crouch_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_crouch_reload_end" "heavy_animations_anims\a_SECONDARY_crouch_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_swim_reload" "heavy_animations_anims\a_SECONDARY_swim_reload.smd" {
	fps 30
}

$sequence "SECONDARY_swim_reload" "heavy_animations_anims\SECONDARY_swim_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_swim_reload_loop" "heavy_animations_anims\a_SECONDARY_swim_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_swim_reload_end" "heavy_animations_anims\a_SECONDARY_swim_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_reload_airwalk" "heavy_animations_anims\a_SECONDARY_reload_airwalk.smd" {
	fps 30
}

$sequence "SECONDARY_reload_airwalk" "heavy_animations_anims\SECONDARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_reload_airwalk_loop" "heavy_animations_anims\a_SECONDARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_reload_airwalk_end" "heavy_animations_anims\a_SECONDARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_END" 1
	// delta
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "attackStand_MELEE_L" "heavy_animations_anims\attackStand_MELEE_L.smd" {
	fps 40
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// delta
}

$sequence "attackStand_MELEE_R" "heavy_animations_anims\attackStand_MELEE_R.smd" {
	fps 35
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// delta
}

$sequence "attackStand_MELEE_U" "heavy_animations_anims\attackStand_MELEE_U.smd" {
	fps 35
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_SECONDARY" 1
	// delta
}

$sequence "attackCrouch_MELEE_L" "heavy_animations_anims\attackCrouch_MELEE_L.smd" {
	fps 40
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// delta
}

$sequence "attackCrouch_MELEE_R" "heavy_animations_anims\attackCrouch_MELEE_R.smd" {
	fps 35
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// delta
}

$sequence "attackCrouch_MELEE_U" "heavy_animations_anims\attackCrouch_MELEE_U.smd" {
	fps 35
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_SECONDARY" 1
	// delta
}

$sequence "layer_attackSwimNMELEE_arms" "heavy_animations_anims\layer_attackSwimNMELEE_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_MELEE_swim_swingN" "heavy_animations_anims\layer_MELEE_swim_swingN.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_attackSwimNMELEE_arms"
}

$sequence "layer_attackSwimSMELEE_arms" "heavy_animations_anims\layer_attackSwimSMELEE_arms.smd" {
	fps 30
	hidden
}

$sequence "layer_MELEE_swim_swingS" "heavy_animations_anims\layer_MELEE_swim_swingS.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_attackSwimSMELEE_arms"
}

$sequence "attackSwim_MELEE" "heavy_animations_anims\attackSwim_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	blendlayer "layer_MELEE_swim_swingN" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_MELEE_swim_swingS" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "attackSwim_MELEE_Crit" "heavy_animations_anims\attackSwim_MELEE_Crit.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_SECONDARY" 1
	blendlayer "layer_MELEE_swim_swingN" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_MELEE_swim_swingS" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "attackStand_MELEE_ALLCLASS" "heavy_animations_anims\attackStand_MELEE_ALLCLASS.smd" {
	fps 40
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "attackCrouch_MELEE_ALLCLASS" "heavy_animations_anims\attackCrouch_MELEE_ALLCLASS.smd" {
	fps 40
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "layer_attackSwimNMELEE_ALLCLASS_arms" "heavy_animations_anims\layer_attackSwimNMELEE_ALLCLASS_arms.smd" {
	fps 60
	hidden
}

$sequence "layer_melee_ALLCLASS_swim_swingN" "heavy_animations_anims\layer_melee_ALLCLASS_swim_swingN.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_attackSwimNMELEE_ALLCLASS_arms"
}

$sequence "layer_attackSwimSMELEE_ALLCLASS_arms" "heavy_animations_anims\layer_attackSwimSMELEE_ALLCLASS_arms.smd" {
	fps 30
	hidden
}

$sequence "layer_MELEE_ALLCLASS_swim_swingS" "heavy_animations_anims\layer_MELEE_ALLCLASS_swim_swingS.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	// addlayer "layer_attackSwimSMELEE_ALLCLASS_arms"
}

$sequence "attackSwim_MELEE_ALLCLASS" "heavy_animations_anims\attackSwim_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	blendlayer "layer_melee_ALLCLASS_swim_swingN" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_MELEE_ALLCLASS_swim_swingS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	// addlayer "r_handposes"
}

$sequence "attackSwim_MELEE_ALLCLASS_Crit" "heavy_animations_anims\attackSwim_MELEE_ALLCLASS_Crit.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS_SECONDARY" 1
	blendlayer "layer_melee_ALLCLASS_swim_swingN" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "layer_MELEE_ALLCLASS_swim_swingS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	// addlayer "r_handposes"
}

$sequence "diesimple" "heavy_animations_anims\diesimple.smd" {
	fps 30
	"ACT_DIESIMPLE" 1
	{ event AE_RAGDOLL 52.0000011920929 "temp" }
}

$sequence "stand_PRIMARY" "heavy_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "heavy_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "heavy_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "heavy_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "heavy_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "heavy_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "heavy_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "heavy_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "heavy_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "heavy_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "heavy_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "heavy_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "jumpstart_PRIMARY" "heavy_animations_anims\jumpstart_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
}

$sequence "jumpfloat_PRIMARY" "heavy_animations_anims\jumpfloat_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
}

$sequence "jumpland_PRIMARY" "heavy_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "jumpstart_SECONDARY" "heavy_animations_anims\jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "jumpfloat_SECONDARY" "heavy_animations_anims\jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumpland_SECONDARY" "heavy_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "jumpstart_MELEE" "heavy_animations_anims\jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "jumpfloat_MELEE" "heavy_animations_anims\jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumpland_MELEE" "heavy_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "jumpstart_MELEE_ALLCLASS" "heavy_animations_anims\jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumpfloat_MELEE_ALLCLASS" "heavy_animations_anims\jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumpland_MELEE_ALLCLASS" "heavy_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "heavy_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "heavy_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "heavy_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "heavy_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "jumpstart_ITEM1" "heavy_animations_anims\jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "jumpfloat_ITEM1" "heavy_animations_anims\jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumpland_ITEM1" "heavy_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim_deployed" {
	"a_PRIMARY_aimmatrix_swim_deployed_straight_up"
	"a_PRIMARY_aimmatrix_swim_deployed_straight_up"
	"a_PRIMARY_aimmatrix_swim_deployed_straight_up"
	"a_PRIMARY_aimmatrix_swim_deployed_up_right"
	"a_PRIMARY_aimmatrix_swim_deployed_up_center"
	"a_PRIMARY_aimmatrix_swim_deployed_up_left"
	"a_PRIMARY_aimmatrix_swim_deployed_mid_right"
	"a_PRIMARY_aimmatrix_swim_deployed_mid_center"
	"a_PRIMARY_aimmatrix_swim_deployed_mid_left"
	"a_PRIMARY_aimmatrix_swim_deployed_down_right"
	"a_PRIMARY_aimmatrix_swim_deployed_down_center"
	"a_PRIMARY_aimmatrix_swim_deployed_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_swim_deployed_movement" {
	"a_swimDeployedSW_PRIMARY"
	"a_swimDeployedS_PRIMARY"
	"a_swimDeployedSE_PRIMARY"
	"a_swimDeployedW_PRIMARY"
	"a_swimDeployedCenter_PRIMARY"
	"a_swimDeployedE_PRIMARY"
	"a_swimDeployedNW_PRIMARY"
	"a_SwimDeployedN_PRIMARY"
	"a_swimDeployedNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_DEPLOYED_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim_deployed"
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 13 "left" }
	{ event 7001 5 "right" }
}

$sequence "crouch_deployed_PRIMARY" "heavy_animations_anims\crouch_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_aimmatrix_deployed_crouch"
}

$sequence "stand_deployed_PRIMARY" "heavy_animations_anims\stand_deployed_PRIMARY.smd" {
	fps 30
	"ACT_MP_DEPLOYED_IDLE" 1
	loop
	// addlayer "PRIMARY_aimmatrix_deployed"
}

$sequence "PRIMARY_deployed_movement" {
	"a_deployedSW_PRIMARY"
	"a_deployedS_PRIMARY"
	"a_deployedSE_PRIMARY"
	"a_deployedW_PRIMARY"
	"a_deployedCenter_PRIMARY"
	"a_deployedE_PRIMARY"
	"a_deployedNW_PRIMARY"
	"a_deployedN_PRIMARY"
	"a_deployedNE_PRIMARY"
	fps 30
	"ACT_MP_DEPLOYED_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_deployed"
	{ event 7001 16.9999995231628 "left" }
	{ event 7001 4.99999988079071 "right" }
}

$sequence "PRIMARY_aimMatrix_crouch_walkN" {
	"a_PRIMARY_aimMatrix_crouch_walkN_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkN_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkN_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkN_up_right"
	"a_PRIMARY_aimMatrix_crouch_walkN_up_center"
	"a_PRIMARY_aimMatrix_crouch_walkN_up_left"
	"a_PRIMARY_aimMatrix_crouch_walkN_mid_right"
	"a_PRIMARY_aimMatrix_crouch_walkN_mid_center"
	"a_PRIMARY_aimMatrix_crouch_walkN_mid_left"
	"a_PRIMARY_aimMatrix_crouch_walkN_down_right"
	"a_PRIMARY_aimMatrix_crouch_walkN_down_center"
	"a_PRIMARY_aimMatrix_crouch_walkN_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimMatrix_crouch_walkS" {
	"a_PRIMARY_aimMatrix_crouch_walkS_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkS_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkS_straight_up"
	"a_PRIMARY_aimMatrix_crouch_walkS_up_right"
	"a_PRIMARY_aimMatrix_crouch_walkS_up_center"
	"a_PRIMARY_aimMatrix_crouch_walkS_up_left"
	"a_PRIMARY_aimMatrix_crouch_walkS_mid_right"
	"a_PRIMARY_aimMatrix_crouch_walkS_mid_center"
	"a_PRIMARY_aimMatrix_crouch_walkS_mid_left"
	"a_PRIMARY_aimMatrix_crouch_walkS_down_right"
	"a_PRIMARY_aimMatrix_crouch_walkS_down_center"
	"a_PRIMARY_aimMatrix_crouch_walkS_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	blendlayer "PRIMARY_aimMatrix_crouch_walkN" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "PRIMARY_aimMatrix_crouch_walkS" -2 -1 -0.8 -0.2 spline poseparameter move_x
	{ event 7001 7.00000002980232 "left" }
	{ event 7001 22.9999995231628 "right" }
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_idle"
	{ event 7001 15 "left" }
	{ event 7001 7 "right" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_SECONDARY"
	"a_crouch_walkS_SECONDARY"
	"a_crouch_walkSE_SECONDARY"
	"a_crouch_walkW_SECONDARY"
	"a_crouch_walkCenter_SECONDARY"
	"a_crouch_walkE_SECONDARY"
	"a_crouch_walkNW_SECONDARY"
	"a_crouch_walkN_SECONDARY"
	"a_crouch_walkNE_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
	{ event 7001 7.00000002980232 "left" }
	{ event 7001 22.0000004768372 "right" }
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 14 "left" }
	{ event 7001 6 "right" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_MELEE"
	"a_crouch_walkS_MELEE"
	"a_crouch_walkSE_MELEE"
	"a_crouch_walkW_MELEE"
	"a_crouch_walkCenter_MELEE"
	"a_crouch_walkE_MELEE"
	"a_crouch_walkNW_MELEE"
	"a_crouch_walkN_MELEE"
	"a_crouch_walkNE_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
	{ event 7001 7.00000002980232 "left" }
	{ event 7001 22.0000004768372 "right" }
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 14 "left" }
	{ event 7001 6 "right" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_MELEE_ALLCLASS"
	"a_crouch_walkS_MELEE_ALLCLASS"
	"a_crouch_walkSE_MELEE_ALLCLASS"
	"a_crouch_walkW_MELEE_ALLCLASS"
	"a_crouch_walkCenter_MELEE_ALLCLASS"
	"a_crouch_walkE_MELEE_ALLCLASS"
	"a_crouch_walkNW_MELEE_ALLCLASS"
	"a_crouch_walkN_MELEE_ALLCLASS"
	"a_crouch_walkNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 7.00000002980232 "left" }
	{ event 7001 22.0000004768372 "right" }
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_run"
	{ event 7001 14 "left" }
	{ event 7001 6 "right" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "airwalk_PRIMARY" "heavy_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_run"
}

$sequence "SECONDARY_aimmatrix_airwalk" {
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_straight_up"
	"a_SECONDARY_aimmatrix_airwalk_up_right"
	"a_SECONDARY_aimmatrix_airwalk_up_center"
	"a_SECONDARY_aimmatrix_airwalk_up_left"
	"a_SECONDARY_aimmatrix_airwalk_mid_right"
	"a_SECONDARY_aimmatrix_airwalk_mid_center"
	"a_SECONDARY_aimmatrix_airwalk_mid_left"
	"a_SECONDARY_aimmatrix_airwalk_down_right"
	"a_SECONDARY_aimmatrix_airwalk_down_center"
	"a_SECONDARY_aimmatrix_airwalk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "airwalk_SECONDARY" "heavy_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_airwalk"
}

$sequence "airwalk_MELEE" "heavy_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "airwalk_MELEE_ALLCLASS" "heavy_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "heavy_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "heavy_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "attackCrouch_PRIMARY" "heavy_animations_anims\attackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "layer_attackCrouch_PRIMARY_spoolup" "heavy_animations_anims\layer_attackCrouch_PRIMARY_spoolup.smd" {
	fps 30
	blendlayer "PRIMARY_aimmatrix_crouch_idle" 0 0 0 0.333333 spline
	blendlayer "PRIMARY_aimmatrix_deployed_crouch" 0 0.333333 1 1 spline
	fadein 0.7
	fadeout 0.7
}

$sequence "attackCrouch_PRIMARY_spoolup" "heavy_animations_anims\attackCrouch_PRIMARY_spoolup.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PREFIRE" 1
	blendlayer "layer_attackCrouch_PRIMARY_spoolup" 0 0 1 1 spline
}

$sequence "layer_attackCrouch_PRIMARY_spooldown" "heavy_animations_anims\layer_attackCrouch_PRIMARY_spooldown.smd" {
	fps 30
	blendlayer "PRIMARY_aimmatrix_deployed_crouch" 0 0 0 0.333333 spline
	blendlayer "PRIMARY_aimmatrix_crouch_idle" 0 0.333333 1 1 spline
	fadein 0.5
	fadeout 0.5
}

$sequence "attackCrouch_PRIMARY_spooldown" "heavy_animations_anims\attackCrouch_PRIMARY_spooldown.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_POSTFIRE" 1
	blendlayer "layer_attackCrouch_PRIMARY_spooldown" 0 0 1 1 spline
}

$sequence "attackStand_PRIMARY" "heavy_animations_anims\attackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "layer_attackStand_PRIMARY_spoolup" "heavy_animations_anims\layer_attackStand_PRIMARY_spoolup.smd" {
	fps 30
	blendlayer "PRIMARY_aimmatrix_idle" 0 0 0 0.333333 spline
	blendlayer "PRIMARY_aimmatrix_deployed" 0 0.333333 1 1 spline
	fadein 0.7
	fadeout 0.7
}

$sequence "attackStand_PRIMARY_spoolup" "heavy_animations_anims\attackStand_PRIMARY_spoolup.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PREFIRE" 1
	blendlayer "layer_attackStand_PRIMARY_spoolup" 0 0.666667 1 1 spline
}

$sequence "layer_attackStand_PRIMARY_spooldown" "heavy_animations_anims\layer_attackStand_PRIMARY_spooldown.smd" {
	fps 30
	blendlayer "PRIMARY_aimmatrix_deployed" 0 0 0 0.333333 spline
	blendlayer "PRIMARY_aimmatrix_idle" 0 0.333333 1 1 spline
	fadein 0.5
	fadeout 0.5
}

$sequence "attackStand_PRIMARY_spooldown" "heavy_animations_anims\attackStand_PRIMARY_spooldown.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_POSTFIRE" 1
	blendlayer "layer_attackStand_PRIMARY_spooldown" 0 0 0.666667 1 spline
}

$sequence "attackSwim_PRIMARY" "heavy_animations_anims\attackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "attackSwim_PRIMARY_spoolup" "heavy_animations_anims\attackSwim_PRIMARY_spoolup.smd" {
	fps 30
	"ACT_MP_ATTACK_SWIM_PREFIRE" 1
}

$sequence "attackSwim_PRIMARY_spooldown" "heavy_animations_anims\attackSwim_PRIMARY_spooldown.smd" {
	fps 30
	"ACT_MP_ATTACK_SWIM_POSTFIRE" 1
}

$sequence "PRIMARY_flinch" "heavy_animations_anims\PRIMARY_flinch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "SECONDARY_flinch" "heavy_animations_anims\SECONDARY_flinch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "MELEE_flinch" "heavy_animations_anims\MELEE_flinch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "MELEE_ALLCLASS_flinch" "heavy_animations_anims\MELEE_ALLCLASS_flinch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "layer_placeSapper_ArmL" "heavy_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "heavy_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "layer_gesture_PRIMARY_go_armL" "heavy_animations_anims\layer_gesture_PRIMARY_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_go" "heavy_animations_anims\gesture_PRIMARY_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
}

$sequence "layer_gesture_PRIMARY_help_armL" "heavy_animations_anims\layer_gesture_PRIMARY_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_help" "heavy_animations_anims\gesture_PRIMARY_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_PRIMARY_help_armL"
}

$sequence "layer_gesture_PRIMARY_cheer_armL" "heavy_animations_anims\layer_gesture_PRIMARY_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_cheer" "heavy_animations_anims\gesture_PRIMARY_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_PRIMARY_cheer_armL"
}

$sequence "layer_gesture_PRIMARY_positive_armL" "heavy_animations_anims\layer_gesture_PRIMARY_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_positive" "heavy_animations_anims\gesture_PRIMARY_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_PRIMARY_positive_armL"
}

$sequence "layer_gesture_SECONDARY_go_armL" "heavy_animations_anims\layer_gesture_SECONDARY_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_go" "heavy_animations_anims\gesture_SECONDARY_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
}

$sequence "layer_gesture_SECONDARY_help_armL" "heavy_animations_anims\layer_gesture_SECONDARY_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_help" "heavy_animations_anims\gesture_SECONDARY_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_SECONDARY_help_armL"
}

$sequence "layer_gesture_SECONDARY_cheer_armL" "heavy_animations_anims\layer_gesture_SECONDARY_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_cheer" "heavy_animations_anims\gesture_SECONDARY_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_SECONDARY_cheer_armL"
}

$sequence "layer_gesture_SECONDARY_positive_armL" "heavy_animations_anims\layer_gesture_SECONDARY_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_positive" "heavy_animations_anims\gesture_SECONDARY_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_SECONDARY_positive_armL"
}

$sequence "layer_gesture_MELEE_go_armL" "heavy_animations_anims\layer_gesture_MELEE_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_go" "heavy_animations_anims\gesture_MELEE_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_go_armL"
}

$sequence "layer_gesture_MELEE_help_armL" "heavy_animations_anims\layer_gesture_MELEE_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_help" "heavy_animations_anims\gesture_MELEE_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_help_armL"
}

$sequence "layer_gesture_MELEE_cheer_armL" "heavy_animations_anims\layer_gesture_MELEE_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_cheer" "heavy_animations_anims\gesture_MELEE_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_cheer_armL"
}

$sequence "layer_gesture_MELEE_positive" "heavy_animations_anims\layer_gesture_MELEE_positive.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_positive" "heavy_animations_anims\gesture_MELEE_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_positive"
}

$sequence "layer_dieviolent" "heavy_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "heavy_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "PRIMARY_death_headshot" "heavy_animations_anims\PRIMARY_death_headshot.smd" {
	fps 30
}

$sequence "PRIMARY_death_backstab" "heavy_animations_anims\PRIMARY_death_backstab.smd" {
	fps 30
}

$sequence "freeze" "heavy_animations_anims\freeze.smd" {
	fps 30
}

$sequence "PRIMARY_death_burning" "heavy_animations_anims\PRIMARY_death_burning.smd" {
	fps 30
}

$sequence "layer_PRIMARY_stun_begin" "heavy_animations_anims\layer_PRIMARY_stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "heavy_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_end" "heavy_animations_anims\layer_PRIMARY_stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_stun_begin" "heavy_animations_anims\PRIMARY_stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_begin"
}

$sequence "PRIMARY_stun_middle" "heavy_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "heavy_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_end"
}

$sequence "selectionMenu_StartPose" "heavy_animations_anims\selectionMenu_StartPose.smd" {
	fps 30
}

$sequence "selectionMenu_Anim01" "heavy_animations_anims\selectionMenu_Anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 7.00000013411045 "Selection.HeavyFootStomp" }
	{ event AE_CL_PLAYSOUND 10.0000003427267 "Selection.HeavyClothesRustle" }
	{ event AE_CL_PLAYSOUND 11.9999997764826 "Selection.HeavyEquipment1" }
	{ event AE_CL_PLAYSOUND 33.0000001788139 "Selection.HeavyFootStomp" }
	{ event AE_CL_PLAYSOUND 37.9999998211861 "Selection.HeavyEquipment2" }
}

$sequence "selectionMenu_Idle" "heavy_animations_anims\selectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "armslayer_throw_fire" "heavy_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "heavy_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "heavy_animations_anims\layer_taunt01.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "heavy_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt01"
	{ event 5004 36.9999994635582 "Taunt.Heavy01HoldGun" }
	{ event 5004 66.0000006556511 "Taunt.Heavy01HoldGun" }
	{ event 5004 75.9999996423721 "Taunt.Heavy01HoldGunLight" }
	{ event 5004 96.9999979734421 "Taunt.Heavy01EquipmentGun2" }
	{ event 5004 17.9999995529652 "Taunt.Heavy01EquipmentGun" }
	{ event 5004 44.9999977350235 "Taunt.Heavy01EquipmentRustleHeavy" }
	{ event 5004 15.9999999850988 "Taunt.Heavy01ClothesRustle" }
	{ event 5004 134.000002026558 "Taunt.Heavy01EquipmentGun" }
}

$sequence "layer_taunt02" "heavy_animations_anims\layer_taunt02.smd" {
	fps 30
	hidden
}

$sequence "taunt02" "heavy_animations_anims\taunt02.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt02"
	{ event 5004 12.0000001713634 "Taunt.Heavy02ShotgunSpin" }
	{ event 5004 55.0000002682209 "Taunt.Heavy02ShotgunGrab" }
	{ event 5004 57.0000001490116 "Taunt.Heavy02EquipmentJingle" }
}

$sequence "layer_taunt03" "heavy_animations_anims\layer_taunt03.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "heavy_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt03"
	{ event AE_WPN_HIDE 1.00000005122274 "" }
	{ event AE_WPN_UNHIDE 118.000000059605 "" }
	{ event 5004 40.0000011622906 "Taunt.Heavy03ClothesRustle" }
	{ event 5004 77.0000025033951 "Taunt.Heavy03ClothesSwipe" }
	{ event 5004 44.000000923872 "Taunt.Heavy03EquipmentJingle" }
	{ event 5004 81.0000022649765 "Taunt.Heavy03EquipmentJingleShort" }
}

$sequence "layer_taunt04" "heavy_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "heavy_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
	{ event AE_CL_BODYGROUP_SET_VALUE_CMODEL_WPN 24.0000003576279 "bites 1" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 30 "sandwich_fx follow_attachment eyes" }
}

$sequence "layer_taunt05" "heavy_animations_anims\layer_taunt05.smd" {
	fps 30
	hidden
}

$sequence "taunt05" "heavy_animations_anims\taunt05.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt05"
	{ event 5004 7.99999997019768 "Taunt.HeavyBell" }
	{ event 5004 39.9999998509884 "Taunt.HeavyUpperCut" }
	{ event 5004 62.0000007152557 "Taunt.HeavyUpperCut" }
	{ event 5004 88.0000034570694 "Taunt.HeavyUpperCut" }
	{ event 5004 111.000000059605 "Taunt.HeavyUpperCut" }
}

$sequence "taunt06" "heavy_animations_anims\taunt06.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.96 1 1 1 spline
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "layer_taunt07_Halloween" "heavy_animations_anims\layer_taunt07_Halloween.smd" {
	fps 30
	hidden
}

$sequence "taunt07_Halloween" "heavy_animations_anims\taunt07_Halloween.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt07_Halloween"
	{ event AE_WPN_HIDE 0.99999999627471 "" }
	{ event AE_WPN_UNHIDE 85.9999977350235 "" }
}

$sequence "heavy_taunt_replay" "heavy_animations_anims\heavy_taunt_replay.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.964706 1 1 1 spline
	{ event AE_WPN_HIDE 1.00000001955777 "" }
	{ event AE_WPN_UNHIDE 85 "" }
}

$sequence "layer_taunt_laugh" "heavy_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "heavy_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.99999999627471 "" }
	{ event AE_WPN_UNHIDE 145 "" }
}

$sequence "taunt_brutallegendinterior" "heavy_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "heavy_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "heavy_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "heavy_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "heavy_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "heavy_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_russianinterior" "heavy_animations_anims\taunt_russianinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_russianin" "heavy_animations_anims\taunt_russianin.smd" {
	fps 30
	hidden
}

$sequence "taunt_russianout" "heavy_animations_anims\taunt_russianout.smd" {
	fps 30
	hidden
}

$sequence "taunt_russianinblend" "heavy_animations_anims\taunt_russianinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_russianoutblend" "heavy_animations_anims\taunt_russianoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_russian" "heavy_animations_anims\taunt_russian.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_russianin" 0 0.017094 0.017094 0.017094 spline
	blendlayer "taunt_russianinterior" 0.017094 0.017094 0.970085 0.970085 spline
	blendlayer "taunt_russianout" 0.970085 0.970085 0.970085 1.004274 spline
	// addlayer "taunt_russianinblend"
	// addlayer "taunt_russianoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 5.00000013783574 "" }
	{ event AE_WPN_HIDE 234 "" }
}

$sequence "taunt_highFiveStart" "heavy_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 86 "" }
}

$sequence "layer_taunt_highFiveSuccessFull" "heavy_animations_anims\layer_taunt_highFiveSuccessFull.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccessFull" "heavy_animations_anims\taunt_highFiveSuccessFull.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccessFull"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 123.999997973442 "" }
}

$sequence "layer_taunt_highFiveSuccess" "heavy_animations_anims\layer_taunt_highFiveSuccess.smd" {
	fps 30
	hidden
}

$sequence "taunt_highFiveSuccess" "heavy_animations_anims\taunt_highFiveSuccess.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highFiveSuccess"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 112.999997019768 "" }
}

$sequence "taunt_conga" "heavy_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "heavy_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "heavy_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 1.00000001024455 "" }
	{ event AE_WPN_UNHIDE 261.000001430511 "" }
}

$sequence "layer_taunt_dosido_intro" "heavy_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "heavy_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
}

$sequence "taunt_flip_start" "heavy_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "heavy_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "heavy_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000001862645 "" }
	{ event AE_WPN_UNHIDE 130.000001907349 "" }
}

$sequence "layer_taunt_flip_success_receiver" "heavy_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "heavy_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 1.00000003119931 "" }
	{ event AE_WPN_UNHIDE 180.00000089407 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 40.0000005215406 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 56.0000024735928 "taunt_heavy_flip_land follow_attachment head" }
}

$sequence "taunt_rps_start" "heavy_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 120 "" }
}

$sequence "layer_taunt_rps_rock" "heavy_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "heavy_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "heavy_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "heavy_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "heavy_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "heavy_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper_win" "heavy_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "heavy_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_scissors_win" "heavy_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "heavy_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_rock_win" "heavy_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "heavy_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_rock_lose" "heavy_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "heavy_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 215.999998390675 "" }
}

$sequence "layer_taunt_rps_paper_lose" "heavy_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "heavy_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 215.999998390675 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "heavy_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "heavy_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 215.999998390675 "" }
}

$sequence "layer_taunt_headbutt_start" "heavy_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "heavy_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 216 "" }
}

$sequence "layer_taunt_headbutt_success" "heavy_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "heavy_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55.9999987483025 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 173 "" }
}

$ikchain "rhand" "bip_hand_R" knee 0.805 0.593 0.004
$ikchain "lhand" "bip_hand_L" knee 0.761 -0.648 0.004
$ikchain "rfoot" "bip_foot_R" knee 0.529 -0.849 0
$ikchain "lfoot" "bip_foot_L" knee 0.529 0.848 0

