// Created by Crowbar 0.19.0.0

$modelname "player/engineer_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_y" -1 1 0
$poseparameter "move_x" -1 1 0

$cdmaterials "models\player\engineer\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "engineer_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "engineer_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "engineer_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "engineer_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "engineer_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "engineer_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "engineer_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "engineer_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "engineer_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "engineer_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "engineer_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "engineer_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "engineer_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "engineer_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "engineer_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "engineer_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "engineer_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "engineer_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "engineer_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_neutral" "engineer_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "engineer_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "engineer_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "engineer_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "engineer_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "engineer_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "engineer_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "engineer_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "engineer_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "engineer_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "engineer_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "engineer_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "engineer_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "engineer_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "engineer_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "engineer_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "engineer_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "engineer_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "engineer_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "engineer_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "engineer_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "engineer_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_neutral" "engineer_animations_anims\a_MELEE_aimmatrix_walk_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_walk_down_right" "engineer_animations_anims\a_MELEE_aimmatrix_walk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_down_center" "engineer_animations_anims\a_MELEE_aimmatrix_walk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_down_left" "engineer_animations_anims\a_MELEE_aimmatrix_walk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_mid_right" "engineer_animations_anims\a_MELEE_aimmatrix_walk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_mid_center" "engineer_animations_anims\a_MELEE_aimmatrix_walk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_mid_left" "engineer_animations_anims\a_MELEE_aimmatrix_walk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_up_right" "engineer_animations_anims\a_MELEE_aimmatrix_walk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_up_center" "engineer_animations_anims\a_MELEE_aimmatrix_walk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_up_left" "engineer_animations_anims\a_MELEE_aimmatrix_walk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_walk_straight_up" "engineer_animations_anims\a_MELEE_aimmatrix_walk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_neutral" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_down_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_down_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_down_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_mid_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_mid_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_mid_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_up_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_up_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_up_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_walk_straight_up" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_walk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_Swing" "engineer_animations_anims\a_Melee_Swing.smd" {
	fps 30
}
$animation "a_Melee_Crouch_Swing" "engineer_animations_anims\a_Melee_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Swing" "engineer_animations_anims\a_Melee_allclass_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Crouch_Swing" "engineer_animations_anims\a_Melee_allclass_Crouch_Swing.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_idle_neutral" "engineer_animations_anims\a_PDA_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_idle_down_right" "engineer_animations_anims\a_PDA_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_down_center" "engineer_animations_anims\a_PDA_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_down_left" "engineer_animations_anims\a_PDA_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_right" "engineer_animations_anims\a_PDA_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_center" "engineer_animations_anims\a_PDA_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_mid_left" "engineer_animations_anims\a_PDA_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_right" "engineer_animations_anims\a_PDA_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_center" "engineer_animations_anims\a_PDA_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_up_left" "engineer_animations_anims\a_PDA_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_idle_straight_up" "engineer_animations_anims\a_PDA_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_neutral" "engineer_animations_anims\a_PDA_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_run_down_right" "engineer_animations_anims\a_PDA_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_down_center" "engineer_animations_anims\a_PDA_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_down_left" "engineer_animations_anims\a_PDA_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_right" "engineer_animations_anims\a_PDA_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_center" "engineer_animations_anims\a_PDA_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_mid_left" "engineer_animations_anims\a_PDA_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_right" "engineer_animations_anims\a_PDA_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_center" "engineer_animations_anims\a_PDA_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_up_left" "engineer_animations_anims\a_PDA_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_run_straight_up" "engineer_animations_anims\a_PDA_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_PDA_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_fire" "engineer_animations_anims\a_PDA_fire.smd" {
	fps 30
}
$animation "a_PDA_run_fire" "engineer_animations_anims\a_PDA_run_fire.smd" {
	fps 30
}
$animation "a_PDA_Crouch_fire" "engineer_animations_anims\a_PDA_Crouch_fire.smd" {
	fps 30
}
$animation "a_BUILDING_aimmatrix_idle_neutral" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_aimmatrix_idle_down_right" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_down_center" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_down_left" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_mid_right" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_mid_center" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_mid_left" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_up_right" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_up_center" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_up_left" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_idle_straight_up" "engineer_animations_anims\a_BUILDING_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_neutral" "engineer_animations_anims\a_BUILDING_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_aimmatrix_run_down_right" "engineer_animations_anims\a_BUILDING_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_down_center" "engineer_animations_anims\a_BUILDING_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_down_left" "engineer_animations_anims\a_BUILDING_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_mid_right" "engineer_animations_anims\a_BUILDING_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_mid_center" "engineer_animations_anims\a_BUILDING_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_mid_left" "engineer_animations_anims\a_BUILDING_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_up_right" "engineer_animations_anims\a_BUILDING_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_up_center" "engineer_animations_anims\a_BUILDING_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_up_left" "engineer_animations_anims\a_BUILDING_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_run_straight_up" "engineer_animations_anims\a_BUILDING_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_BUILDING_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "engineer_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_neutral" "engineer_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "engineer_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "engineer_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "engineer_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "engineer_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "engineer_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "engineer_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "engineer_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "engineer_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "engineer_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "engineer_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_neutral" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_idle_down_right" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_center" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_down_left" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_right" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_center" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_mid_left" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_right" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_center" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_up_left" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_idle_straight_up" "engineer_animations_anims\a_ITEM2_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_neutral" "engineer_animations_anims\a_ITEM2_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_run_down_right" "engineer_animations_anims\a_ITEM2_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_center" "engineer_animations_anims\a_ITEM2_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_down_left" "engineer_animations_anims\a_ITEM2_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_right" "engineer_animations_anims\a_ITEM2_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_center" "engineer_animations_anims\a_ITEM2_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_mid_left" "engineer_animations_anims\a_ITEM2_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_right" "engineer_animations_anims\a_ITEM2_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_center" "engineer_animations_anims\a_ITEM2_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_up_left" "engineer_animations_anims\a_ITEM2_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_run_straight_up" "engineer_animations_anims\a_ITEM2_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_ITEM2_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_swing" "engineer_animations_anims\a_ITEM2_swing.smd" {
	fps 30
}
$animation "a_ITEM2_crouch_swing" "engineer_animations_anims\a_ITEM2_crouch_swing.smd" {
	fps 30
}
$animation "a_ITEM2_swing_hard" "engineer_animations_anims\a_ITEM2_swing_hard.smd" {
	fps 30
}
$animation "a_ITEM2_crouch_swing_hard" "engineer_animations_anims\a_ITEM2_crouch_swing_hard.smd" {
	fps 30
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_neutral" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_down_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_down_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_down_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_mid_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_mid_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_mid_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_up_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_up_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_up_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_idle_straight_up" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_neutral" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_straight_up" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "engineer_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "engineer_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "engineer_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "engineer_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "engineer_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "engineer_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "engineer_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "engineer_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "engineer_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "engineer_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "engineer_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "engineer_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "engineer_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "engineer_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "engineer_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "engineer_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "engineer_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "engineer_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "engineer_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "engineer_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "engineer_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "engineer_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "engineer_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "engineer_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "engineer_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "engineer_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "engineer_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "engineer_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "engineer_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "engineer_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "engineer_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "engineer_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "engineer_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "engineer_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "engineer_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "engineer_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "engineer_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "engineer_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "engineer_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "engineer_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "engineer_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "engineer_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "engineer_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "engineer_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "engineer_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "engineer_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "engineer_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "engineer_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "engineer_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "engineer_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "engineer_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "engineer_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "engineer_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "engineer_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "engineer_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "engineer_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "engineer_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "engineer_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "engineer_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_ITEM2_aimmatrix_swim_neutral" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM2_aimmatrix_swim_down_right" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_center" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_down_left" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_right" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_center" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_mid_left" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_right" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_center" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_up_left" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM2_aimmatrix_swim_straight_up" "engineer_animations_anims\a_ITEM2_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM2" "engineer_animations_anims\a_swimCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM2" "engineer_animations_anims\a_swimS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM2" "engineer_animations_anims\a_swimSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM2" "engineer_animations_anims\a_swimE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM2" "engineer_animations_anims\a_swimNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM2" "engineer_animations_anims\a_swimN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM2" "engineer_animations_anims\a_swimNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM2" "engineer_animations_anims\a_swimW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM2" "engineer_animations_anims\a_swimSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_PDA_aimmatrix_swim_neutral" "engineer_animations_anims\a_PDA_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PDA_aimmatrix_swim_down_right" "engineer_animations_anims\a_PDA_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_down_center" "engineer_animations_anims\a_PDA_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_down_left" "engineer_animations_anims\a_PDA_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_right" "engineer_animations_anims\a_PDA_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_center" "engineer_animations_anims\a_PDA_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_mid_left" "engineer_animations_anims\a_PDA_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_right" "engineer_animations_anims\a_PDA_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_center" "engineer_animations_anims\a_PDA_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_up_left" "engineer_animations_anims\a_PDA_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PDA_aimmatrix_swim_straight_up" "engineer_animations_anims\a_PDA_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PDA" "engineer_animations_anims\a_swimCenter_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimS_PDA" "engineer_animations_anims\a_swimS_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PDA" "engineer_animations_anims\a_swimSE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimE_PDA" "engineer_animations_anims\a_swimE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PDA" "engineer_animations_anims\a_swimNE_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimN_PDA" "engineer_animations_anims\a_swimN_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PDA" "engineer_animations_anims\a_swimNW_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimW_PDA" "engineer_animations_anims\a_swimW_PDA.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PDA" "engineer_animations_anims\a_swimSW_PDA.smd" {
	fps 30
	loop
}
$animation "a_BUILDING_aimmatrix_swim_neutral" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_aimmatrix_swim_down_right" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_down_center" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_down_left" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_mid_right" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_mid_center" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_mid_left" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_up_right" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_up_center" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_up_left" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_aimmatrix_swim_straight_up" "engineer_animations_anims\a_BUILDING_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_BUILDING" "engineer_animations_anims\a_swimCenter_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimS_BUILDING" "engineer_animations_anims\a_swimS_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimSE_BUILDING" "engineer_animations_anims\a_swimSE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimE_BUILDING" "engineer_animations_anims\a_swimE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimNE_BUILDING" "engineer_animations_anims\a_swimNE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimN_BUILDING" "engineer_animations_anims\a_swimN_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimNW_BUILDING" "engineer_animations_anims\a_swimNW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimW_BUILDING" "engineer_animations_anims\a_swimW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_swimSW_BUILDING" "engineer_animations_anims\a_swimSW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_neutral" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_down_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_down_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_down_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_mid_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_mid_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_mid_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_up_right" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_up_center" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_up_left" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_BUILDING_DEPLOYED_aimmatrix_swim_straight_up" "engineer_animations_anims\a_BUILDING_DEPLOYED_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimCenter_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimS_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimS_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimSE_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimSE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimE_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimNE_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimNE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimN_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimN_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimNW_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimNW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimW_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimSW_BUILDING_DEPLOYED" "engineer_animations_anims\a_swimSW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "engineer_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "engineer_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "engineer_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "engineer_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "engineer_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "engineer_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "engineer_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "engineer_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "engineer_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "engineer_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "engineer_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "engineer_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "engineer_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "engineer_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "engineer_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "engineer_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "engineer_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "engineer_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "engineer_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "engineer_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "engineer_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "engineer_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "engineer_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "engineer_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "engineer_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "engineer_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "engineer_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "engineer_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "engineer_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "engineer_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "engineer_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "engineer_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "engineer_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "engineer_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "engineer_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "engineer_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_forward_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_forward_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_forward_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_forward_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_neutral" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_reverse_down_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_down_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_down_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_mid_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_mid_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_mid_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_up_right" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_up_center" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_up_left" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_reverse_straight_up" "engineer_animations_anims\a_SECONDARY_aimmatrix_reverse_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_blend_crouchN_SECONDARY" "engineer_animations_anims\a_blend_crouchN_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_SECONDARY" "engineer_animations_anims\a_crouch_walkCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_SECONDARY" "engineer_animations_anims\a_crouch_walkS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_SECONDARY" "engineer_animations_anims\a_crouch_walkSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_SECONDARY" "engineer_animations_anims\a_crouch_walkE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_SECONDARY" "engineer_animations_anims\a_crouch_walkNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_SECONDARY" "engineer_animations_anims\a_crouch_walkN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_SECONDARY" "engineer_animations_anims\a_crouch_walkNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_SECONDARY" "engineer_animations_anims\a_crouch_walkW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_SECONDARY" "engineer_animations_anims\a_crouch_walkSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "engineer_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "engineer_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "engineer_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "engineer_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "engineer_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "engineer_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "engineer_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "engineer_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "engineer_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "engineer_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "engineer_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "engineer_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "engineer_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "engineer_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "engineer_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "engineer_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "engineer_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "engineer_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "engineer_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "engineer_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "engineer_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "engineer_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "engineer_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "engineer_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "engineer_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "engineer_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "engineer_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "engineer_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM1" "engineer_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "engineer_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "engineer_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "engineer_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "engineer_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "engineer_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "engineer_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "engineer_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "engineer_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "engineer_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runCenter_ITEM2" "engineer_animations_anims\a_runCenter_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM2" "engineer_animations_anims\a_runS_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM2" "engineer_animations_anims\a_runSE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM2" "engineer_animations_anims\a_runE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM2" "engineer_animations_anims\a_runNE_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM2" "engineer_animations_anims\a_runN_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM2" "engineer_animations_anims\a_runNW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM2" "engineer_animations_anims\a_runW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM2" "engineer_animations_anims\a_runSW_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM2" "engineer_animations_anims\a_blend_crouchN_crouch_walk_ITEM2.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkS_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkN_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM2" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_ITEM2.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PDA" "engineer_animations_anims\a_runCenter_PDA.smd" {
	fps 30
	loop
}
$animation "a_runS_PDA" "engineer_animations_anims\a_runS_PDA.smd" {
	fps 30
	loop
}
$animation "a_runSE_PDA" "engineer_animations_anims\a_runSE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runE_PDA" "engineer_animations_anims\a_runE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runNE_PDA" "engineer_animations_anims\a_runNE_PDA.smd" {
	fps 30
	loop
}
$animation "a_runN_PDA" "engineer_animations_anims\a_runN_PDA.smd" {
	fps 30
	loop
}
$animation "a_runNW_PDA" "engineer_animations_anims\a_runNW_PDA.smd" {
	fps 30
	loop
}
$animation "a_runW_PDA" "engineer_animations_anims\a_runW_PDA.smd" {
	fps 30
	loop
}
$animation "a_runSW_PDA" "engineer_animations_anims\a_runSW_PDA.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_PDA" "engineer_animations_anims\a_blend_crouchN_crouch_walk_PDA.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkS_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkN_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_PDA" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_PDA.smd" {
	fps 30
	loop
}
$animation "a_runCenter_BUILDING" "engineer_animations_anims\a_runCenter_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runS_BUILDING" "engineer_animations_anims\a_runS_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runSE_BUILDING" "engineer_animations_anims\a_runSE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runE_BUILDING" "engineer_animations_anims\a_runE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runNE_BUILDING" "engineer_animations_anims\a_runNE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runN_BUILDING" "engineer_animations_anims\a_runN_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runNW_BUILDING" "engineer_animations_anims\a_runNW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runW_BUILDING" "engineer_animations_anims\a_runW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runSW_BUILDING" "engineer_animations_anims\a_runSW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_BUILDING" "engineer_animations_anims\a_crouch_walkCenter_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_BUILDING" "engineer_animations_anims\a_crouch_walkS_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_BUILDING" "engineer_animations_anims\a_crouch_walkSE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_BUILDING" "engineer_animations_anims\a_crouch_walkE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_BUILDING" "engineer_animations_anims\a_crouch_walkNE_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_BUILDING" "engineer_animations_anims\a_crouch_walkN_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_BUILDING" "engineer_animations_anims\a_crouch_walkNW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_BUILDING" "engineer_animations_anims\a_crouch_walkW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_BUILDING" "engineer_animations_anims\a_crouch_walkSW_BUILDING.smd" {
	fps 30
	loop
}
$animation "a_runCenter_BUILDING_DEPLOYED" "engineer_animations_anims\a_runCenter_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runS_BUILDING_DEPLOYED" "engineer_animations_anims\a_runS_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runSE_BUILDING_DEPLOYED" "engineer_animations_anims\a_runSE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runE_BUILDING_DEPLOYED" "engineer_animations_anims\a_runE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runNE_BUILDING_DEPLOYED" "engineer_animations_anims\a_runNE_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runN_BUILDING_DEPLOYED" "engineer_animations_anims\a_runN_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runNW_BUILDING_DEPLOYED" "engineer_animations_anims\a_runNW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runW_BUILDING_DEPLOYED" "engineer_animations_anims\a_runW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_runSW_BUILDING_DEPLOYED" "engineer_animations_anims\a_runSW_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_blend_crouchN_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkCenter_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkS_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkSE_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkE_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkNE_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkN_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkNW_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkW_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_BUILDING_DEPLOYED" "engineer_animations_anims\a_crouch_walkSW_crouch_walk_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_aimmatrix_airwalk_neutral" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_right" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_center" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_left" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_straight_up" "engineer_animations_anims\a_PRIMARY_aimmatrix_airwalk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_stun_startpose" "engineer_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "engineer_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "engineer_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "engineer_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_PRIMARY" "engineer_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY" "engineer_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "engineer_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "ReloadStand_PRIMARY" "engineer_animations_anims\ReloadStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
}

$sequence "ReloadCrouch_PRIMARY" "engineer_animations_anims\ReloadCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
}

$sequence "ReloadSwim_PRIMARY" "engineer_animations_anims\ReloadSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
}

$sequence "a_PRIMARY_reload" "engineer_animations_anims\a_PRIMARY_reload.smd" {
	fps 30
}

$sequence "a_PRIMARY_reload_loop" "engineer_animations_anims\a_PRIMARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP" 2
	// delta
}

$sequence "b_PRIMARY_reload_loop" "engineer_animations_anims\b_PRIMARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP" 1
	// delta
}

$sequence "PRIMARY_reload_end" "engineer_animations_anims\PRIMARY_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END" 1
	// delta
	fadeout 1
}

$sequence "a_PRIMARYcrouch_reload" "engineer_animations_anims\a_PRIMARYcrouch_reload.smd" {
	fps 30
}

$sequence "reloadcrouch_PRIMARY_end" "engineer_animations_anims\reloadcrouch_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END" 1
	// delta
	fadeout 0.7
}

$sequence "PRIMARY_reloadcrouch" "engineer_animations_anims\PRIMARY_reloadcrouch.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 100
	// delta
}

$sequence "a_PRIMARY_reloadcrouch_loop" "engineer_animations_anims\a_PRIMARY_reloadcrouch_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP" 2
	// delta
}

$sequence "b_PRIMARY_reloadcrouch_loop" "engineer_animations_anims\b_PRIMARY_reloadcrouch_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP" 1
	// delta
}

$sequence "a_PRIMARY_reload_airwalk" "engineer_animations_anims\a_PRIMARY_reload_airwalk.smd" {
	fps 30
}

$sequence "layer_reload_arms_PRIMARY" "engineer_animations_anims\layer_reload_arms_PRIMARY.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_airwalk" "engineer_animations_anims\PRIMARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY"
}

$sequence "layer_reload_arms_PRIMARY_loop" "engineer_animations_anims\layer_reload_arms_PRIMARY_loop.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_airwalk_loop" "engineer_animations_anims\PRIMARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY_loop"
}

$sequence "layer_reload_arms_PRIMARY_end" "engineer_animations_anims\layer_reload_arms_PRIMARY_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_airwalk_end" "engineer_animations_anims\PRIMARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY_end"
	fadeout 0.7
}

$sequence "a_PRIMARY_reload_swim" "engineer_animations_anims\a_PRIMARY_reload_swim.smd" {
	fps 30
}

$sequence "layer_reload_arms_PRIMARY_swim" "engineer_animations_anims\layer_reload_arms_PRIMARY_swim.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_swim" "engineer_animations_anims\PRIMARY_reload_swim.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY_swim"
}

$sequence "layer_reload_arms_PRIMARY_loop_swim" "engineer_animations_anims\layer_reload_arms_PRIMARY_loop_swim.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_swim_loop" "engineer_animations_anims\PRIMARY_reload_swim_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY_loop_swim"
}

$sequence "layer_reload_arms_PRIMARY_end_swim" "engineer_animations_anims\layer_reload_arms_PRIMARY_end_swim.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_reload_swim_end" "engineer_animations_anims\PRIMARY_reload_swim_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_END" 1
	// delta
	// addlayer "layer_reload_arms_PRIMARY_end_swim"
	fadeout 0.7
}

$sequence "layer_placeSapper_ArmL" "engineer_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "engineer_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "engineer_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "engineer_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "engineer_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "layer_reload_standing_arms_SECONDARY" "engineer_animations_anims\layer_reload_standing_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_airwalk_arms_SECONDARY" "engineer_animations_anims\layer_reload_airwalk_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "layer_reload_crouch_arms_SECONDARY" "engineer_animations_anims\layer_reload_crouch_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY" "engineer_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "ReloadAirwalk_SECONDARY" "engineer_animations_anims\ReloadAirwalk_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_airwalk_arms_SECONDARY"
}

$sequence "ReloadCrouch_SECONDARY" "engineer_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	// addlayer "layer_reload_crouch_arms_SECONDARY"
}

$sequence "ReloadSwim_SECONDARY" "engineer_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_arms_SECONDARY"
}

$sequence "xReloadPrim" "engineer_animations_anims\xReloadPrim.smd" {
	fps 30
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_walk" {
	"a_MELEE_aimmatrix_walk_straight_up"
	"a_MELEE_aimmatrix_walk_straight_up"
	"a_MELEE_aimmatrix_walk_straight_up"
	"a_MELEE_aimmatrix_walk_up_right"
	"a_MELEE_aimmatrix_walk_up_center"
	"a_MELEE_aimmatrix_walk_up_left"
	"a_MELEE_aimmatrix_walk_mid_right"
	"a_MELEE_aimmatrix_walk_mid_center"
	"a_MELEE_aimmatrix_walk_mid_left"
	"a_MELEE_aimmatrix_walk_down_right"
	"a_MELEE_aimmatrix_walk_down_center"
	"a_MELEE_aimmatrix_walk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
}

$sequence "MELEE_ALLCLASS_aimmatrix_walk" {
	"a_MELEE_ALLCLASS_aimmatrix_walk_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_walk_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_walk_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_walk_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_walk_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_walk_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_walk_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_walk_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_walk_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_walk_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_walk_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_walk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
}

$sequence "armslayer_melee_swing" "engineer_animations_anims\armslayer_melee_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swing" "engineer_animations_anims\bodylayer_Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swing" "engineer_animations_anims\Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	blendlayer "bodylayer_Melee_Swing" 0 0.041667 0.833333 1 spline
	blendlayer "armslayer_melee_swing" 0 0.208333 0.833333 1 spline
}

$sequence "armslayer_melee_Crouch_swing" "engineer_animations_anims\armslayer_melee_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Crouch_Swing" "engineer_animations_anims\bodylayer_Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Crouch_Swing" "engineer_animations_anims\Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// addlayer "bodylayer_Melee_Crouch_Swing"
	// addlayer "armslayer_melee_Crouch_swing"
}

$sequence "armslayer_melee_allclass_swing" "engineer_animations_anims\armslayer_melee_allclass_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Swing" "engineer_animations_anims\bodylayer_Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Swing" "engineer_animations_anims\Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	blendlayer "bodylayer_Melee_allclass_Swing" 0 0.041667 0.833333 1 spline
	blendlayer "armslayer_melee_allclass_swing" 0 0.208333 0.833333 1 spline
	// addlayer "r_handposes"
}

$sequence "armslayer_melee_allclass_Crouch_swing" "engineer_animations_anims\armslayer_melee_allclass_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Crouch_Swing" "engineer_animations_anims\bodylayer_Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Crouch_Swing" "engineer_animations_anims\Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_Melee_allclass_Crouch_Swing"
	// addlayer "armslayer_melee_allclass_Crouch_swing"
	// addlayer "r_handposes"
}

$sequence "AttackSwim_MELEE" "engineer_animations_anims\AttackSwim_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// delta
}

$sequence "AttackSwim_MELEE_ALLCLASS" "engineer_animations_anims\AttackSwim_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "melee_raw" "engineer_animations_anims\melee_raw.smd" {
	fps 30
}

$sequence "melee_crouchraw" "engineer_animations_anims\melee_crouchraw.smd" {
	fps 30
}

$sequence "PDA_aimmatrix_idle" {
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_straight_up"
	"a_PDA_aimmatrix_idle_up_right"
	"a_PDA_aimmatrix_idle_up_center"
	"a_PDA_aimmatrix_idle_up_left"
	"a_PDA_aimmatrix_idle_mid_right"
	"a_PDA_aimmatrix_idle_mid_center"
	"a_PDA_aimmatrix_idle_mid_left"
	"a_PDA_aimmatrix_idle_down_right"
	"a_PDA_aimmatrix_idle_down_center"
	"a_PDA_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PDA_aimmatrix_run" {
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_straight_up"
	"a_PDA_aimmatrix_run_up_right"
	"a_PDA_aimmatrix_run_up_center"
	"a_PDA_aimmatrix_run_up_left"
	"a_PDA_aimmatrix_run_mid_right"
	"a_PDA_aimmatrix_run_mid_center"
	"a_PDA_aimmatrix_run_mid_left"
	"a_PDA_aimmatrix_run_down_right"
	"a_PDA_aimmatrix_run_down_center"
	"a_PDA_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PDA_aimmatrix_crouch_idle" {
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_straight_up"
	"a_PDA_aimmatrix_crouch_idle_up_right"
	"a_PDA_aimmatrix_crouch_idle_up_center"
	"a_PDA_aimmatrix_crouch_idle_up_left"
	"a_PDA_aimmatrix_crouch_idle_mid_right"
	"a_PDA_aimmatrix_crouch_idle_mid_center"
	"a_PDA_aimmatrix_crouch_idle_mid_left"
	"a_PDA_aimmatrix_crouch_idle_down_right"
	"a_PDA_aimmatrix_crouch_idle_down_center"
	"a_PDA_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_PDA_fire" "engineer_animations_anims\armslayer_PDA_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_fire" "engineer_animations_anims\bodylayer_PDA_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_fire" "engineer_animations_anims\PDA_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PDA" 1
	// addlayer "bodylayer_PDA_fire"
	// addlayer "armslayer_PDA_fire"
}

$sequence "armslayer_PDA_run_fire" "engineer_animations_anims\armslayer_PDA_run_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_run_fire" "engineer_animations_anims\bodylayer_PDA_run_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_run_fire" "engineer_animations_anims\PDA_run_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_RUN_PDA" 1
	// addlayer "bodylayer_PDA_run_fire"
	// addlayer "armslayer_PDA_run_fire"
}

$sequence "armslayer_PDA_Crouch_fire" "engineer_animations_anims\armslayer_PDA_Crouch_fire.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_PDA_Crouch_fire" "engineer_animations_anims\bodylayer_PDA_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "PDA_Crouch_fire" "engineer_animations_anims\PDA_Crouch_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PDA" 1
	// addlayer "bodylayer_PDA_Crouch_fire"
	// addlayer "armslayer_PDA_Crouch_fire"
}

$sequence "layer_fire_standing_arms_PDA" "engineer_animations_anims\layer_fire_standing_arms_PDA.smd" {
	fps 30
	hidden
}

$sequence "AttackStand_PDA" "engineer_animations_anims\AttackStand_PDA.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PDA" 1
	// delta
}

$sequence "AttackCrouch_PDA" "engineer_animations_anims\AttackCrouch_PDA.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PDA" 1
	// delta
}

$sequence "AttackSwim_PDA" "engineer_animations_anims\AttackSwim_PDA.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PDA" 1
	// delta
}

$sequence "BUILDING_aimmatrix_idle" {
	"a_BUILDING_aimmatrix_idle_straight_up"
	"a_BUILDING_aimmatrix_idle_straight_up"
	"a_BUILDING_aimmatrix_idle_straight_up"
	"a_BUILDING_aimmatrix_idle_up_right"
	"a_BUILDING_aimmatrix_idle_up_center"
	"a_BUILDING_aimmatrix_idle_up_left"
	"a_BUILDING_aimmatrix_idle_mid_right"
	"a_BUILDING_aimmatrix_idle_mid_center"
	"a_BUILDING_aimmatrix_idle_mid_left"
	"a_BUILDING_aimmatrix_idle_down_right"
	"a_BUILDING_aimmatrix_idle_down_center"
	"a_BUILDING_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "BUILDING_aimmatrix_run" {
	"a_BUILDING_aimmatrix_run_straight_up"
	"a_BUILDING_aimmatrix_run_straight_up"
	"a_BUILDING_aimmatrix_run_straight_up"
	"a_BUILDING_aimmatrix_run_up_right"
	"a_BUILDING_aimmatrix_run_up_center"
	"a_BUILDING_aimmatrix_run_up_left"
	"a_BUILDING_aimmatrix_run_mid_right"
	"a_BUILDING_aimmatrix_run_mid_center"
	"a_BUILDING_aimmatrix_run_mid_left"
	"a_BUILDING_aimmatrix_run_down_right"
	"a_BUILDING_aimmatrix_run_down_center"
	"a_BUILDING_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "BUILDING_aimmatrix_crouch_idle" {
	"a_BUILDING_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_aimmatrix_crouch_idle_up_right"
	"a_BUILDING_aimmatrix_crouch_idle_up_center"
	"a_BUILDING_aimmatrix_crouch_idle_up_left"
	"a_BUILDING_aimmatrix_crouch_idle_mid_right"
	"a_BUILDING_aimmatrix_crouch_idle_mid_center"
	"a_BUILDING_aimmatrix_crouch_idle_mid_left"
	"a_BUILDING_aimmatrix_crouch_idle_down_right"
	"a_BUILDING_aimmatrix_crouch_idle_down_center"
	"a_BUILDING_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_idle" {
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_straight_up"
	"a_ITEM2_aimmatrix_idle_up_right"
	"a_ITEM2_aimmatrix_idle_up_center"
	"a_ITEM2_aimmatrix_idle_up_left"
	"a_ITEM2_aimmatrix_idle_mid_right"
	"a_ITEM2_aimmatrix_idle_mid_center"
	"a_ITEM2_aimmatrix_idle_mid_left"
	"a_ITEM2_aimmatrix_idle_down_right"
	"a_ITEM2_aimmatrix_idle_down_center"
	"a_ITEM2_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_run" {
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_straight_up"
	"a_ITEM2_aimmatrix_run_up_right"
	"a_ITEM2_aimmatrix_run_up_center"
	"a_ITEM2_aimmatrix_run_up_left"
	"a_ITEM2_aimmatrix_run_mid_right"
	"a_ITEM2_aimmatrix_run_mid_center"
	"a_ITEM2_aimmatrix_run_mid_left"
	"a_ITEM2_aimmatrix_run_down_right"
	"a_ITEM2_aimmatrix_run_down_center"
	"a_ITEM2_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM2_aimmatrix_crouch_idle" {
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_straight_up"
	"a_ITEM2_aimmatrix_crouch_idle_up_right"
	"a_ITEM2_aimmatrix_crouch_idle_up_center"
	"a_ITEM2_aimmatrix_crouch_idle_up_left"
	"a_ITEM2_aimmatrix_crouch_idle_mid_right"
	"a_ITEM2_aimmatrix_crouch_idle_mid_center"
	"a_ITEM2_aimmatrix_crouch_idle_mid_left"
	"a_ITEM2_aimmatrix_crouch_idle_down_right"
	"a_ITEM2_aimmatrix_crouch_idle_down_center"
	"a_ITEM2_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "armslayer_ITEM2_swing" "engineer_animations_anims\armslayer_ITEM2_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM2_swing" "engineer_animations_anims\bodylayer_ITEM2_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM2_swing" "engineer_animations_anims\ITEM2_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM2" 1
	blendlayer "bodylayer_ITEM2_swing" 0 0.038462 0.769231 1 spline
	blendlayer "armslayer_ITEM2_swing" 0 0.192308 0.769231 1 spline
}

$sequence "armslayer_ITEM2_crouch_swing" "engineer_animations_anims\armslayer_ITEM2_crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM2_crouch_swing" "engineer_animations_anims\bodylayer_ITEM2_crouch_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM2_crouch_swing" "engineer_animations_anims\ITEM2_crouch_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM2" 1
	// addlayer "bodylayer_ITEM2_crouch_swing"
	// addlayer "armslayer_ITEM2_crouch_swing"
}

$sequence "AttackSwim_ITEM2" "engineer_animations_anims\AttackSwim_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_ITEM2" 1
	// delta
}

$sequence "armslayer_ITEM2_swing_hard" "engineer_animations_anims\armslayer_ITEM2_swing_hard.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM2_swing_hard" "engineer_animations_anims\bodylayer_ITEM2_swing_hard.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM2_swing_hard" "engineer_animations_anims\ITEM2_swing_hard.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_HARD_ITEM2" 1
	blendlayer "bodylayer_ITEM2_swing_hard" 0 0.037037 0.777778 1 spline
	blendlayer "armslayer_ITEM2_swing_hard" 0 0.185185 0.777778 1 spline
}

$sequence "armslayer_ITEM2_crouch_swing_hard" "engineer_animations_anims\armslayer_ITEM2_crouch_swing_hard.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM2_crouch_swing_hard" "engineer_animations_anims\bodylayer_ITEM2_crouch_swing_hard.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "ITEM2_Crouch_Swing_hard" "engineer_animations_anims\ITEM2_Crouch_Swing_hard.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_HARD_ITEM2" 1
	// addlayer "bodylayer_ITEM2_crouch_swing_hard"
	// addlayer "armslayer_ITEM2_crouch_swing_hard"
}

$sequence "AttackSwim_ITEM2_hard" "engineer_animations_anims\AttackSwim_ITEM2_hard.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_HARD_ITEM2" 1
	// delta
}

$sequence "layer_gesture_primary_go_armL" "engineer_animations_anims\layer_gesture_primary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_go" "engineer_animations_anims\gesture_primary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_go_armL"
}

$sequence "layer_gesture_primary_cheer_armL" "engineer_animations_anims\layer_gesture_primary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_cheer" "engineer_animations_anims\gesture_primary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_cheer_armL"
}

$sequence "layer_gesture_primary_help_armL" "engineer_animations_anims\layer_gesture_primary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_help" "engineer_animations_anims\gesture_primary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_help_armL"
}

$sequence "layer_gesture_secondary_go_armL" "engineer_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "engineer_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_go_armL"
}

$sequence "layer_gesture_secondary_cheer_armL" "engineer_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "engineer_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_help_armL" "engineer_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "engineer_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_melee_go_armL" "engineer_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "engineer_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_go_armL"
}

$sequence "layer_gesture_melee_cheer_armL" "engineer_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "engineer_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_cheer_armL"
}

$sequence "layer_gesture_melee_help_armL" "engineer_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "engineer_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_help_armL"
}

$sequence "layer_gesture_PDA_go_armL" "engineer_animations_anims\layer_gesture_PDA_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_go" "engineer_animations_anims\gesture_PDA_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PDA" 1
	// delta
	// addlayer "layer_gesture_PDA_go_armL"
}

$sequence "layer_gesture_PDA_cheer_armL" "engineer_animations_anims\layer_gesture_PDA_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_cheer" "engineer_animations_anims\gesture_PDA_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PDA" 1
	// delta
	// addlayer "layer_gesture_PDA_cheer_armL"
}

$sequence "layer_gesture_PDA_help_armL" "engineer_animations_anims\layer_gesture_PDA_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PDA_help" "engineer_animations_anims\gesture_PDA_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PDA" 1
	// delta
	// addlayer "layer_gesture_PDA_help_armL"
}

$sequence "BUILDING_DEPLOYED_aimmatrix_idle" {
	"a_BUILDING_DEPLOYED_aimmatrix_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_up_right"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_up_center"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_up_left"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_mid_right"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_mid_center"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_mid_left"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_down_right"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_down_center"
	"a_BUILDING_DEPLOYED_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "BUILDING_DEPLOYED_aimmatrix_crouch_idle" {
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_right"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_center"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_up_left"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_right"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_center"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_mid_left"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_right"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_center"
	"a_BUILDING_DEPLOYED_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "stand_PRIMARY" "engineer_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "engineer_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "engineer_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "engineer_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "engineer_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "engineer_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "stand_ITEM2" "engineer_animations_anims\stand_ITEM2.smd" {
	fps 30
	"ACT_MP_STAND_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "stand_PDA" "engineer_animations_anims\stand_PDA.smd" {
	fps 30
	"ACT_MP_STAND_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_idle"
}

$sequence "stand_BUILDING" "engineer_animations_anims\stand_BUILDING.smd" {
	fps 30
	"ACT_MP_STAND_BUILDING" 1
	loop
	// addlayer "BUILDING_aimmatrix_idle"
}

$sequence "stand_BUILDING_DEPLOYED" "engineer_animations_anims\stand_BUILDING_DEPLOYED.smd" {
	fps 30
	"ACT_MP_STAND_BUILDING_DEPLOYED" 1
	loop
	// addlayer "BUILDING_DEPLOYED_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "engineer_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "engineer_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "engineer_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "engineer_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "engineer_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "engineer_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "crouch_ITEM2" "engineer_animations_anims\crouch_ITEM2.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_crouch_idle"
}

$sequence "crouch_PDA" "engineer_animations_anims\crouch_PDA.smd" {
	fps 30
	"ACT_MP_CROUCH_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_crouch_idle"
}

$sequence "crouch_BUILDING" "engineer_animations_anims\crouch_BUILDING.smd" {
	fps 30
	"ACT_MP_CROUCH_BUILDING" 1
	loop
	// addlayer "BUILDING_aimmatrix_crouch_idle"
}

$sequence "crouch_BUILDING_DEPLOYED" "engineer_animations_anims\crouch_BUILDING_DEPLOYED.smd" {
	fps 30
	"ACT_MP_CROUCH_BUILDING_DEPLOYED" 1
	loop
	// addlayer "BUILDING_DEPLOYED_aimmatrix_crouch_idle"
}

$sequence "a_jumpstart_PRIMARY" "engineer_animations_anims\a_jumpstart_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
}

$sequence "a_jumpfloat_PRIMARY" "engineer_animations_anims\a_jumpfloat_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
}

$sequence "jumplandPose_PRIMARY" "engineer_animations_anims\jumplandPose_PRIMARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_PRIMARY" "engineer_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "a_jumpstart_SECONDARY" "engineer_animations_anims\a_jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "a_jumpfloat_SECONDARY" "engineer_animations_anims\a_jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumplandPose_SECONDARY" "engineer_animations_anims\jumplandPose_SECONDARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_SECONDARY" "engineer_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "engineer_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "engineer_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "engineer_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "engineer_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "engineer_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "engineer_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "engineer_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "engineer_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "engineer_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "engineer_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "engineer_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "engineer_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "a_jumpstart_ITEM1" "engineer_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "a_jumpfloat_ITEM1" "engineer_animations_anims\a_jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumplandPose_ITEM1" "engineer_animations_anims\jumplandPose_ITEM1.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM1" "engineer_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "a_jumpstart_ITEM2" "engineer_animations_anims\a_jumpstart_ITEM2.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM2" 1
}

$sequence "a_jumpfloat_ITEM2" "engineer_animations_anims\a_jumpfloat_ITEM2.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM2" 1
	loop
}

$sequence "jumplandPose_ITEM2" "engineer_animations_anims\jumplandPose_ITEM2.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM2" "engineer_animations_anims\jumpland_ITEM2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM2" 1
	// delta
}

$sequence "a_jumpstart_PDA" "engineer_animations_anims\a_jumpstart_PDA.smd" {
	fps 30
	"ACT_MP_JUMP_START_PDA" 1
}

$sequence "a_jumpfloat_PDA" "engineer_animations_anims\a_jumpfloat_PDA.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PDA" 1
	loop
}

$sequence "jumplandPose_PDA" "engineer_animations_anims\jumplandPose_PDA.smd" {
	fps 30
	loop
}

$sequence "jumpland_PDA" "engineer_animations_anims\jumpland_PDA.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PDA" 1
	// delta
}

$sequence "a_jumpstart_BUILDING" "engineer_animations_anims\a_jumpstart_BUILDING.smd" {
	fps 30
	"ACT_MP_JUMP_START_BUILDING" 1
}

$sequence "a_jumpfloat_BUILDING" "engineer_animations_anims\a_jumpfloat_BUILDING.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_BUILDING" 1
	loop
}

$sequence "jumplandPose_BUILDING" "engineer_animations_anims\jumplandPose_BUILDING.smd" {
	fps 30
	loop
}

$sequence "jumpland_BUILDING" "engineer_animations_anims\jumpland_BUILDING.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_BUILDING" 1
	// delta
}

$sequence "a_jumpstart_BUILDING_DEPLOYED" "engineer_animations_anims\a_jumpstart_BUILDING_DEPLOYED.smd" {
	fps 30
	"ACT_MP_JUMP_START_BUILDING_DEPLOYED" 1
}

$sequence "a_jumpfloat_BUILDING_DEPLOYED" "engineer_animations_anims\a_jumpfloat_BUILDING_DEPLOYED.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_BUILDING_DEPLOYED" 1
	loop
}

$sequence "jumplandPose_BUILDING_DEPLOYED" "engineer_animations_anims\jumplandPose_BUILDING_DEPLOYED.smd" {
	fps 30
	loop
}

$sequence "jumpland_BUILDING_DEPLOYED" "engineer_animations_anims\jumpland_BUILDING_DEPLOYED.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_BUILDING_DEPLOYED" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "ITEM2_aimmatrix_swim" {
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_straight_up"
	"a_ITEM2_aimmatrix_swim_up_right"
	"a_ITEM2_aimmatrix_swim_up_center"
	"a_ITEM2_aimmatrix_swim_up_left"
	"a_ITEM2_aimmatrix_swim_mid_right"
	"a_ITEM2_aimmatrix_swim_mid_center"
	"a_ITEM2_aimmatrix_swim_mid_left"
	"a_ITEM2_aimmatrix_swim_down_right"
	"a_ITEM2_aimmatrix_swim_down_center"
	"a_ITEM2_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM2" {
	"a_swimCenter_ITEM2"
	fps 30
	loop
}

$sequence "swim_ITEM2" {
	"a_swimSW_ITEM2"
	"a_swimS_ITEM2"
	"a_swimSE_ITEM2"
	"a_swimW_ITEM2"
	"a_swimCenter_ITEM2"
	"a_swimE_ITEM2"
	"a_swimNW_ITEM2"
	"a_swimN_ITEM2"
	"a_swimNE_ITEM2"
	fps 30
	"ACT_MP_SWIM_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_swim"
}

$sequence "PDA_aimmatrix_swim" {
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_straight_up"
	"a_PDA_aimmatrix_swim_up_right"
	"a_PDA_aimmatrix_swim_up_center"
	"a_PDA_aimmatrix_swim_up_left"
	"a_PDA_aimmatrix_swim_mid_right"
	"a_PDA_aimmatrix_swim_mid_center"
	"a_PDA_aimmatrix_swim_mid_left"
	"a_PDA_aimmatrix_swim_down_right"
	"a_PDA_aimmatrix_swim_down_center"
	"a_PDA_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PDA" {
	"a_swimCenter_PDA"
	fps 30
	loop
}

$sequence "swim_PDA" {
	"a_swimSW_PDA"
	"a_swimS_PDA"
	"a_swimSE_PDA"
	"a_swimW_PDA"
	"a_swimCenter_PDA"
	"a_swimE_PDA"
	"a_swimNW_PDA"
	"a_swimN_PDA"
	"a_swimNE_PDA"
	fps 30
	"ACT_MP_SWIM_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_swim"
}

$sequence "BUILDING_aimmatrix_swim" {
	"a_BUILDING_aimmatrix_swim_straight_up"
	"a_BUILDING_aimmatrix_swim_straight_up"
	"a_BUILDING_aimmatrix_swim_straight_up"
	"a_BUILDING_aimmatrix_swim_up_right"
	"a_BUILDING_aimmatrix_swim_up_center"
	"a_BUILDING_aimmatrix_swim_up_left"
	"a_BUILDING_aimmatrix_swim_mid_right"
	"a_BUILDING_aimmatrix_swim_mid_center"
	"a_BUILDING_aimmatrix_swim_mid_left"
	"a_BUILDING_aimmatrix_swim_down_right"
	"a_BUILDING_aimmatrix_swim_down_center"
	"a_BUILDING_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_BUILDING" {
	"a_swimCenter_BUILDING"
	fps 30
	loop
}

$sequence "swim_BUILDING" {
	"a_swimSW_BUILDING"
	"a_swimS_BUILDING"
	"a_swimSE_BUILDING"
	"a_swimW_BUILDING"
	"a_swimCenter_BUILDING"
	"a_swimE_BUILDING"
	"a_swimNW_BUILDING"
	"a_swimN_BUILDING"
	"a_swimNE_BUILDING"
	fps 30
	"ACT_MP_SWIM_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_aimmatrix_swim"
}

$sequence "BUILDING_DEPLOYED_aimmatrix_swim" {
	"a_BUILDING_DEPLOYED_aimmatrix_swim_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_straight_up"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_up_right"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_up_center"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_up_left"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_mid_right"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_mid_center"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_mid_left"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_down_right"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_down_center"
	"a_BUILDING_DEPLOYED_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_BUILDING_DEPLOYED" {
	"a_swimCenter_BUILDING_DEPLOYED"
	fps 30
	loop
}

$sequence "swim_BUILDING_DEPLOYED" {
	"a_swimSW_BUILDING_DEPLOYED"
	"a_swimS_BUILDING_DEPLOYED"
	"a_swimSE_BUILDING_DEPLOYED"
	"a_swimW_BUILDING_DEPLOYED"
	"a_swimCenter_BUILDING_DEPLOYED"
	"a_swimE_BUILDING_DEPLOYED"
	"a_swimNW_BUILDING_DEPLOYED"
	"a_swimN_BUILDING_DEPLOYED"
	"a_swimNE_BUILDING_DEPLOYED"
	fps 30
	"ACT_MP_SWIM_BUILDING_DEPLOYED" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_DEPLOYED_aimmatrix_idle"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "SECONDARY_aimmatrix_forward" {
	"a_SECONDARY_aimmatrix_forward_straight_up"
	"a_SECONDARY_aimmatrix_forward_straight_up"
	"a_SECONDARY_aimmatrix_forward_straight_up"
	"a_SECONDARY_aimmatrix_forward_up_right"
	"a_SECONDARY_aimmatrix_forward_up_center"
	"a_SECONDARY_aimmatrix_forward_up_left"
	"a_SECONDARY_aimmatrix_forward_mid_right"
	"a_SECONDARY_aimmatrix_forward_mid_center"
	"a_SECONDARY_aimmatrix_forward_mid_left"
	"a_SECONDARY_aimmatrix_forward_down_right"
	"a_SECONDARY_aimmatrix_forward_down_center"
	"a_SECONDARY_aimmatrix_forward_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_reverse" {
	"a_SECONDARY_aimmatrix_reverse_straight_up"
	"a_SECONDARY_aimmatrix_reverse_straight_up"
	"a_SECONDARY_aimmatrix_reverse_straight_up"
	"a_SECONDARY_aimmatrix_reverse_up_right"
	"a_SECONDARY_aimmatrix_reverse_up_center"
	"a_SECONDARY_aimmatrix_reverse_up_left"
	"a_SECONDARY_aimmatrix_reverse_mid_right"
	"a_SECONDARY_aimmatrix_reverse_mid_center"
	"a_SECONDARY_aimmatrix_reverse_mid_left"
	"a_SECONDARY_aimmatrix_reverse_down_right"
	"a_SECONDARY_aimmatrix_reverse_down_center"
	"a_SECONDARY_aimmatrix_reverse_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	blendlayer "SECONDARY_aimmatrix_forward" -0.8 -0.2 1 2 spline poseparameter move_x
	blendlayer "SECONDARY_aimmatrix_reverse" -2 -1 -0.8 -0.2 spline poseparameter move_x
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_SECONDARY"
	"a_crouch_walkS_SECONDARY"
	"a_crouch_walkSE_SECONDARY"
	"a_crouch_walkW_SECONDARY"
	"a_crouch_walkCenter_SECONDARY"
	"a_crouch_walkE_SECONDARY"
	"a_crouch_walkNW_SECONDARY"
	"a_crouch_walkN_SECONDARY"
	"a_crouch_walkNE_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_forward"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_handposes"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_idle"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "run_ITEM2" {
	"a_runSW_ITEM2"
	"a_runS_ITEM2"
	"a_runSE_ITEM2"
	"a_runW_ITEM2"
	"a_runCenter_ITEM2"
	"a_runE_ITEM2"
	"a_runNW_ITEM2"
	"a_runN_ITEM2"
	"a_runNE_ITEM2"
	fps 30
	"ACT_MP_RUN_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_idle"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_ITEM2" {
	"a_crouch_walkSW_crouch_walk_ITEM2"
	"a_crouch_walkS_crouch_walk_ITEM2"
	"a_crouch_walkSE_crouch_walk_ITEM2"
	"a_crouch_walkW_crouch_walk_ITEM2"
	"a_crouch_walkCenter_crouch_walk_ITEM2"
	"a_crouch_walkE_crouch_walk_ITEM2"
	"a_crouch_walkNW_crouch_walk_ITEM2"
	"a_crouch_walkN_crouch_walk_ITEM2"
	"a_crouch_walkNE_crouch_walk_ITEM2"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM2_aimmatrix_crouch_idle"
}

$sequence "run_PDA" {
	"a_runSW_PDA"
	"a_runS_PDA"
	"a_runSE_PDA"
	"a_runW_PDA"
	"a_runCenter_PDA"
	"a_runE_PDA"
	"a_runNW_PDA"
	"a_runN_PDA"
	"a_runNE_PDA"
	fps 30
	"ACT_MP_RUN_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_PDA" {
	"a_crouch_walkSW_crouch_walk_PDA"
	"a_crouch_walkS_crouch_walk_PDA"
	"a_crouch_walkSE_crouch_walk_PDA"
	"a_crouch_walkW_crouch_walk_PDA"
	"a_crouch_walkCenter_crouch_walk_PDA"
	"a_crouch_walkE_crouch_walk_PDA"
	"a_crouch_walkNW_crouch_walk_PDA"
	"a_crouch_walkN_crouch_walk_PDA"
	"a_crouch_walkNE_crouch_walk_PDA"
	fps 30
	"ACT_MP_CROUCHWALK_PDA" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PDA_aimmatrix_crouch_idle"
}

$sequence "run_BUILDING" {
	"a_runSW_BUILDING"
	"a_runS_BUILDING"
	"a_runSE_BUILDING"
	"a_runW_BUILDING"
	"a_runCenter_BUILDING"
	"a_runE_BUILDING"
	"a_runNW_BUILDING"
	"a_runN_BUILDING"
	"a_runNE_BUILDING"
	fps 30
	"ACT_MP_RUN_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_BUILDING" {
	"a_crouch_walkSW_BUILDING"
	"a_crouch_walkS_BUILDING"
	"a_crouch_walkSE_BUILDING"
	"a_crouch_walkW_BUILDING"
	"a_crouch_walkCenter_BUILDING"
	"a_crouch_walkE_BUILDING"
	"a_crouch_walkNW_BUILDING"
	"a_crouch_walkN_BUILDING"
	"a_crouch_walkNE_BUILDING"
	fps 30
	"ACT_MP_CROUCHWALK_BUILDING" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_aimmatrix_crouch_idle"
}

$sequence "run_BUILDING_DEPLOYED" {
	"a_runSW_BUILDING_DEPLOYED"
	"a_runS_BUILDING_DEPLOYED"
	"a_runSE_BUILDING_DEPLOYED"
	"a_runW_BUILDING_DEPLOYED"
	"a_runCenter_BUILDING_DEPLOYED"
	"a_runE_BUILDING_DEPLOYED"
	"a_runNW_BUILDING_DEPLOYED"
	"a_runN_BUILDING_DEPLOYED"
	"a_runNE_BUILDING_DEPLOYED"
	fps 30
	"ACT_MP_RUN_BUILDING_DEPLOYED" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_DEPLOYED_aimmatrix_idle"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_BUILDING_DEPLOYED" {
	"a_crouch_walkSW_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkS_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkSE_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkW_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkCenter_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkE_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkNW_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkN_crouch_walk_BUILDING_DEPLOYED"
	"a_crouch_walkNE_crouch_walk_BUILDING_DEPLOYED"
	fps 30
	"ACT_MP_CROUCHWALK_BUILDING_DEPLOYED" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "BUILDING_DEPLOYED_aimmatrix_crouch_idle"
}

$sequence "PRIMARY_aimmatrix_airwalk" {
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_up_right"
	"a_PRIMARY_aimmatrix_airwalk_up_center"
	"a_PRIMARY_aimmatrix_airwalk_up_left"
	"a_PRIMARY_aimmatrix_airwalk_mid_right"
	"a_PRIMARY_aimmatrix_airwalk_mid_center"
	"a_PRIMARY_aimmatrix_airwalk_mid_left"
	"a_PRIMARY_aimmatrix_airwalk_down_right"
	"a_PRIMARY_aimmatrix_airwalk_down_center"
	"a_PRIMARY_aimmatrix_airwalk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "airwalk_PRIMARY" "engineer_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_airwalk"
}

$sequence "airwalk_SECONDARY" "engineer_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "airwalk_MELEE" "engineer_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "airwalk_MELEE_ALLCLASS" "engineer_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_aimmatrix_swim"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "engineer_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "engineer_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "airwalk_ITEM2" "engineer_animations_anims\airwalk_ITEM2.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM2" 1
	loop
	// addlayer "ITEM2_aimmatrix_idle"
}

$sequence "airwalk_PDA" "engineer_animations_anims\airwalk_PDA.smd" {
	fps 30
	"ACT_MP_AIRWALK_PDA" 1
	loop
	// addlayer "PDA_aimmatrix_swim"
}

$sequence "airwalk_BUILDING" "engineer_animations_anims\airwalk_BUILDING.smd" {
	fps 30
	"ACT_MP_AIRWALK_BUILDING" 1
	loop
	// addlayer "BUILDING_aimmatrix_swim"
}

$sequence "airwalk_BUILDING_DEPLOYED" "engineer_animations_anims\airwalk_BUILDING_DEPLOYED.smd" {
	fps 30
	"ACT_MP_AIRWALK_BUILDING_DEPLOYED" 1
	loop
	// addlayer "BUILDING_DEPLOYED_aimmatrix_idle"
}

$sequence "a_flinch01" "engineer_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 2
	// delta
}

$sequence "a_flinch02" "engineer_animations_anims\a_flinch02.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 10
	// delta
}

$sequence "a_flinch04" "engineer_animations_anims\a_flinch04.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 5
	// delta
}

$sequence "layer_dieviolent" "engineer_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "engineer_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "PRIMARY_death_headshot" "engineer_animations_anims\PRIMARY_death_headshot.smd" {
	fps 30
}

$sequence "PRIMARY_death_backstab" "engineer_animations_anims\PRIMARY_death_backstab.smd" {
	fps 30
}

$sequence "PRIMARY_death_burning" "engineer_animations_anims\PRIMARY_death_burning.smd" {
	fps 30
}

$sequence "layer_PRIMARY_stun_begin" "engineer_animations_anims\layer_PRIMARY_stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "engineer_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_end" "engineer_animations_anims\layer_PRIMARY_stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_stun_begin" "engineer_animations_anims\PRIMARY_stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_begin"
}

$sequence "PRIMARY_stun_middle" "engineer_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "engineer_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_end"
}

$sequence "SelectionMenu_StartPose" "engineer_animations_anims\SelectionMenu_StartPose.smd" {
	fps 30
}

$sequence "SelectionMenu_Anim01" "engineer_animations_anims\SelectionMenu_Anim01.smd" {
	fps 30
	{ event 5004 17.000000551343 "Selection.EngineerFootStomp" }
	{ event 5004 23.0000004172325 "Selection.EngineerWrenchShoulder" }
	{ event 5004 40.0000020861626 "Selection.EngineerClothesRustle" }
}

$sequence "SelectionMenu_Idle" "engineer_animations_anims\SelectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "armslayer_throw_fire" "engineer_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "engineer_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "engineer_animations_anims\layer_taunt01.smd" {
	fps 23
	hidden
}

$sequence "taunt01" "engineer_animations_anims\taunt01.smd" {
	fps 23
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt01"
	{ event AE_WPN_HIDE 1.00000003818423 "" }
	{ event AE_WPN_UNHIDE 105 "" }
	{ event 5004 10.0000001862645 "Taunt.Engineer01HandClap" }
	{ event 5004 59.0000027418137 "Taunt.Engineer01HandClap2" }
	{ event 5004 22.0000002533197 "Taunt.Engineer01FootStomp" }
	{ event 5004 29.0000014007092 "Taunt.Engineer01FootStomp" }
	{ event 5004 68.0000022053719 "Taunt.Engineer01FootStomp" }
	{ event 5004 37.000000923872 "Taunt.Engineer01FootStompLight" }
	{ event 5004 42.0000006258488 "Taunt.Engineer01FootStompLight" }
	{ event 5004 47.0000003278255 "Taunt.Engineer01FootStompLight" }
	{ event 5004 56.0000029206276 "Taunt.Engineer01FootStomp" }
	{ event 5004 57.0000028610229 "Taunt.Engineer01FootStompLight" }
	{ event 5004 60.000002682209 "Taunt.Engineer01FootStompLight" }
	{ event 5004 79.0000015497208 "Taunt.Engineer01FootStompLight" }
	{ event 5004 86.0000011324883 "Taunt.Engineer01FootStompLight" }
	{ event 5004 88.000001013279 "Taunt.Engineer01FootStomp" }
}

$sequence "layer_taunt02" "engineer_animations_anims\layer_taunt02.smd" {
	fps 30
	hidden
}

$sequence "taunt02" "engineer_animations_anims\taunt02.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt02"
	{ event 5004 8.99999984353781 "Taunt.Engineer02PistolTwirl" }
}

$sequence "layer_taunt03" "engineer_animations_anims\layer_taunt03.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "engineer_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt03"
	{ event 5004 38.0000011026859 "Taunt.Engineer01HandClap" }
	{ event 5004 37.0000005364418 "Taunt.Engineer01FootStompLight" }
	{ event 5004 48.999999165535 "Taunt.Engineer01FootStompLight" }
	{ event 5004 39.999998152256 "Taunt.Engineer01FootStomp" }
}

$sequence "taunt06" "engineer_animations_anims\taunt06.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "layer_taunt07" "engineer_animations_anims\layer_taunt07.smd" {
	fps 30
	hidden
}

$sequence "taunt07" "engineer_animations_anims\taunt07.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt07"
	{ event AE_WPN_HIDE 112.000000476837 "" }
	{ event AE_WPN_UNHIDE 120 "" }
	{ event 5004 45 "Taunt.EngineerStrum" }
	{ event 5004 97.9999995231628 "Taunt.EngineerSwoosh" }
	{ event 5004 107.999997138977 "Taunt.EngineerSmash" }
}

$sequence "layer_taunt_replay" "engineer_animations_anims\layer_taunt_replay.smd" {
	fps 30
	hidden
}

$sequence "taunt_replay" "engineer_animations_anims\taunt_replay.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_replay"
	{ event AE_WPN_HIDE 0.999999977648258 "" }
	{ event AE_WPN_UNHIDE 99.0000009536743 "" }
}

$sequence "layer_taunt_laugh" "engineer_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "engineer_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.999999977648258 "" }
	{ event AE_WPN_UNHIDE 99.0000009536743 "" }
}

$sequence "layer_taunt09" "engineer_animations_anims\layer_taunt09.smd" {
	fps 30
	hidden
}

$sequence "taunt09" "engineer_animations_anims\taunt09.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt09"
	{ event 5004 1.00000000093132 "Taunt.EngineerGunSlinger" }
}

$sequence "layer_taunt10" "engineer_animations_anims\layer_taunt10.smd" {
	fps 30
	hidden
}

$sequence "taunt10" "engineer_animations_anims\taunt10.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt10"
}

$sequence "layer_taunt_drg_melee" "engineer_animations_anims\layer_taunt_drg_melee.smd" {
	fps 30
	hidden
}

$sequence "taunt_drg_melee" "engineer_animations_anims\taunt_drg_melee.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_TAUNT" 1
	// addlayer "layer_taunt_drg_melee"
}

$sequence "taunt_brutallegendinterior" "engineer_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "engineer_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "engineer_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "engineer_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "engineer_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "engineer_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_hifiveSuccess" "engineer_animations_anims\taunt_hifiveSuccess.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000005122274 "" }
	{ event AE_WPN_UNHIDE 119 "" }
}

$sequence "taunt_hifiveSuccessFull" "engineer_animations_anims\taunt_hifiveSuccessFull.smd" {
	fps 30
	{ event AE_WPN_HIDE 1.00000005122274 "" }
	{ event AE_WPN_UNHIDE 119 "" }
}

$sequence "taunt_highFiveStart" "engineer_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 76 "" }
}

$sequence "taunt_highFiveStart_idle" "engineer_animations_anims\taunt_highFiveStart_idle.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 137 "" }
}

$sequence "taunt_conga" "engineer_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "engineer_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "engineer_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
	{ event AE_CL_PLAYSOUND 100.000003695488 "Taunt.MedicHardClap3" }
	{ event 5004 220.999993622303 "Taunt.Engineer_Western_Shoot1" }
	{ event 5004 225.999995291233 "Taunt.Engineer_Western_Shoot2" }
}

$sequence "layer_taunt_dosido_intro" "engineer_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "engineer_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
	{ event AE_CL_PLAYSOUND 33.0000003576279 "Taunt.MedicHardClap4" }
	{ event AE_CL_PLAYSOUND 47.9999995231628 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 63.0000014305115 "Taunt.MedicHardClap6" }
	{ event AE_CL_PLAYSOUND 77.9999978542328 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 92 "Taunt.MedicHardClap5" }
}

$sequence "taunt_flip_start" "engineer_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "engineer_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "engineer_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 0.999999968335032 "" }
	{ event AE_WPN_UNHIDE 100.000002980232 "" }
}

$sequence "layer_taunt_flip_success_receiver" "engineer_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "engineer_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 0.999999999068677 "" }
	{ event AE_WPN_UNHIDE 140.000002682209 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 39.9999988377094 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 57.9999985396862 "taunt_flip_land follow_attachment foot_R" }
}

$sequence "taunt_rps_start" "engineer_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "engineer_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "engineer_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "engineer_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "engineer_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "engineer_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "engineer_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_rock_win" "engineer_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "engineer_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 195.000004768372 "" }
}

$sequence "layer_taunt_rps_paper_win" "engineer_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "engineer_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 195.000004768372 "" }
}

$sequence "layer_taunt_rps_scissors_win" "engineer_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "engineer_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 195.000004768372 "" }
}

$sequence "layer_taunt_rps_rock_lose" "engineer_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "engineer_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 194.999996066093 "" }
}

$sequence "layer_taunt_rps_paper_lose" "engineer_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "engineer_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 194.999996066093 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "engineer_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "engineer_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 194.999996066093 "" }
}

$sequence "layer_taunt_headbutt_start" "engineer_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "engineer_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_headbutt_success" "engineer_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "engineer_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55.9999980032444 "taunt_headbutt_impact follow_attachment head" }
}

$sequence "layer_taunt_killer_time_intro" "engineer_animations_anims\layer_taunt_killer_time_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_killer_time_intro" "engineer_animations_anims\taunt_killer_time_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_killer_time_intro"
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_killer_time_outro" "engineer_animations_anims\layer_taunt_killer_time_outro.smd" {
	fps 30
	hidden
}

$sequence "taunt_killer_time_outro" "engineer_animations_anims\taunt_killer_time_outro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_killer_time_outro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "taunt_ENGINEER_SPARKS start_at_origin back_lower" }
}

$ikchain "rhand" "bip_hand_R" knee 0.697 0.717 0.003
$ikchain "lhand" "bip_hand_L" knee 0.687 -0.727 0.002
$ikchain "rfoot" "bip_foot_R" knee 0.583 -0.001 0.813
$ikchain "lfoot" "bip_foot_L" knee 0.581 0.001 0.814

