// Created by Crowbar 0.19.0.0

$modelname "player/soldier_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_y" -1 1 0
$poseparameter "move_x" -1 1 0

$cdmaterials "models\player\soldier\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "soldier_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "soldier_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "soldier_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "soldier_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "soldier_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "soldier_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "soldier_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "soldier_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "soldier_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "soldier_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "soldier_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "soldier_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "soldier_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "soldier_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "soldier_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "soldier_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "soldier_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "soldier_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "soldier_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "soldier_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_reload_startpose" "soldier_animations_anims\a_reload_startpose.smd" {
	fps 30
}
$animation "a_reload_startpose_3" "soldier_animations_anims\a_reload_startpose_3.smd" {
	fps 30
}
$animation "a_quake_reload_startpose" "soldier_animations_anims\a_quake_reload_startpose.smd" {
	fps 30
}
$animation "a_reload_startpose_2" "soldier_animations_anims\a_reload_startpose_2.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "soldier_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "soldier_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "soldier_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_reload_secondary_startpose" "soldier_animations_anims\a_reload_secondary_startpose.smd" {
	fps 30
}
$animation "a_reload_crouch_secondary_startpose" "soldier_animations_anims\a_reload_crouch_secondary_startpose.smd" {
	fps 30
}
$animation "a_SECONDARY2_aimmatrix_idle_neutral" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY2_aimmatrix_idle_down_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_down_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_down_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_mid_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_mid_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_mid_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_up_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_up_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_up_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_idle_straight_up" "soldier_animations_anims\a_SECONDARY2_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_neutral" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY2_aimmatrix_run_down_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_down_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_down_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_mid_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_mid_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_mid_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_up_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_up_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_up_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_run_straight_up" "soldier_animations_anims\a_SECONDARY2_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_neutral" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_down_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_down_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_down_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_mid_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_mid_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_mid_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_up_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_up_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_up_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_crouch_idle_straight_up" "soldier_animations_anims\a_SECONDARY2_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_reload_SECONDARY2_startpose" "soldier_animations_anims\a_reload_SECONDARY2_startpose.smd" {
	fps 30
}
$animation "a_reload_crouch_SECONDARY2_startpose" "soldier_animations_anims\a_reload_crouch_SECONDARY2_startpose.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_neutral" "soldier_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "soldier_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "soldier_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "soldier_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "soldier_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "soldier_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "soldier_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "soldier_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "soldier_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "soldier_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "soldier_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "soldier_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "soldier_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "soldier_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "soldier_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "soldier_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "soldier_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "soldier_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "soldier_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "soldier_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "soldier_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "soldier_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "soldier_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_Swim_Swing" "soldier_animations_anims\a_Melee_Swim_Swing.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "soldier_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "soldier_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "soldier_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "soldier_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "soldier_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "soldier_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "soldier_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "soldier_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "soldier_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "soldier_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "soldier_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "soldier_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "soldier_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "soldier_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "soldier_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "soldier_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "soldier_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "soldier_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "soldier_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "soldier_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY2_aimmatrix_swim_neutral" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY2_aimmatrix_swim_down_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_down_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_down_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_mid_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_mid_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_mid_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_up_right" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_up_center" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_up_left" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY2_aimmatrix_swim_straight_up" "soldier_animations_anims\a_SECONDARY2_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY2" "soldier_animations_anims\a_swimCenter_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY2" "soldier_animations_anims\a_swimS_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY2" "soldier_animations_anims\a_swimSE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY2" "soldier_animations_anims\a_swimE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY2" "soldier_animations_anims\a_swimNE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY2" "soldier_animations_anims\a_swimN_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY2" "soldier_animations_anims\a_swimNW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY2" "soldier_animations_anims\a_swimW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY2" "soldier_animations_anims\a_swimSW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "soldier_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "soldier_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "soldier_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "soldier_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "soldier_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "soldier_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "soldier_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "soldier_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "soldier_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "soldier_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "soldier_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "soldier_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "soldier_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "soldier_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "soldier_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "soldier_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "soldier_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "soldier_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "soldier_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "soldier_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "soldier_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "soldier_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "soldier_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "soldier_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "soldier_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "soldier_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "soldier_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "soldier_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "soldier_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "soldier_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "soldier_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "soldier_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "soldier_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "soldier_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "soldier_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "soldier_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "soldier_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "soldier_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "soldier_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "soldier_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "soldier_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "soldier_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "soldier_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "soldier_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "soldier_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "soldier_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "soldier_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "soldier_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "soldier_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "soldier_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "soldier_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "soldier_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "soldier_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "soldier_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "soldier_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "soldier_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "soldier_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "soldier_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "soldier_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "soldier_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "soldier_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "soldier_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "soldier_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "soldier_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "soldier_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY" "soldier_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY" "soldier_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "soldier_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "soldier_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "soldier_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "soldier_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "soldier_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "soldier_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "soldier_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "soldier_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "soldier_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "soldier_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "soldier_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "soldier_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "soldier_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "soldier_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "soldier_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "soldier_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "soldier_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "soldier_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "soldier_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "soldier_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "soldier_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "soldier_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "soldier_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "soldier_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "soldier_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "soldier_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "soldier_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "soldier_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "soldier_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "soldier_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY2" "soldier_animations_anims\a_runCenter_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY2" "soldier_animations_anims\a_runS_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY2" "soldier_animations_anims\a_runSE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY2" "soldier_animations_anims\a_runE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY2" "soldier_animations_anims\a_runNE_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY2" "soldier_animations_anims\a_runN_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY2" "soldier_animations_anims\a_runNW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY2" "soldier_animations_anims\a_runW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY2" "soldier_animations_anims\a_runSW_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY2" "soldier_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY2.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY2" "soldier_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY2.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "soldier_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_Swim_Swing" "soldier_animations_anims\a_MELEE_ALLCLASS_Swim_Swing.smd" {
	fps 30
}
$animation "a_stun_startpose" "soldier_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "soldier_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_throw_fire" "soldier_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "soldier_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "test" "soldier_animations_anims\test.smd" {
	fps 30
}

$sequence "AttackStand_PRIMARY" "soldier_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY" "soldier_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "soldier_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "AttackStand_PRIMARY2" "soldier_animations_anims\AttackStand_PRIMARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY_ALT" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY2" "soldier_animations_anims\AttackCrouch_PRIMARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY_ALT" 1
	// delta
}

$sequence "AttackSwim_PRIMARY2" "soldier_animations_anims\AttackSwim_PRIMARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY_ALT" 1
	// delta
}

$sequence "AttackStand_PRIMARY2_SUPER" "soldier_animations_anims\AttackStand_PRIMARY2_SUPER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY_SUPER" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY2_SUPER" "soldier_animations_anims\AttackCrouch_PRIMARY2_SUPER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY_SUPER" 1
	// delta
}

$sequence "AttackSwim_PRIMARY2_SUPER" "soldier_animations_anims\AttackSwim_PRIMARY2_SUPER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY_SUPER" 1
	// delta
}

$sequence "layer_reload_standing_arms" "soldier_animations_anims\layer_reload_standing_arms.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_PRIMARY" "soldier_animations_anims\ReloadStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY" "soldier_animations_anims\ReloadCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY" "soldier_animations_anims\ReloadAirwalk_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY" 1
	// delta
	// addlayer "layer_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "layer_reload_standing_arms_loop" "soldier_animations_anims\layer_reload_standing_arms_loop.smd" {
	fps 30
	loop
	hidden
}

$sequence "ReloadStand_PRIMARY_loop" "soldier_animations_anims\ReloadStand_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY_loop" "soldier_animations_anims\ReloadCrouch_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY_loop" "soldier_animations_anims\ReloadAirwalk_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "layer_reload_standing_arms_end" "soldier_animations_anims\layer_reload_standing_arms_end.smd" {
	fps 44
	hidden
}

$sequence "ReloadStand_PRIMARY_end" "soldier_animations_anims\ReloadStand_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END" 1
	// delta
	blendlayer "layer_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY_end" "soldier_animations_anims\ReloadCrouch_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END" 1
	// delta
	blendlayer "layer_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY_end" "soldier_animations_anims\ReloadAirwalk_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END" 1
	// delta
	blendlayer "layer_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "layer_reload_swim_arms" "soldier_animations_anims\layer_reload_swim_arms.smd" {
	fps 44
	hidden
}

$sequence "ReloadSwim_PRIMARY" "soldier_animations_anims\ReloadSwim_PRIMARY.smd" {
	fps 44
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
	// addlayer "layer_reload_swim_arms"
}

$sequence "layer_reload_standing_arms_3" "soldier_animations_anims\layer_reload_standing_arms_3.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_PRIMARY_3" "soldier_animations_anims\ReloadStand_PRIMARY_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_ALT" 1
	// delta
	// addlayer "layer_reload_standing_arms_3"
}

$sequence "ReloadCrouch_PRIMARY_3" "soldier_animations_anims\ReloadCrouch_PRIMARY_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_ALT" 1
	// delta
	// addlayer "layer_reload_standing_arms_3"
}

$sequence "ReloadAirwalk_PRIMARY_3" "soldier_animations_anims\ReloadAirwalk_PRIMARY_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_ALT" 1
	// delta
	// addlayer "layer_reload_standing_arms_3"
}

$sequence "layer_reload_standing_arms_loop_3" "soldier_animations_anims\layer_reload_standing_arms_loop_3.smd" {
	fps 30
	loop
	hidden
}

$sequence "ReloadStand_PRIMARY_loop_3" "soldier_animations_anims\ReloadStand_PRIMARY_loop_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP_ALT" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_3"
}

$sequence "ReloadCrouch_PRIMARY_loop_3" "soldier_animations_anims\ReloadCrouch_PRIMARY_loop_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP_ALT" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_3"
}

$sequence "ReloadAirwalk_PRIMARY_loop_3" "soldier_animations_anims\ReloadAirwalk_PRIMARY_loop_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP_ALT" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_3"
}

$sequence "layer_reload_standing_arms_end_3" "soldier_animations_anims\layer_reload_standing_arms_end_3.smd" {
	fps 44
	hidden
}

$sequence "ReloadStand_PRIMARY_end_3" "soldier_animations_anims\ReloadStand_PRIMARY_end_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END_ALT" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_3" 0 0 0.555556 1 spline
}

$sequence "ReloadCrouch_PRIMARY_end_3" "soldier_animations_anims\ReloadCrouch_PRIMARY_end_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END_ALT" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_3" 0 0 0.555556 1 spline
}

$sequence "ReloadAirwalk_PRIMARY_end_3" "soldier_animations_anims\ReloadAirwalk_PRIMARY_end_3.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END_ALT" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_3" 0 0 0.555556 1 spline
}

$sequence "layer_reload_swim_arms_3" "soldier_animations_anims\layer_reload_swim_arms_3.smd" {
	fps 44
	hidden
}

$sequence "ReloadSwim_PRIMARY_3" "soldier_animations_anims\ReloadSwim_PRIMARY_3.smd" {
	fps 44
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_ALT" 1
	// delta
	// addlayer "layer_reload_swim_arms_3"
}

$sequence "layer_quake_reload_standing_arms" "soldier_animations_anims\layer_quake_reload_standing_arms.smd" {
	fps 30
	hidden
}

$sequence "quake_ReloadStand_PRIMARY" "soldier_animations_anims\quake_ReloadStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY3" 1
	// delta
	// addlayer "layer_quake_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "quake_ReloadCrouch_PRIMARY" "soldier_animations_anims\quake_ReloadCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY3" 1
	// delta
	// addlayer "layer_quake_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "quake_ReloadAirwalk_PRIMARY" "soldier_animations_anims\quake_ReloadAirwalk_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY3" 1
	// delta
	// addlayer "layer_quake_reload_standing_arms"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "layer_quake_reload_standing_arms_loop" "soldier_animations_anims\layer_quake_reload_standing_arms_loop.smd" {
	fps 30
	loop
	hidden
}

$sequence "quake_ReloadStand_PRIMARY_loop" "soldier_animations_anims\quake_ReloadStand_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY3_LOOP" 1
	loop
	// delta
	// addlayer "layer_quake_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "quake_ReloadCrouch_PRIMARY_loop" "soldier_animations_anims\quake_ReloadCrouch_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY3_LOOP" 1
	loop
	// delta
	// addlayer "layer_quake_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "quake_ReloadAirwalk_PRIMARY_loop" "soldier_animations_anims\quake_ReloadAirwalk_PRIMARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY3_LOOP" 1
	loop
	// delta
	// addlayer "layer_quake_reload_standing_arms_loop"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "layer_quake_reload_standing_arms_end" "soldier_animations_anims\layer_quake_reload_standing_arms_end.smd" {
	fps 44
	hidden
}

$sequence "quake_ReloadStand_PRIMARY_end" "soldier_animations_anims\quake_ReloadStand_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY3_END" 1
	// delta
	blendlayer "layer_quake_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "quake_ReloadCrouch_PRIMARY_end" "soldier_animations_anims\quake_ReloadCrouch_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY3_END" 1
	// delta
	blendlayer "layer_quake_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "quake_ReloadAirwalk_PRIMARY_end" "soldier_animations_anims\quake_ReloadAirwalk_PRIMARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY3_END" 1
	// delta
	blendlayer "layer_quake_reload_standing_arms_end" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "layer_quake_reload_swim_arms" "soldier_animations_anims\layer_quake_reload_swim_arms.smd" {
	fps 44
	hidden
}

$sequence "quake_ReloadSwim_PRIMARY" "soldier_animations_anims\quake_ReloadSwim_PRIMARY.smd" {
	fps 44
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY3" 1
	// delta
	// addlayer "layer_quake_reload_swim_arms"
}

$sequence "layer_reload_standing_arms_2" "soldier_animations_anims\layer_reload_standing_arms_2.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_PRIMARY_2" "soldier_animations_anims\ReloadStand_PRIMARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY_2" "soldier_animations_anims\ReloadCrouch_PRIMARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY_2" "soldier_animations_anims\ReloadAirwalk_PRIMARY_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_2" 1
	// delta
	// addlayer "layer_reload_standing_arms_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 11 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21 "rocket 0" }
}

$sequence "layer_reload_standing_arms_loop_2" "soldier_animations_anims\layer_reload_standing_arms_loop_2.smd" {
	fps 30
	loop
	hidden
}

$sequence "ReloadStand_PRIMARY_loop_2" "soldier_animations_anims\ReloadStand_PRIMARY_loop_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP_2" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY_loop_2" "soldier_animations_anims\ReloadCrouch_PRIMARY_loop_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP_2" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY_loop_2" "soldier_animations_anims\ReloadAirwalk_PRIMARY_loop_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP_2" 1
	loop
	// delta
	// addlayer "layer_reload_standing_arms_loop_2"
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
	{ event AE_CL_BODYGROUP_SET_VALUE 12.000000089407 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 21.9999997615814 "rocket 0" }
}

$sequence "layer_reload_standing_arms_end_2" "soldier_animations_anims\layer_reload_standing_arms_end_2.smd" {
	fps 44
	hidden
}

$sequence "ReloadStand_PRIMARY_end_2" "soldier_animations_anims\ReloadStand_PRIMARY_end_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END_2" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_2" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "ReloadCrouch_PRIMARY_end_2" "soldier_animations_anims\ReloadCrouch_PRIMARY_end_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END_2" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_2" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "ReloadAirwalk_PRIMARY_end_2" "soldier_animations_anims\ReloadAirwalk_PRIMARY_end_2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END_2" 1
	// delta
	blendlayer "layer_reload_standing_arms_end_2" 0 0 0.555556 1 spline
	{ event AE_CL_BODYGROUP_SET_VALUE 1.00000000745058 "rocket 0" }
}

$sequence "layer_reload_swim_arms_2" "soldier_animations_anims\layer_reload_swim_arms_2.smd" {
	fps 44
	hidden
}

$sequence "ReloadSwim_PRIMARY_2" "soldier_animations_anims\ReloadSwim_PRIMARY_2.smd" {
	fps 44
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_2" 1
	// delta
	// addlayer "layer_reload_swim_arms_2"
}

$sequence "a_flinch01" "soldier_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "soldier_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "soldier_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "soldier_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "ReloadSwim_SECONDARY" "soldier_animations_anims\ReloadSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
}

$sequence "layer_reload_standing_secondary_arms" "soldier_animations_anims\layer_reload_standing_secondary_arms.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY" "soldier_animations_anims\ReloadStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
	// addlayer "layer_reload_standing_secondary_arms"
}

$sequence "layer_reload_standing_secondary_arms_loop" "soldier_animations_anims\layer_reload_standing_secondary_arms_loop.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY_loop" "soldier_animations_anims\ReloadStand_SECONDARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_secondary_arms_loop"
}

$sequence "layer_reload_standing_secondary_arms_end" "soldier_animations_anims\layer_reload_standing_secondary_arms_end.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY_end" "soldier_animations_anims\ReloadStand_SECONDARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_END" 1
	// delta
	blendlayer "layer_reload_standing_secondary_arms_end" 0 0 0.571429 1.071429 spline
}

$sequence "layer_reload_crouch_secondary_arms" "soldier_animations_anims\layer_reload_crouch_secondary_arms.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY" "soldier_animations_anims\ReloadCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	// addlayer "layer_reload_crouch_secondary_arms"
}

$sequence "layer_reload_crouch_secondary_arms_loop" "soldier_animations_anims\layer_reload_crouch_secondary_arms_loop.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY_loop" "soldier_animations_anims\ReloadCrouch_SECONDARY_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_crouch_secondary_arms_loop"
}

$sequence "layer_reload_crouch_secondary_arms_end" "soldier_animations_anims\layer_reload_crouch_secondary_arms_end.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY_end" "soldier_animations_anims\ReloadCrouch_SECONDARY_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_END" 1
	// delta
	// addlayer "layer_reload_crouch_secondary_arms_end"
}

$sequence "a_SECONDARY_reload_airwalk" "soldier_animations_anims\a_SECONDARY_reload_airwalk.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY" "soldier_animations_anims\layer_reload_arms_SECONDARY.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk" "soldier_animations_anims\SECONDARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY"
}

$sequence "layer_reload_arms_SECONDARY_loop" "soldier_animations_anims\layer_reload_arms_SECONDARY_loop.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk_loop" "soldier_animations_anims\SECONDARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_loop"
}

$sequence "layer_reload_arms_SECONDARY_end" "soldier_animations_anims\layer_reload_arms_SECONDARY_end.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_airwalk_end" "soldier_animations_anims\SECONDARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_end"
	fadeout 1
}

$sequence "a_SECONDARY_reload_swim" "soldier_animations_anims\a_SECONDARY_reload_swim.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim" "soldier_animations_anims\SECONDARY_reload_swim.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_swim"
}

$sequence "layer_reload_arms_SECONDARY_loop_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY_loop_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim_loop" "soldier_animations_anims\SECONDARY_reload_swim_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_loop_swim"
}

$sequence "layer_reload_arms_SECONDARY_end_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY_end_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY_reload_swim_end" "soldier_animations_anims\SECONDARY_reload_swim_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY_end_swim"
	fadeout 1
}

$sequence "SECONDARY2_aimmatrix_idle" {
	"a_SECONDARY2_aimmatrix_idle_straight_up"
	"a_SECONDARY2_aimmatrix_idle_straight_up"
	"a_SECONDARY2_aimmatrix_idle_straight_up"
	"a_SECONDARY2_aimmatrix_idle_up_right"
	"a_SECONDARY2_aimmatrix_idle_up_center"
	"a_SECONDARY2_aimmatrix_idle_up_left"
	"a_SECONDARY2_aimmatrix_idle_mid_right"
	"a_SECONDARY2_aimmatrix_idle_mid_center"
	"a_SECONDARY2_aimmatrix_idle_mid_left"
	"a_SECONDARY2_aimmatrix_idle_down_right"
	"a_SECONDARY2_aimmatrix_idle_down_center"
	"a_SECONDARY2_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY2_aimmatrix_run" {
	"a_SECONDARY2_aimmatrix_run_straight_up"
	"a_SECONDARY2_aimmatrix_run_straight_up"
	"a_SECONDARY2_aimmatrix_run_straight_up"
	"a_SECONDARY2_aimmatrix_run_up_right"
	"a_SECONDARY2_aimmatrix_run_up_center"
	"a_SECONDARY2_aimmatrix_run_up_left"
	"a_SECONDARY2_aimmatrix_run_mid_right"
	"a_SECONDARY2_aimmatrix_run_mid_center"
	"a_SECONDARY2_aimmatrix_run_mid_left"
	"a_SECONDARY2_aimmatrix_run_down_right"
	"a_SECONDARY2_aimmatrix_run_down_center"
	"a_SECONDARY2_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY2_aimmatrix_crouch_idle" {
	"a_SECONDARY2_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY2_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY2_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY2_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY2_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY2_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY2_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY2_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY2_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY2_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY2_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY2_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY2" "soldier_animations_anims\AttackStand_SECONDARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY2" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY2" "soldier_animations_anims\AttackCrouch_SECONDARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY2" 1
	// delta
}

$sequence "layer_reload_standing_SECONDARY2_arms" "soldier_animations_anims\layer_reload_standing_SECONDARY2_arms.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY2" "soldier_animations_anims\ReloadStand_SECONDARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY2" 1
	// delta
	// addlayer "layer_reload_standing_SECONDARY2_arms"
}

$sequence "layer_reload_standing_SECONDARY2_arms_loop" "soldier_animations_anims\layer_reload_standing_SECONDARY2_arms_loop.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY2_loop" "soldier_animations_anims\ReloadStand_SECONDARY2_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY2_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_standing_SECONDARY2_arms_loop"
}

$sequence "layer_reload_standing_SECONDARY2_arms_end" "soldier_animations_anims\layer_reload_standing_SECONDARY2_arms_end.smd" {
	fps 30
	hidden
}

$sequence "ReloadStand_SECONDARY2_end" "soldier_animations_anims\ReloadStand_SECONDARY2_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY2_END" 1
	// delta
	blendlayer "layer_reload_standing_SECONDARY2_arms_end" 0 0 0.571429 1.071429 spline
}

$sequence "layer_reload_crouch_SECONDARY2_arms" "soldier_animations_anims\layer_reload_crouch_SECONDARY2_arms.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY2" "soldier_animations_anims\ReloadCrouch_SECONDARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY2" 1
	// delta
	// addlayer "layer_reload_crouch_SECONDARY2_arms"
}

$sequence "layer_reload_crouch_SECONDARY2_arms_loop" "soldier_animations_anims\layer_reload_crouch_SECONDARY2_arms_loop.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY2_loop" "soldier_animations_anims\ReloadCrouch_SECONDARY2_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY2_LOOP" 1
	loop
	// delta
	// addlayer "layer_reload_crouch_SECONDARY2_arms_loop"
}

$sequence "layer_reload_crouch_SECONDARY2_arms_end" "soldier_animations_anims\layer_reload_crouch_SECONDARY2_arms_end.smd" {
	fps 30
	hidden
}

$sequence "ReloadCrouch_SECONDARY2_end" "soldier_animations_anims\ReloadCrouch_SECONDARY2_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY2_END" 1
	// delta
	// addlayer "layer_reload_crouch_SECONDARY2_arms_end"
}

$sequence "a_SECONDARY2_reload_airwalk" "soldier_animations_anims\a_SECONDARY2_reload_airwalk.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY2" "soldier_animations_anims\layer_reload_arms_SECONDARY2.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_airwalk" "soldier_animations_anims\SECONDARY2_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY2" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2"
}

$sequence "layer_reload_arms_SECONDARY2_loop" "soldier_animations_anims\layer_reload_arms_SECONDARY2_loop.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_airwalk_loop" "soldier_animations_anims\SECONDARY2_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY2_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2_loop"
}

$sequence "layer_reload_arms_SECONDARY2_end" "soldier_animations_anims\layer_reload_arms_SECONDARY2_end.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_airwalk_end" "soldier_animations_anims\SECONDARY2_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY2_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2_end"
	fadeout 1
}

$sequence "a_SECONDARY2_reload_swim" "soldier_animations_anims\a_SECONDARY2_reload_swim.smd" {
	fps 30
}

$sequence "layer_reload_arms_SECONDARY2_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY2_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_swim" "soldier_animations_anims\SECONDARY2_reload_swim.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY2" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2_swim"
}

$sequence "layer_reload_arms_SECONDARY2_loop_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY2_loop_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_swim_loop" "soldier_animations_anims\SECONDARY2_reload_swim_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY2_LOOP" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2_loop_swim"
}

$sequence "layer_reload_arms_SECONDARY2_end_swim" "soldier_animations_anims\layer_reload_arms_SECONDARY2_end_swim.smd" {
	fps 30
	hidden
}

$sequence "SECONDARY2_reload_swim_end" "soldier_animations_anims\SECONDARY2_reload_swim_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY2_END" 1
	// delta
	// addlayer "layer_reload_arms_SECONDARY2_end_swim"
	fadeout 1
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_AttackStandMelee_arms" "soldier_animations_anims\layer_AttackStandMelee_arms.smd" {
	fps 30
	hidden
}

$sequence "Attack_Stand_MELEE" "soldier_animations_anims\Attack_Stand_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// delta
	blendlayer "layer_AttackStandMelee_arms" 0 0.125 0.875 1 spline
}

$sequence "layer_AttackCrouchMelee_arms" "soldier_animations_anims\layer_AttackCrouchMelee_arms.smd" {
	fps 30
	hidden
}

$sequence "Attack_Crouch_MELEE" "soldier_animations_anims\Attack_Crouch_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// delta
	blendlayer "layer_AttackCrouchMelee_arms" 0 0.125 0.875 1 spline
}

$sequence "armslayer_melee_Swim_swing" "soldier_animations_anims\armslayer_melee_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swim_Swing" "soldier_animations_anims\bodylayer_Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swim_Swing" "soldier_animations_anims\Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// addlayer "bodylayer_Melee_Swim_Swing"
	// addlayer "armslayer_melee_Swim_swing"
}

$sequence "stand_PRIMARY" "soldier_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "soldier_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "soldier_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "soldier_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "soldier_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_SECONDARY2" "soldier_animations_anims\stand_SECONDARY2.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY2" 1
	loop
	// addlayer "SECONDARY2_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "soldier_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "soldier_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "soldier_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "soldier_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "soldier_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_SECONDARY2" "soldier_animations_anims\crouch_SECONDARY2.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY2" 1
	loop
	// addlayer "SECONDARY2_aimmatrix_crouch_idle"
}

$sequence "jump_start_PRIMARY" "soldier_animations_anims\jump_start_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "layer_PRIMARY_jump_floatNoise" "soldier_animations_anims\layer_PRIMARY_jump_floatNoise.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	realtime
	hidden
}

$sequence "jump_float_PRIMARY" "soldier_animations_anims\jump_float_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
	// addlayer "layer_PRIMARY_jump_floatNoise"
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "jumpland_PRIMARY" "soldier_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "jump_start_SECONDARY" "soldier_animations_anims\jump_start_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "jump_float_SECONDARY" "soldier_animations_anims\jump_float_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
	// addlayer "layer_PRIMARY_jump_floatNoise"
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "jumpland_SECONDARY" "soldier_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "soldier_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "soldier_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "soldier_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "soldier_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "soldier_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "soldier_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "soldier_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "soldier_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "soldier_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "soldier_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "soldier_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "soldier_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "jump_start_SECONDARY2" "soldier_animations_anims\jump_start_SECONDARY2.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY2" 1
	// addlayer "SECONDARY2_aimmatrix_idle"
}

$sequence "jump_float_SECONDARY2" "soldier_animations_anims\jump_float_SECONDARY2.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY2" 1
	loop
	// addlayer "layer_PRIMARY_jump_floatNoise"
	// addlayer "SECONDARY2_aimmatrix_idle"
}

$sequence "jumpland_SECONDARY2" "soldier_animations_anims\jumpland_SECONDARY2.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY2" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "SECONDARY2_aimmatrix_swim" {
	"a_SECONDARY2_aimmatrix_swim_straight_up"
	"a_SECONDARY2_aimmatrix_swim_straight_up"
	"a_SECONDARY2_aimmatrix_swim_straight_up"
	"a_SECONDARY2_aimmatrix_swim_up_right"
	"a_SECONDARY2_aimmatrix_swim_up_center"
	"a_SECONDARY2_aimmatrix_swim_up_left"
	"a_SECONDARY2_aimmatrix_swim_mid_right"
	"a_SECONDARY2_aimmatrix_swim_mid_center"
	"a_SECONDARY2_aimmatrix_swim_mid_left"
	"a_SECONDARY2_aimmatrix_swim_down_right"
	"a_SECONDARY2_aimmatrix_swim_down_center"
	"a_SECONDARY2_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY2" {
	"a_swimCenter_SECONDARY2"
	fps 30
	loop
}

$sequence "swim_SECONDARY2" {
	"a_swimSW_SECONDARY2"
	"a_swimS_SECONDARY2"
	"a_swimSE_SECONDARY2"
	"a_swimW_SECONDARY2"
	"a_swimCenter_SECONDARY2"
	"a_swimE_SECONDARY2"
	"a_swimNW_SECONDARY2"
	"a_swimN_SECONDARY2"
	"a_swimNE_SECONDARY2"
	fps 30
	"ACT_MP_SWIM_SECONDARY2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY2_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_crouch_walk_SECONDARY"
	"a_crouch_walkS_crouch_walk_SECONDARY"
	"a_crouch_walkSE_crouch_walk_SECONDARY"
	"a_crouch_walkW_crouch_walk_SECONDARY"
	"a_crouch_walkCenter_crouch_walk_SECONDARY"
	"a_crouch_walkE_crouch_walk_SECONDARY"
	"a_crouch_walkNW_crouch_walk_SECONDARY"
	"a_crouch_walkN_crouch_walk_SECONDARY"
	"a_crouch_walkNE_crouch_walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "run_SECONDARY2" {
	"a_runSW_SECONDARY2"
	"a_runS_SECONDARY2"
	"a_runSE_SECONDARY2"
	"a_runW_SECONDARY2"
	"a_runCenter_SECONDARY2"
	"a_runE_SECONDARY2"
	"a_runNW_SECONDARY2"
	"a_runN_SECONDARY2"
	"a_runNE_SECONDARY2"
	fps 30
	"ACT_MP_RUN_SECONDARY2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY2_aimmatrix_run"
	{ event 7001 2.0000000372529 "right" }
	{ event 7001 11.0000005960464 "left" }
}

$sequence "crouch_walk_SECONDARY2" {
	"a_crouch_walkSW_crouch_walk_SECONDARY2"
	"a_crouch_walkS_crouch_walk_SECONDARY2"
	"a_crouch_walkSE_crouch_walk_SECONDARY2"
	"a_crouch_walkW_crouch_walk_SECONDARY2"
	"a_crouch_walkCenter_crouch_walk_SECONDARY2"
	"a_crouch_walkE_crouch_walk_SECONDARY2"
	"a_crouch_walkNW_crouch_walk_SECONDARY2"
	"a_crouch_walkN_crouch_walk_SECONDARY2"
	"a_crouch_walkNE_crouch_walk_SECONDARY2"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY2" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY2_aimmatrix_crouch_idle"
}

$sequence "airwalk_PRIMARY" "soldier_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_SECONDARY" "soldier_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "airwalk_MELEE" "soldier_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "airwalk_MELEE_ALLCLASS" "soldier_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "soldier_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_SECONDARY2" "soldier_animations_anims\airwalk_SECONDARY2.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY2" 1
	loop
	// addlayer "SECONDARY2_aimmatrix_idle"
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "layer_AttackStandMELEE_ALLCLASS_arms" "soldier_animations_anims\layer_AttackStandMELEE_ALLCLASS_arms.smd" {
	fps 30
	hidden
}

$sequence "Attack_Stand_MELEE_ALLCLASS" "soldier_animations_anims\Attack_Stand_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	// delta
	blendlayer "layer_AttackStandMELEE_ALLCLASS_arms" 0 0.125 0.875 1 spline
	// addlayer "r_handposes"
}

$sequence "layer_AttackCrouchMELEE_ALLCLASS_arms" "soldier_animations_anims\layer_AttackCrouchMELEE_ALLCLASS_arms.smd" {
	fps 30
	hidden
}

$sequence "Attack_Crouch_MELEE_ALLCLASS" "soldier_animations_anims\Attack_Crouch_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// delta
	blendlayer "layer_AttackCrouchMELEE_ALLCLASS_arms" 0 0.125 0.875 1 spline
	// addlayer "r_handposes"
}

$sequence "armslayer_MELEE_ALLCLASS_Swim_swing" "soldier_animations_anims\armslayer_MELEE_ALLCLASS_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_MELEE_ALLCLASS_Swim_Swing" "soldier_animations_anims\bodylayer_MELEE_ALLCLASS_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "MELEE_ALLCLASS_Swim_Swing" "soldier_animations_anims\MELEE_ALLCLASS_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_MELEE_ALLCLASS_Swim_Swing"
	// addlayer "armslayer_MELEE_ALLCLASS_Swim_swing"
	// addlayer "r_handposes"
}

$sequence "layer_gesture_item1_buglecall" "soldier_animations_anims\layer_gesture_item1_buglecall.smd" {
	fps 30
	hidden
}

$sequence "item1_buglecall_red" "soldier_animations_anims\item1_buglecall_red.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// delta
	// addlayer "layer_gesture_item1_buglecall"
}

$sequence "layer_gesture_item1_buglecall_blue" "soldier_animations_anims\layer_gesture_item1_buglecall_blue.smd" {
	fps 30
	hidden
}

$sequence "item1_buglecall_blue" "soldier_animations_anims\item1_buglecall_blue.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_item1_buglecall_blue"
}

$sequence "layer_gesture_item2_warhorncall" "soldier_animations_anims\layer_gesture_item2_warhorncall.smd" {
	fps 30
	hidden
}

$sequence "item2_warhorncall_red" "soldier_animations_anims\item2_warhorncall_red.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM2" 2
	// delta
	// addlayer "layer_gesture_item2_warhorncall"
}

$sequence "layer_gesture_item2_warhorncall_blue" "soldier_animations_anims\layer_gesture_item2_warhorncall_blue.smd" {
	fps 30
	hidden
}

$sequence "item2_warhorncall_blue" "soldier_animations_anims\item2_warhorncall_blue.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM2_SECONDARY" 2
	// delta
	// addlayer "layer_gesture_item2_warhorncall_blue"
}

$sequence "layer_placeSapper_ArmL" "soldier_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "soldier_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "primary_floatA" "soldier_animations_anims\primary_floatA.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
}

$sequence "primary_floatB" "soldier_animations_anims\primary_floatB.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
}

$sequence "primary_floatC" "soldier_animations_anims\primary_floatC.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
}

$sequence "primary_floatD" "soldier_animations_anims\primary_floatD.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
}

$sequence "layer_gesture_primary_go_armL" "soldier_animations_anims\layer_gesture_primary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_go" "soldier_animations_anims\gesture_primary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
}

$sequence "layer_gesture_primary_help_armL" "soldier_animations_anims\layer_gesture_primary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_help" "soldier_animations_anims\gesture_primary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_help_armL"
}

$sequence "layer_gesture_primary_cheer_armL" "soldier_animations_anims\layer_gesture_primary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_cheer" "soldier_animations_anims\gesture_primary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_cheer_armL"
}

$sequence "layer_gesture_primary_positive_armL" "soldier_animations_anims\layer_gesture_primary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_primary_positive" "soldier_animations_anims\gesture_primary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_PRIMARY" 1
	// delta
	// addlayer "layer_gesture_primary_positive_armL"
}

$sequence "layer_gesture_secondary_go_armL" "soldier_animations_anims\layer_gesture_secondary_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_go" "soldier_animations_anims\gesture_secondary_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
}

$sequence "layer_gesture_secondary_help_armL" "soldier_animations_anims\layer_gesture_secondary_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_help" "soldier_animations_anims\gesture_secondary_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_help_armL"
}

$sequence "layer_gesture_secondary_cheer_armL" "soldier_animations_anims\layer_gesture_secondary_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_cheer" "soldier_animations_anims\gesture_secondary_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_cheer_armL"
}

$sequence "layer_gesture_secondary_positive_armL" "soldier_animations_anims\layer_gesture_secondary_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_secondary_positive" "soldier_animations_anims\gesture_secondary_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_SECONDARY" 1
	// delta
	// addlayer "layer_gesture_secondary_positive_armL"
}

$sequence "layer_gesture_melee_go_armL" "soldier_animations_anims\layer_gesture_melee_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_go" "soldier_animations_anims\gesture_melee_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_go_armL"
}

$sequence "layer_gesture_melee_help_armL" "soldier_animations_anims\layer_gesture_melee_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_help" "soldier_animations_anims\gesture_melee_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_help_armL"
}

$sequence "layer_gesture_melee_cheer_armL" "soldier_animations_anims\layer_gesture_melee_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_cheer" "soldier_animations_anims\gesture_melee_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_cheer_armL"
}

$sequence "layer_gesture_melee_positive" "soldier_animations_anims\layer_gesture_melee_positive.smd" {
	fps 30
	hidden
}

$sequence "gesture_melee_positive" "soldier_animations_anims\gesture_melee_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_POSITIVE_MELEE" 1
	// delta
	// addlayer "layer_gesture_melee_positive"
}

$sequence "layer_PRIMARY_Stun_begin" "soldier_animations_anims\layer_PRIMARY_Stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "soldier_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_Stun_end" "soldier_animations_anims\layer_PRIMARY_Stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_Stun_begin" "soldier_animations_anims\PRIMARY_Stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_begin"
}

$sequence "PRIMARY_stun_middle" "soldier_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "soldier_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_Stun_end"
}

$sequence "layer_dieviolent" "soldier_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "soldier_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "primary_death_headshot" "soldier_animations_anims\primary_death_headshot.smd" {
	fps 30
}

$sequence "primary_death_backStab" "soldier_animations_anims\primary_death_backStab.smd" {
	fps 30
}

$sequence "primary_death_burning" "soldier_animations_anims\primary_death_burning.smd" {
	fps 30
}

$sequence "selectionMenu_StartPose" "soldier_animations_anims\selectionMenu_StartPose.smd" {
	fps 30
}

$sequence "selectionMenu_Idle" "soldier_animations_anims\selectionMenu_Idle.smd" {
	fps 30
	loop
}

$sequence "selectionMenu_Anim0l" "soldier_animations_anims\selectionMenu_Anim0l.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 20 "Selection.SoldierLauncherGrab" }
	{ event AE_CL_PLAYSOUND 24 "Selection.SoldierEquipment" }
	{ event AE_CL_PLAYSOUND 36 "Selection.SoldierClothesRustle" }
	{ event AE_CL_PLAYSOUND 47 "Selection.SoldierLauncherGrab" }
	{ event AE_CL_PLAYSOUND 64 "Selection.SoldierClothesRustle" }
	{ event AE_CL_PLAYSOUND 73 "Selection.SoldierLauncherGrab" }
	{ event AE_CL_PLAYSOUND 94 "Selection.SoldierLauncherSetStart" }
	{ event AE_CL_PLAYSOUND 103 "Selection.SoldierLauncherSetStop" }
	{ event AE_CL_PLAYSOUND 103 "Selection.SoldierLauncherHitGround" }
}

$sequence "armslayer_throw_fire" "soldier_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "soldier_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "soldier_animations_anims\layer_taunt01.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "soldier_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt01"
	{ event AE_WPN_HIDE 1.00000001862645 "" }
	{ event AE_WPN_UNHIDE 84 "" }
	{ event 5004 17.0000002384186 "Taunt.Soldier01ClothesSwipe" }
	{ event 5004 17.0000002384186 "Taunt.Soldier01HeelClick" }
	{ event 5004 47.0000009536743 "Taunt.Soldier01ClothesRustle" }
	{ event 5004 59.0000002384186 "Taunt.Soldier01HelmetJostle" }
}

$sequence "layer_taunt02" "soldier_animations_anims\layer_taunt02.smd" {
	fps 30
	hidden
}

$sequence "taunt02" "soldier_animations_anims\taunt02.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt02"
	{ event AE_CL_BODYGROUP_SET_VALUE 18.0000008940697 "rocket 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 125.999998569489 "rocket 0" }
	{ event AE_WPN_HIDE 0.99999999627471 "" }
	{ event AE_WPN_UNHIDE 129 "" }
	{ event 5004 71.0000030994415 "Taunt.Soldier02GrenadeCatch" }
	{ event 5004 85.0000020861626 "Taunt.Soldier02GrenadeCatch" }
	{ event 5004 101.000002026558 "Taunt.Soldier02GrenadeCatch" }
	{ event 5004 107.999997675419 "Taunt.Soldier02GrenadeCatch" }
	{ event 5004 63.9999997615814 "Taunt.Soldier02ShovelCatch" }
	{ event 5004 91.9999977350235 "Taunt.Soldier02ShovelCatch" }
	{ event 5004 11.0000004395843 "Taunt.Soldier02ClothesRustle" }
}

$sequence "layer_taunt03" "soldier_animations_anims\layer_taunt03.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "soldier_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt03"
	{ event 5004 27.0000001639128 "Taunt.Soldier03FootStomp" }
	{ event 5004 79.0000023841858 "Taunt.Soldier03HelmetHit" }
	{ event 5004 89.0000017881393 "Taunt.Soldier03HelmetHit" }
	{ event 5004 99.0000011920929 "Taunt.Soldier03HelmetHit" }
	{ event 5004 27.0000001639128 "Taunt.Soldier03ClothesRustle" }
	{ event 5004 60.000003516674 "Taunt.Soldier03ClothesSwipe" }
	{ event 5004 40.0000011622906 "Taunt.Soldier03HelmetJostle" }
}

$sequence "layer_taunt05" "soldier_animations_anims\layer_taunt05.smd" {
	fps 30
	hidden
}

$sequence "taunt05" "soldier_animations_anims\taunt05.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt05"
	{ event AE_WPN_HIDE 26.9999994188547 "" }
	{ event AE_WPN_UNHIDE 129 "" }
	{ event 5004 9.00000044703484 "Taunt.SoldierClothesRustle" }
	{ event 5004 31.9999998807907 "Taunt.SoldierKnuckleCrack" }
	{ event 5004 47.9999998211861 "Taunt.SoldierKnuckleCrack" }
	{ event 5004 70.0000026226044 "Taunt.SoldierGrenadePull" }
}

$sequence "taunt06" "soldier_animations_anims\taunt06.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.96 1 1 1 spline
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "layer_taunt07" "soldier_animations_anims\layer_taunt07.smd" {
	fps 30
	hidden
}

$sequence "taunt07" "soldier_animations_anims\taunt07.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt07"
	{ event AE_WPN_HIDE 1.00000002980232 "" }
	{ event AE_WPN_UNHIDE 87.0000009536743 "" }
	{ event 5004 12.0000003576279 "Taunt.TauntChestThumpYell" }
	{ event 5004 35.9999997615814 "Taunt.SoldierChestThump" }
	{ event 5004 41.9999992847443 "Taunt.SoldierChestThumpAlt" }
	{ event 5004 49.9999995231628 "Taunt.SoldierChestThump" }
	{ event 5004 55 "Taunt.SoldierChestThumpAlt" }
	{ event 5004 61.9999985694885 "Taunt.SoldierChestThump" }
	{ event 5004 65.0000009536743 "Taunt.SoldierChestThumpLow" }
	{ event 5004 67.9999980926514 "Taunt.SoldierChestThumpLow" }
	{ event 5004 73.9999976158142 "Taunt.SoldierChestThumpLow" }
}

$sequence "layer_taunt04" "soldier_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "soldier_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
	{ event 5004 1.99999998509884 "Taunt.SoldierTaps" }
	{ event 5004 11.999999910593 "Taunt.SoldierShotgunFire" }
	{ event 5004 27.9999997913837 "Taunt.SoldierShotgunCockBack" }
	{ event 5004 30.0000008642673 "Taunt.SoldierShotgunCockForward" }
	{ event 5004 44.9999980330467 "Taunt.SoldierShotgunFire" }
	{ event 5004 60.0000017285347 "Taunt.SoldierShotgunCockBack" }
	{ event 5004 62.999998986721 "Taunt.SoldierShotgunCockForward" }
	{ event 5004 75.0000010728836 "Taunt.SoldierShotgunFire" }
	{ event 5004 89.9999960660934 "Taunt.SoldierSaluteSwish" }
	{ event 5004 95.9999992847443 "Taunt.Heavy03EquipmentJingleShort" }
}

$sequence "layer_taunt08" "soldier_animations_anims\layer_taunt08.smd" {
	fps 30
	hidden
}

$sequence "taunt08" "soldier_animations_anims\taunt08.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt08"
	{ event AE_WPN_HIDE 0.999999968335032 "" }
	{ event AE_WPN_UNHIDE 109.000000953674 "" }
	{ event 5004 17.9999992251396 "Taunt.Soldier03FootStomp" }
	{ event 5004 20.0000005960464 "Taunt.Soldier03FootStomp" }
	{ event 5004 38.9999988675117 "Taunt.Soldier03HelmetHit" }
	{ event 5004 48.999999165535 "Taunt.Soldier01HeelClick" }
	{ event 5004 55.9999990463257 "Taunt.Soldier01HeelClick" }
	{ event 5004 75.9999996423721 "Taunt.Soldier03FootStomp" }
	{ event 5004 83.9999985694885 "Taunt.Soldier03FootStomp" }
}

$sequence "layer_taunt09" "soldier_animations_anims\layer_taunt09.smd" {
	fps 30
	hidden
}

$sequence "taunt09" "soldier_animations_anims\taunt09.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt09"
	{ event AE_WPN_HIDE 1.00000003818423 "" }
	{ event AE_WPN_UNHIDE 104.000000059605 "" }
}

$sequence "layer_Soldier_replay_taunt" "soldier_animations_anims\layer_Soldier_replay_taunt.smd" {
	fps 30
	hidden
}

$sequence "Soldier_replay_taunt" "soldier_animations_anims\Soldier_replay_taunt.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_Soldier_replay_taunt"
	{ event AE_WPN_HIDE 1.00000001862645 "" }
	{ event AE_WPN_UNHIDE 84 "" }
	{ event 5004 22.9999998807907 "Taunt.Soldier01ClothesSwipe" }
	{ event 5004 17.0000002384186 "Taunt.Soldier01HeelClick" }
}

$sequence "layer_taunt_laugh" "soldier_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "soldier_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.99999999627471 "" }
	{ event AE_WPN_UNHIDE 145 "" }
}

$sequence "taunt_brutallegendinterior" "soldier_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "soldier_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "soldier_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "soldier_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "soldier_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "soldier_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_highFiveStart" "soldier_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "taunt_highFiveStart_idle" "soldier_animations_anims\taunt_highFiveStart_idle.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 46 "" }
}

$sequence "layer_taunt_highfiveSuccess" "soldier_animations_anims\layer_taunt_highfiveSuccess.smd" {
	fps 30
	hidden
}

$sequence "taunt_highfiveSuccess" "soldier_animations_anims\taunt_highfiveSuccess.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highfiveSuccess"
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 123.999997973442 "" }
}

$sequence "layer_taunt_highfiveSuccessFull" "soldier_animations_anims\layer_taunt_highfiveSuccessFull.smd" {
	fps 30
	hidden
}

$sequence "taunt_highfiveSuccessFull" "soldier_animations_anims\taunt_highfiveSuccessFull.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highfiveSuccessFull"
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 123.999997973442 "" }
}

$sequence "taunt_conga" "soldier_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "soldier_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "soldier_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 0.999999962747097 "" }
	{ event AE_WPN_UNHIDE 241.999994695187 "" }
	{ event AE_CL_PLAYSOUND 100.000003695488 "Taunt.MedicHardClap3" }
}

$sequence "layer_taunt_dosido_intro" "soldier_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "soldier_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
	{ event AE_CL_PLAYSOUND 48.9999992847443 "Taunt.MedicHardClap4" }
	{ event AE_CL_PLAYSOUND 79.9999973773956 "Taunt.MedicHardClap5" }
	{ event AE_CL_PLAYSOUND 85.0000016689301 "Taunt.MedicHardClap5" }
}

$sequence "taunt_flip_start" "soldier_animations_anims\taunt_flip_start.smd" {
	fps 35
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "soldier_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "soldier_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 1.00000000325963 "" }
	{ event AE_WPN_UNHIDE 122.000001251698 "" }
}

$sequence "layer_taunt_flip_success_receiver" "soldier_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "soldier_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 0.999999954365194 "" }
	{ event AE_WPN_UNHIDE 109.000000059605 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 37.0000007748604 "taunt_flip_trail follow_attachment back_lower" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 57.9999971389771 "taunt_flip_land follow_attachment foot_L" }
}

$sequence "taunt_rps_start" "soldier_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "soldier_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "soldier_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_paper" "soldier_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "soldier_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_scissors" "soldier_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "soldier_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103 "" }
}

$sequence "layer_taunt_rps_rock_win" "soldier_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "soldier_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_paper_win" "soldier_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "soldier_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_scissors_win" "soldier_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "soldier_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 198.999994874001 "" }
}

$sequence "layer_taunt_rps_rock_lose" "soldier_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "soldier_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_paper_lose" "soldier_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "soldier_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "soldier_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "soldier_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_rock_lose2" "soldier_animations_anims\layer_taunt_rps_rock_lose2.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose2" "soldier_animations_anims\taunt_rps_rock_lose2.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose2"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_paper_lose2" "soldier_animations_anims\layer_taunt_rps_paper_lose2.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose2" "soldier_animations_anims\taunt_rps_paper_lose2.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose2"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_rps_scissors_lose2" "soldier_animations_anims\layer_taunt_rps_scissors_lose2.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose2" "soldier_animations_anims\taunt_rps_scissors_lose2.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose2"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 205.000000953674 "" }
}

$sequence "layer_taunt_headbutt_start" "soldier_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "soldier_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 144 "" }
}

$sequence "layer_taunt_headbutt_success" "soldier_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "soldier_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55.9999980032444 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 135 "" }
}

$sequence "layer_taunt_coffee" "soldier_animations_anims\layer_taunt_coffee.smd" {
	fps 30
	hidden
}

$sequence "taunt_coffee" "soldier_animations_anims\taunt_coffee.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_coffee"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 6.00000008940697 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1.99999993108213 "taunt_soldier_coffee_cup follow_attachment weapon_bone_L" }
	{ event AE_WPN_HIDE 149.999997496605 "" }
}

$ikchain "rhand" "bip_hand_R" knee 0.841 0.541 0.005
$ikchain "lhand" "bip_hand_L" knee 0.788 -0.616 0.005
$ikchain "rfoot" "bip_foot_R" knee 0.6 -0.8 -0.003
$ikchain "lfoot" "bip_foot_L" knee 0.554 0.002 0.832

