// Created by Crowbar 0.19.0.0

$modelname "player/demo_animations.mdl"

$poseparameter "body_pitch" -45 90 360
$poseparameter "body_yaw" -45 45 360
$poseparameter "r_hand_grip" 0 14 0
$poseparameter "r_arm" 0 1 0
$poseparameter "move_y" -1 1 0
$poseparameter "move_x" -1 1 0

$cdmaterials "models\player\demo\"

$surfaceprop "default"

$contents "solid"



$sectionframes 30 119

$animation "a_reference" "demo_animations_anims\a_reference.smd" {
	fps 30
}
$animation "SPELL_hand_pose" "demo_animations_anims\SPELL_hand_pose.smd" {
	fps 30
}
$animation "SPELL_arm_pose" "demo_animations_anims\SPELL_arm_pose.smd" {
	fps 30
}
$animation "saxxy_pose" "demo_animations_anims\saxxy_pose.smd" {
	fps 30
}
$animation "bread_bagged_pose" "demo_animations_anims\bread_bagged_pose.smd" {
	fps 30
}
$animation "bread_baguette_pose" "demo_animations_anims\bread_baguette_pose.smd" {
	fps 30
}
$animation "bread_burnt_pose" "demo_animations_anims\bread_burnt_pose.smd" {
	fps 30
}
$animation "bread_cinnamon_pose" "demo_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
}
$animation "bread_cornbread_pose" "demo_animations_anims\bread_cornbread_pose.smd" {
	fps 30
}
$animation "bread_crumpet_pose" "demo_animations_anims\bread_crumpet_pose.smd" {
	fps 30
}
$animation "bread_pretzel_pose" "demo_animations_anims\bread_pretzel_pose.smd" {
	fps 30
}
$animation "bread_ration_pose" "demo_animations_anims\bread_ration_pose.smd" {
	fps 30
}
$animation "bread_robo_pose" "demo_animations_anims\bread_robo_pose.smd" {
	fps 30
}
$animation "bread_russianblack_pose" "demo_animations_anims\bread_russianblack_pose.smd" {
	fps 30
}
$animation "bread_shortbread_pose" "demo_animations_anims\bread_shortbread_pose.smd" {
	fps 30
}
$animation "bread_monster_pose" "demo_animations_anims\bread_monster_pose.smd" {
	fps 30
}
$animation "MELEE_allclass_idle_arm" "demo_animations_anims\MELEE_allclass_idle_arm.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_neutral" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_idle_down_right" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_center" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_down_left" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_right" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_center" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_mid_left" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_right" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_center" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_up_left" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_idle_straight_up" "demo_animations_anims\a_PRIMARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_neutral" "demo_animations_anims\a_PRIMARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_run_down_right" "demo_animations_anims\a_PRIMARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_center" "demo_animations_anims\a_PRIMARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_down_left" "demo_animations_anims\a_PRIMARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_right" "demo_animations_anims\a_PRIMARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_center" "demo_animations_anims\a_PRIMARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_mid_left" "demo_animations_anims\a_PRIMARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_right" "demo_animations_anims\a_PRIMARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_center" "demo_animations_anims\a_PRIMARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_up_left" "demo_animations_anims\a_PRIMARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_run_straight_up" "demo_animations_anims\a_PRIMARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_neutral" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_right" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_center" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_down_left" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_right" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_center" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_mid_left" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_right" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_center" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_up_left" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_crouch_idle_straight_up" "demo_animations_anims\a_PRIMARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_neutral" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_idle_down_right" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_center" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_down_left" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_right" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_center" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_mid_left" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_right" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_center" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_up_left" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_idle_straight_up" "demo_animations_anims\a_SECONDARY_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_neutral" "demo_animations_anims\a_SECONDARY_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_run_down_right" "demo_animations_anims\a_SECONDARY_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_center" "demo_animations_anims\a_SECONDARY_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_down_left" "demo_animations_anims\a_SECONDARY_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_right" "demo_animations_anims\a_SECONDARY_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_center" "demo_animations_anims\a_SECONDARY_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_mid_left" "demo_animations_anims\a_SECONDARY_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_right" "demo_animations_anims\a_SECONDARY_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_center" "demo_animations_anims\a_SECONDARY_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_up_left" "demo_animations_anims\a_SECONDARY_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_run_straight_up" "demo_animations_anims\a_SECONDARY_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_neutral" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_right" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_center" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_down_left" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_right" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_center" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_mid_left" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_right" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_center" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_up_left" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_crouch_idle_straight_up" "demo_animations_anims\a_SECONDARY_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_stun_startpose" "demo_animations_anims\a_stun_startpose.smd" {
	fps 30
}
$animation "a_stun_endpose" "demo_animations_anims\a_stun_endpose.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_neutral" "demo_animations_anims\a_MELEE_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_idle_down_right" "demo_animations_anims\a_MELEE_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_center" "demo_animations_anims\a_MELEE_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_down_left" "demo_animations_anims\a_MELEE_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_right" "demo_animations_anims\a_MELEE_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_center" "demo_animations_anims\a_MELEE_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_mid_left" "demo_animations_anims\a_MELEE_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_right" "demo_animations_anims\a_MELEE_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_center" "demo_animations_anims\a_MELEE_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_up_left" "demo_animations_anims\a_MELEE_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_idle_straight_up" "demo_animations_anims\a_MELEE_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_neutral" "demo_animations_anims\a_MELEE_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_run_down_right" "demo_animations_anims\a_MELEE_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_center" "demo_animations_anims\a_MELEE_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_down_left" "demo_animations_anims\a_MELEE_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_right" "demo_animations_anims\a_MELEE_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_center" "demo_animations_anims\a_MELEE_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_mid_left" "demo_animations_anims\a_MELEE_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_right" "demo_animations_anims\a_MELEE_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_center" "demo_animations_anims\a_MELEE_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_up_left" "demo_animations_anims\a_MELEE_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_run_straight_up" "demo_animations_anims\a_MELEE_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_neutral" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_right" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_center" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_down_left" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_right" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_center" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_mid_left" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_right" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_center" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_up_left" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_crouch_idle_straight_up" "demo_animations_anims\a_MELEE_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_neutral" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_down_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_mid_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_up_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_idle_straight_up" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_neutral" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_down_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_mid_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_up_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_run_straight_up" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_Melee_Swing" "demo_animations_anims\a_Melee_Swing.smd" {
	fps 30
}
$animation "a_Melee_Crouch_Swing" "demo_animations_anims\a_Melee_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Melee_Swim_Swing" "demo_animations_anims\a_Melee_Swim_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Swing" "demo_animations_anims\a_Melee_allclass_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Crouch_Swing" "demo_animations_anims\a_Melee_allclass_Crouch_Swing.smd" {
	fps 30
}
$animation "a_Melee_allclass_Swim_Swing" "demo_animations_anims\a_Melee_allclass_Swim_Swing.smd" {
	fps 30
}
$animation "a_ITEM1_swing" "demo_animations_anims\a_ITEM1_swing.smd" {
	fps 30
}
$animation "a_ITEM1_crouch_swing" "demo_animations_anims\a_ITEM1_crouch_swing.smd" {
	fps 30
}
$animation "a_ITEM1_swim_swing" "demo_animations_anims\a_ITEM1_swim_swing.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_neutral" "demo_animations_anims\a_ITEM1_aimmatrix_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_idle_down_right" "demo_animations_anims\a_ITEM1_aimmatrix_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_center" "demo_animations_anims\a_ITEM1_aimmatrix_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_down_left" "demo_animations_anims\a_ITEM1_aimmatrix_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_right" "demo_animations_anims\a_ITEM1_aimmatrix_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_center" "demo_animations_anims\a_ITEM1_aimmatrix_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_mid_left" "demo_animations_anims\a_ITEM1_aimmatrix_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_right" "demo_animations_anims\a_ITEM1_aimmatrix_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_center" "demo_animations_anims\a_ITEM1_aimmatrix_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_up_left" "demo_animations_anims\a_ITEM1_aimmatrix_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_idle_straight_up" "demo_animations_anims\a_ITEM1_aimmatrix_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_neutral" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_right" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_center" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_down_left" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_right" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_center" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_mid_left" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_right" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_center" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_up_left" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_crouch_idle_straight_up" "demo_animations_anims\a_ITEM1_aimmatrix_crouch_idle_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_neutral" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_swim_down_right" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_center" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_down_left" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_right" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_center" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_mid_left" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_right" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_center" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_up_left" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_swim_straight_up" "demo_animations_anims\a_PRIMARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_PRIMARY" "demo_animations_anims\a_swimCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_PRIMARY" "demo_animations_anims\a_swimS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_PRIMARY" "demo_animations_anims\a_swimSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_PRIMARY" "demo_animations_anims\a_swimE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_PRIMARY" "demo_animations_anims\a_swimNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_PRIMARY" "demo_animations_anims\a_swimN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_PRIMARY" "demo_animations_anims\a_swimNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_PRIMARY" "demo_animations_anims\a_swimW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_PRIMARY" "demo_animations_anims\a_swimSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_SECONDARY_aimmatrix_swim_neutral" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_SECONDARY_aimmatrix_swim_down_right" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_center" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_down_left" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_right" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_center" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_mid_left" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_right" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_center" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_up_left" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_SECONDARY_aimmatrix_swim_straight_up" "demo_animations_anims\a_SECONDARY_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_SECONDARY" "demo_animations_anims\a_swimCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimS_SECONDARY" "demo_animations_anims\a_swimS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSE_SECONDARY" "demo_animations_anims\a_swimSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimE_SECONDARY" "demo_animations_anims\a_swimE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNE_SECONDARY" "demo_animations_anims\a_swimNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimN_SECONDARY" "demo_animations_anims\a_swimN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimNW_SECONDARY" "demo_animations_anims\a_swimNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimW_SECONDARY" "demo_animations_anims\a_swimW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_swimSW_SECONDARY" "demo_animations_anims\a_swimSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_MELEE_aimmatrix_swim_neutral" "demo_animations_anims\a_MELEE_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_aimmatrix_swim_down_right" "demo_animations_anims\a_MELEE_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_center" "demo_animations_anims\a_MELEE_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_down_left" "demo_animations_anims\a_MELEE_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_right" "demo_animations_anims\a_MELEE_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_center" "demo_animations_anims\a_MELEE_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_mid_left" "demo_animations_anims\a_MELEE_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_right" "demo_animations_anims\a_MELEE_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_center" "demo_animations_anims\a_MELEE_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_up_left" "demo_animations_anims\a_MELEE_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_aimmatrix_swim_straight_up" "demo_animations_anims\a_MELEE_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE" "demo_animations_anims\a_swimCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE" "demo_animations_anims\a_swimS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE" "demo_animations_anims\a_swimSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE" "demo_animations_anims\a_swimE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE" "demo_animations_anims\a_swimNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE" "demo_animations_anims\a_swimN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE" "demo_animations_anims\a_swimNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE" "demo_animations_anims\a_swimW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE" "demo_animations_anims\a_swimSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_neutral" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_down_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_mid_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_right" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_center" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_up_left" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_MELEE_ALLCLASS_aimmatrix_swim_straight_up" "demo_animations_anims\a_MELEE_ALLCLASS_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_MELEE_ALLCLASS" "demo_animations_anims\a_swimCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimS_MELEE_ALLCLASS" "demo_animations_anims\a_swimS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSE_MELEE_ALLCLASS" "demo_animations_anims\a_swimSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimE_MELEE_ALLCLASS" "demo_animations_anims\a_swimE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNE_MELEE_ALLCLASS" "demo_animations_anims\a_swimNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimN_MELEE_ALLCLASS" "demo_animations_anims\a_swimN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimNW_MELEE_ALLCLASS" "demo_animations_anims\a_swimNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimW_MELEE_ALLCLASS" "demo_animations_anims\a_swimW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_swimSW_MELEE_ALLCLASS" "demo_animations_anims\a_swimSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_swim_neutral" "demo_animations_anims\a_ITEM1_aimmatrix_swim_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_swim_down_right" "demo_animations_anims\a_ITEM1_aimmatrix_swim_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_center" "demo_animations_anims\a_ITEM1_aimmatrix_swim_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_down_left" "demo_animations_anims\a_ITEM1_aimmatrix_swim_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_right" "demo_animations_anims\a_ITEM1_aimmatrix_swim_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_center" "demo_animations_anims\a_ITEM1_aimmatrix_swim_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_mid_left" "demo_animations_anims\a_ITEM1_aimmatrix_swim_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_right" "demo_animations_anims\a_ITEM1_aimmatrix_swim_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_center" "demo_animations_anims\a_ITEM1_aimmatrix_swim_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_up_left" "demo_animations_anims\a_ITEM1_aimmatrix_swim_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_swim_straight_up" "demo_animations_anims\a_ITEM1_aimmatrix_swim_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_swimCenter_ITEM1" "demo_animations_anims\a_swimCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimS_ITEM1" "demo_animations_anims\a_swimS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSE_ITEM1" "demo_animations_anims\a_swimSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimE_ITEM1" "demo_animations_anims\a_swimE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNE_ITEM1" "demo_animations_anims\a_swimNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimN_ITEM1" "demo_animations_anims\a_swimN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimNW_ITEM1" "demo_animations_anims\a_swimNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimW_ITEM1" "demo_animations_anims\a_swimW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimSW_ITEM1" "demo_animations_anims\a_swimSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_swimCenter_LOSER" "demo_animations_anims\a_swimCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimS_LOSER" "demo_animations_anims\a_swimS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSE_LOSER" "demo_animations_anims\a_swimSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimE_LOSER" "demo_animations_anims\a_swimE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNE_LOSER" "demo_animations_anims\a_swimNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimN_LOSER" "demo_animations_anims\a_swimN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimNW_LOSER" "demo_animations_anims\a_swimNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimW_LOSER" "demo_animations_anims\a_swimW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_swimSW_LOSER" "demo_animations_anims\a_swimSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runCenter_PRIMARY" "demo_animations_anims\a_runCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runS_PRIMARY" "demo_animations_anims\a_runS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_PRIMARY" "demo_animations_anims\a_runSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runE_PRIMARY" "demo_animations_anims\a_runE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_PRIMARY" "demo_animations_anims\a_runNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runN_PRIMARY" "demo_animations_anims\a_runN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_PRIMARY" "demo_animations_anims\a_runNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runW_PRIMARY" "demo_animations_anims\a_runW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_PRIMARY" "demo_animations_anims\a_runSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkCenter_PRIMARY" "demo_animations_anims\a_crouch_walkCenter_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_PRIMARY" "demo_animations_anims\a_crouch_walkS_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_PRIMARY" "demo_animations_anims\a_crouch_walkSE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_PRIMARY" "demo_animations_anims\a_crouch_walkE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_PRIMARY" "demo_animations_anims\a_crouch_walkNE_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_PRIMARY" "demo_animations_anims\a_crouch_walkN_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_PRIMARY" "demo_animations_anims\a_crouch_walkNW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_PRIMARY" "demo_animations_anims\a_crouch_walkW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_PRIMARY" "demo_animations_anims\a_crouch_walkSW_PRIMARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_SECONDARY" "demo_animations_anims\a_runCenter_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runS_SECONDARY" "demo_animations_anims\a_runS_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSE_SECONDARY" "demo_animations_anims\a_runSE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runE_SECONDARY" "demo_animations_anims\a_runE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNE_SECONDARY" "demo_animations_anims\a_runNE_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runN_SECONDARY" "demo_animations_anims\a_runN_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runNW_SECONDARY" "demo_animations_anims\a_runNW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runW_SECONDARY" "demo_animations_anims\a_runW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runSW_SECONDARY" "demo_animations_anims\a_runSW_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_SECONDARY" "demo_animations_anims\a_blend_crouchN_crouch_walk_SECONDARY.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkCenter_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkS_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkSE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkNE_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkN_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkNW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_SECONDARY" "demo_animations_anims\a_crouch_walkSW_crouch_walk_SECONDARY.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE" "demo_animations_anims\a_runCenter_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE" "demo_animations_anims\a_runS_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE" "demo_animations_anims\a_runSE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE" "demo_animations_anims\a_runE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE" "demo_animations_anims\a_runNE_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE" "demo_animations_anims\a_runN_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE" "demo_animations_anims\a_runNW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE" "demo_animations_anims\a_runW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE" "demo_animations_anims\a_runSW_MELEE.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE" "demo_animations_anims\a_blend_crouchN_crouch_walk_MELEE.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkS_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkSE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkNE_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkN_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkNW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE" "demo_animations_anims\a_crouch_walkSW_crouch_walk_MELEE.smd" {
	fps 30
	loop
}
$animation "a_runCenter_MELEE_ALLCLASS" "demo_animations_anims\a_runCenter_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runS_MELEE_ALLCLASS" "demo_animations_anims\a_runS_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSE_MELEE_ALLCLASS" "demo_animations_anims\a_runSE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runE_MELEE_ALLCLASS" "demo_animations_anims\a_runE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNE_MELEE_ALLCLASS" "demo_animations_anims\a_runNE_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runN_MELEE_ALLCLASS" "demo_animations_anims\a_runN_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runNW_MELEE_ALLCLASS" "demo_animations_anims\a_runNW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runW_MELEE_ALLCLASS" "demo_animations_anims\a_runW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runSW_MELEE_ALLCLASS" "demo_animations_anims\a_runSW_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_blend_crouchN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkS_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkN_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS" "demo_animations_anims\a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}
$animation "a_runCenter_LOSER" "demo_animations_anims\a_runCenter_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runS_LOSER" "demo_animations_anims\a_runS_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSE_LOSER" "demo_animations_anims\a_runSE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runE_LOSER" "demo_animations_anims\a_runE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNE_LOSER" "demo_animations_anims\a_runNE_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runN_LOSER" "demo_animations_anims\a_runN_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runNW_LOSER" "demo_animations_anims\a_runNW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runW_LOSER" "demo_animations_anims\a_runW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_runSW_LOSER" "demo_animations_anims\a_runSW_LOSER.smd" {
	fps 30
	loop
}
$animation "a_ITEM1_aimmatrix_run_neutral" "demo_animations_anims\a_ITEM1_aimmatrix_run_neutral.smd" {
	fps 30
}
$animation "a_ITEM1_aimmatrix_run_down_right" "demo_animations_anims\a_ITEM1_aimmatrix_run_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_center" "demo_animations_anims\a_ITEM1_aimmatrix_run_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_down_left" "demo_animations_anims\a_ITEM1_aimmatrix_run_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_right" "demo_animations_anims\a_ITEM1_aimmatrix_run_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_center" "demo_animations_anims\a_ITEM1_aimmatrix_run_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_mid_left" "demo_animations_anims\a_ITEM1_aimmatrix_run_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_right" "demo_animations_anims\a_ITEM1_aimmatrix_run_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_center" "demo_animations_anims\a_ITEM1_aimmatrix_run_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_up_left" "demo_animations_anims\a_ITEM1_aimmatrix_run_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_ITEM1_aimmatrix_run_straight_up" "demo_animations_anims\a_ITEM1_aimmatrix_run_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_runCenter_ITEM1" "demo_animations_anims\a_runCenter_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runS_ITEM1" "demo_animations_anims\a_runS_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSE_ITEM1" "demo_animations_anims\a_runSE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runE_ITEM1" "demo_animations_anims\a_runE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNE_ITEM1" "demo_animations_anims\a_runNE_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runN_ITEM1" "demo_animations_anims\a_runN_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runNW_ITEM1" "demo_animations_anims\a_runNW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runW_ITEM1" "demo_animations_anims\a_runW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_runSW_ITEM1" "demo_animations_anims\a_runSW_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_blend_crouchN_crouch_walk_ITEM1" "demo_animations_anims\a_blend_crouchN_crouch_walk_ITEM1.smd" {
	fps 30
}
$animation "a_crouch_walkCenter_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkCenter_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkS_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkS_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSE_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkSE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkE_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNE_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkNE_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkN_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkN_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkNW_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkNW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkW_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_crouch_walkSW_crouch_walk_ITEM1" "demo_animations_anims\a_crouch_walkSW_crouch_walk_ITEM1.smd" {
	fps 30
	loop
}
$animation "a_PRIMARY_aimmatrix_airwalk_neutral" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_neutral.smd" {
	fps 30
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_right" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_center" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_down_left" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_down_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_right" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_center" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_mid_left" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_mid_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_right" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_right.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_center" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_center.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_up_left" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_up_left.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_PRIMARY_aimmatrix_airwalk_straight_up" "demo_animations_anims\a_PRIMARY_aimmatrix_airwalk_straight_up.smd" {
	fps 30
	// subtract "a_reference" 0
}
$animation "a_throw_fire" "demo_animations_anims\a_throw_fire.smd" {
	fps 30
}


$sequence "ragdollspawn" "demo_animations_anims\ragdollspawn.smd" {
	fps 30
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"SPELL_hand_pose"
	"@r_handposes"
	fps 30
	hidden
	blendwidth 14
	blend "r_hand_grip" 0 14
}

$sequence "r_armposes" {
	"MELEE_allclass_idle_arm"
	"SPELL_arm_pose"
	fps 30
	hidden
	blendwidth 2
	blend "r_arm" 0 1
}

$sequence "PRIMARY_aimmatrix_idle" {
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_straight_up"
	"a_PRIMARY_aimmatrix_idle_up_right"
	"a_PRIMARY_aimmatrix_idle_up_center"
	"a_PRIMARY_aimmatrix_idle_up_left"
	"a_PRIMARY_aimmatrix_idle_mid_right"
	"a_PRIMARY_aimmatrix_idle_mid_center"
	"a_PRIMARY_aimmatrix_idle_mid_left"
	"a_PRIMARY_aimmatrix_idle_down_right"
	"a_PRIMARY_aimmatrix_idle_down_center"
	"a_PRIMARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_run" {
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_straight_up"
	"a_PRIMARY_aimmatrix_run_up_right"
	"a_PRIMARY_aimmatrix_run_up_center"
	"a_PRIMARY_aimmatrix_run_up_left"
	"a_PRIMARY_aimmatrix_run_mid_right"
	"a_PRIMARY_aimmatrix_run_mid_center"
	"a_PRIMARY_aimmatrix_run_mid_left"
	"a_PRIMARY_aimmatrix_run_down_right"
	"a_PRIMARY_aimmatrix_run_down_center"
	"a_PRIMARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "PRIMARY_aimmatrix_crouch_idle" {
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_straight_up"
	"a_PRIMARY_aimmatrix_crouch_idle_up_right"
	"a_PRIMARY_aimmatrix_crouch_idle_up_center"
	"a_PRIMARY_aimmatrix_crouch_idle_up_left"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_right"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_center"
	"a_PRIMARY_aimmatrix_crouch_idle_mid_left"
	"a_PRIMARY_aimmatrix_crouch_idle_down_right"
	"a_PRIMARY_aimmatrix_crouch_idle_down_center"
	"a_PRIMARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_PRIMARY" "demo_animations_anims\AttackStand_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_PRIMARY" 1
	// delta
}

$sequence "AttackCrouch_PRIMARY" "demo_animations_anims\AttackCrouch_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_PRIMARY" 1
	// delta
}

$sequence "AttackSwim_PRIMARY" "demo_animations_anims\AttackSwim_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_PRIMARY" 1
	// delta
}

$sequence "a_PRIMARY_reload" "demo_animations_anims\a_PRIMARY_reload.smd" {
	fps 30
}

$sequence "PRIMARY_reload" "demo_animations_anims\PRIMARY_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_reload_loop" "demo_animations_anims\a_PRIMARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_reload_end" "demo_animations_anims\a_PRIMARY_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_PRIMARY_END" 1
	// delta
}

$sequence "a_PRIMARY_crouch_reload" "demo_animations_anims\a_PRIMARY_crouch_reload.smd" {
	fps 30
}

$sequence "PRIMARY_crouch_reload" "demo_animations_anims\PRIMARY_crouch_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_crouch_reload_loop" "demo_animations_anims\a_PRIMARY_crouch_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_crouch_reload_end" "demo_animations_anims\a_PRIMARY_crouch_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_PRIMARY_END" 1
	// delta
}

$sequence "a_PRIMARY_swim_reload" "demo_animations_anims\a_PRIMARY_swim_reload.smd" {
	fps 30
}

$sequence "PRIMARY_swim_reload" "demo_animations_anims\PRIMARY_swim_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_swim_reload_loop" "demo_animations_anims\a_PRIMARY_swim_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_swim_reload_end" "demo_animations_anims\a_PRIMARY_swim_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_PRIMARY_END" 1
	// delta
}

$sequence "a_PRIMARY_reload_airwalk" "demo_animations_anims\a_PRIMARY_reload_airwalk.smd" {
	fps 30
}

$sequence "PRIMARY_reload_airwalk" "demo_animations_anims\PRIMARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_reload_airwalk_loop" "demo_animations_anims\a_PRIMARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_PRIMARY_reload_airwalk_end" "demo_animations_anims\a_PRIMARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_PRIMARY_END" 1
	// delta
}

$sequence "a_flinch01" "demo_animations_anims\a_flinch01.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_FLINCH_CHEST" 1
	// delta
}

$sequence "layer_placeSapper_ArmL" "demo_animations_anims\layer_placeSapper_ArmL.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_placeSapper" "demo_animations_anims\PRIMARY_placeSapper.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_GRENADE" 1
	// delta
	// addlayer "layer_placeSapper_ArmL"
}

$sequence "SECONDARY_aimmatrix_idle" {
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_straight_up"
	"a_SECONDARY_aimmatrix_idle_up_right"
	"a_SECONDARY_aimmatrix_idle_up_center"
	"a_SECONDARY_aimmatrix_idle_up_left"
	"a_SECONDARY_aimmatrix_idle_mid_right"
	"a_SECONDARY_aimmatrix_idle_mid_center"
	"a_SECONDARY_aimmatrix_idle_mid_left"
	"a_SECONDARY_aimmatrix_idle_down_right"
	"a_SECONDARY_aimmatrix_idle_down_center"
	"a_SECONDARY_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_run" {
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_straight_up"
	"a_SECONDARY_aimmatrix_run_up_right"
	"a_SECONDARY_aimmatrix_run_up_center"
	"a_SECONDARY_aimmatrix_run_up_left"
	"a_SECONDARY_aimmatrix_run_mid_right"
	"a_SECONDARY_aimmatrix_run_mid_center"
	"a_SECONDARY_aimmatrix_run_mid_left"
	"a_SECONDARY_aimmatrix_run_down_right"
	"a_SECONDARY_aimmatrix_run_down_center"
	"a_SECONDARY_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "SECONDARY_aimmatrix_crouch_idle" {
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_straight_up"
	"a_SECONDARY_aimmatrix_crouch_idle_up_right"
	"a_SECONDARY_aimmatrix_crouch_idle_up_center"
	"a_SECONDARY_aimmatrix_crouch_idle_up_left"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_right"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_center"
	"a_SECONDARY_aimmatrix_crouch_idle_mid_left"
	"a_SECONDARY_aimmatrix_crouch_idle_down_right"
	"a_SECONDARY_aimmatrix_crouch_idle_down_center"
	"a_SECONDARY_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "AttackStand_SECONDARY" "demo_animations_anims\AttackStand_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_SECONDARY" 1
	// delta
}

$sequence "AttackCrouch_SECONDARY" "demo_animations_anims\AttackCrouch_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_SECONDARY" 1
	// delta
}

$sequence "AttackSwim_SECONDARY" "demo_animations_anims\AttackSwim_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_SECONDARY" 1
	// delta
}

$sequence "a_SECONDARY_reload" "demo_animations_anims\a_SECONDARY_reload.smd" {
	fps 30
}

$sequence "SECONDARY_reload" "demo_animations_anims\SECONDARY_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY" 1
	// delta
}

$sequence "SECONDARY_reload_loop" "demo_animations_anims\SECONDARY_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_LOOP" 1
	// delta
}

$sequence "a_SECONDARY_reload_end" "demo_animations_anims\a_SECONDARY_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_STAND_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_crouch_reload" "demo_animations_anims\a_SECONDARY_crouch_reload.smd" {
	fps 30
}

$sequence "SECONDARY_crouch_reload" "demo_animations_anims\SECONDARY_crouch_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_crouch_reload_loop" "demo_animations_anims\a_SECONDARY_crouch_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_crouch_reload_end" "demo_animations_anims\a_SECONDARY_crouch_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_CROUCH_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_swim_reload" "demo_animations_anims\a_SECONDARY_swim_reload.smd" {
	fps 30
}

$sequence "SECONDARY_swim_reload" "demo_animations_anims\SECONDARY_swim_reload.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_swim_reload_loop" "demo_animations_anims\a_SECONDARY_swim_reload_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_swim_reload_end" "demo_animations_anims\a_SECONDARY_swim_reload_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_SWIM_SECONDARY_END" 1
	// delta
}

$sequence "a_SECONDARY_reload_airwalk" "demo_animations_anims\a_SECONDARY_reload_airwalk.smd" {
	fps 30
}

$sequence "SECONDARY_reload_airwalk" "demo_animations_anims\SECONDARY_reload_airwalk.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_reload_airwalk_loop" "demo_animations_anims\a_SECONDARY_reload_airwalk_loop.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP" 1
	// delta
	hidden
}

$sequence "a_SECONDARY_reload_airwalk_end" "demo_animations_anims\a_SECONDARY_reload_airwalk_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_RELOAD_AIRWALK_SECONDARY_END" 1
	// delta
}

$sequence "layer_PRIMARY_stun_begin" "demo_animations_anims\layer_PRIMARY_stun_begin.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_middle" "demo_animations_anims\layer_PRIMARY_stun_middle.smd" {
	fps 30
	hidden
}

$sequence "layer_PRIMARY_stun_end" "demo_animations_anims\layer_PRIMARY_stun_end.smd" {
	fps 30
	hidden
}

$sequence "PRIMARY_stun_begin" "demo_animations_anims\PRIMARY_stun_begin.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_BEGIN" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_begin"
}

$sequence "PRIMARY_stun_middle" "demo_animations_anims\PRIMARY_stun_middle.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_MIDDLE" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_middle"
}

$sequence "PRIMARY_stun_end" "demo_animations_anims\PRIMARY_stun_end.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_STUN_END" 1
	snap
	// delta
	// addlayer "layer_PRIMARY_stun_end"
}

$sequence "MELEE_aimmatrix_idle" {
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_straight_up"
	"a_MELEE_aimmatrix_idle_up_right"
	"a_MELEE_aimmatrix_idle_up_center"
	"a_MELEE_aimmatrix_idle_up_left"
	"a_MELEE_aimmatrix_idle_mid_right"
	"a_MELEE_aimmatrix_idle_mid_center"
	"a_MELEE_aimmatrix_idle_mid_left"
	"a_MELEE_aimmatrix_idle_down_right"
	"a_MELEE_aimmatrix_idle_down_center"
	"a_MELEE_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_run" {
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_straight_up"
	"a_MELEE_aimmatrix_run_up_right"
	"a_MELEE_aimmatrix_run_up_center"
	"a_MELEE_aimmatrix_run_up_left"
	"a_MELEE_aimmatrix_run_mid_right"
	"a_MELEE_aimmatrix_run_mid_center"
	"a_MELEE_aimmatrix_run_mid_left"
	"a_MELEE_aimmatrix_run_down_right"
	"a_MELEE_aimmatrix_run_down_center"
	"a_MELEE_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_aimmatrix_crouch_idle" {
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_aimmatrix_crouch_idle_up_right"
	"a_MELEE_aimmatrix_crouch_idle_up_center"
	"a_MELEE_aimmatrix_crouch_idle_up_left"
	"a_MELEE_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_aimmatrix_crouch_idle_down_right"
	"a_MELEE_aimmatrix_crouch_idle_down_center"
	"a_MELEE_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "MELEE_ALLCLASS_aimmatrix_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
	// addlayer "r_armposes"
}

$sequence "MELEE_ALLCLASS_aimmatrix_run" {
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
	// addlayer "r_armposes"
}

$sequence "MELEE_ALLCLASS_aimmatrix_crouch_idle" {
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_handposes"
	// addlayer "r_armposes"
}

$sequence "armslayer_melee_swing" "demo_animations_anims\armslayer_melee_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swing" "demo_animations_anims\bodylayer_Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swing" "demo_animations_anims\Melee_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE" 1
	// addlayer "bodylayer_Melee_Swing"
	// addlayer "armslayer_melee_swing"
}

$sequence "armslayer_melee_Crouch_swing" "demo_animations_anims\armslayer_melee_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Crouch_Swing" "demo_animations_anims\bodylayer_Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Crouch_Swing" "demo_animations_anims\Melee_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE" 1
	// addlayer "bodylayer_Melee_Crouch_Swing"
	// addlayer "armslayer_melee_Crouch_swing"
}

$sequence "armslayer_melee_Swim_swing" "demo_animations_anims\armslayer_melee_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_Swim_Swing" "demo_animations_anims\bodylayer_Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_Swim_Swing" "demo_animations_anims\Melee_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE" 1
	// addlayer "bodylayer_Melee_Swim_Swing"
	// addlayer "armslayer_melee_Swim_swing"
}

$sequence "armslayer_melee_allclass_swing" "demo_animations_anims\armslayer_melee_allclass_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Swing" "demo_animations_anims\bodylayer_Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Swing" "demo_animations_anims\Melee_allclass_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_Melee_allclass_Swing"
	// addlayer "armslayer_melee_allclass_swing"
	// addlayer "r_handposes"
}

$sequence "armslayer_melee_allclass_Crouch_swing" "demo_animations_anims\armslayer_melee_allclass_Crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Crouch_Swing" "demo_animations_anims\bodylayer_Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Crouch_Swing" "demo_animations_anims\Melee_allclass_Crouch_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_Melee_allclass_Crouch_Swing"
	// addlayer "armslayer_melee_allclass_Crouch_swing"
	// addlayer "r_handposes"
}

$sequence "armslayer_melee_allclass_Swim_swing" "demo_animations_anims\armslayer_melee_allclass_Swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_Melee_allclass_Swim_Swing" "demo_animations_anims\bodylayer_Melee_allclass_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "Melee_allclass_Swim_Swing" "demo_animations_anims\Melee_allclass_Swim_Swing.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS" 1
	// addlayer "bodylayer_Melee_allclass_Swim_Swing"
	// addlayer "armslayer_melee_allclass_Swim_swing"
	// addlayer "r_handposes"
}

$sequence "armslayer_ITEM1_swing" "demo_animations_anims\armslayer_ITEM1_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_swing" "demo_animations_anims\bodylayer_ITEM1_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "attackstand_ITEM1" "demo_animations_anims\attackstand_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_STAND_ITEM1" 1
	// addlayer "bodylayer_ITEM1_swing"
	// addlayer "armslayer_ITEM1_swing"
}

$sequence "armslayer_ITEM1_crouch_swing" "demo_animations_anims\armslayer_ITEM1_crouch_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_crouch_swing" "demo_animations_anims\bodylayer_ITEM1_crouch_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "attackcrouch_ITEM1" "demo_animations_anims\attackcrouch_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_CROUCH_ITEM1" 1
	// addlayer "bodylayer_ITEM1_crouch_swing"
	// addlayer "armslayer_ITEM1_crouch_swing"
}

$sequence "armslayer_ITEM1_swim_swing" "demo_animations_anims\armslayer_ITEM1_swim_swing.smd" {
	fps 30
	hidden
}

$sequence "bodylayer_ITEM1_swim_swing" "demo_animations_anims\bodylayer_ITEM1_swim_swing.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "attackswim_ITEM1" "demo_animations_anims\attackswim_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_ATTACK_SWIM_ITEM1" 1
	// addlayer "bodylayer_ITEM1_swim_swing"
	// addlayer "armslayer_ITEM1_swim_swing"
}

$sequence "ITEM1_aimmatrix_idle" {
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_straight_up"
	"a_ITEM1_aimmatrix_idle_up_right"
	"a_ITEM1_aimmatrix_idle_up_center"
	"a_ITEM1_aimmatrix_idle_up_left"
	"a_ITEM1_aimmatrix_idle_mid_right"
	"a_ITEM1_aimmatrix_idle_mid_center"
	"a_ITEM1_aimmatrix_idle_mid_left"
	"a_ITEM1_aimmatrix_idle_down_right"
	"a_ITEM1_aimmatrix_idle_down_center"
	"a_ITEM1_aimmatrix_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "ITEM1_aimmatrix_crouch_idle" {
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_straight_up"
	"a_ITEM1_aimmatrix_crouch_idle_up_right"
	"a_ITEM1_aimmatrix_crouch_idle_up_center"
	"a_ITEM1_aimmatrix_crouch_idle_up_left"
	"a_ITEM1_aimmatrix_crouch_idle_mid_right"
	"a_ITEM1_aimmatrix_crouch_idle_mid_center"
	"a_ITEM1_aimmatrix_crouch_idle_mid_left"
	"a_ITEM1_aimmatrix_crouch_idle_down_right"
	"a_ITEM1_aimmatrix_crouch_idle_down_center"
	"a_ITEM1_aimmatrix_crouch_idle_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "stand_PRIMARY" "demo_animations_anims\stand_PRIMARY.smd" {
	fps 30
	"ACT_MP_STAND_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_idle"
}

$sequence "stand_SECONDARY" "demo_animations_anims\stand_SECONDARY.smd" {
	fps 30
	"ACT_MP_STAND_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "stand_MELEE" "demo_animations_anims\stand_MELEE.smd" {
	fps 30
	"ACT_MP_STAND_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "stand_MELEE_ALLCLASS" "demo_animations_anims\stand_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_STAND_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "stand_LOSER" "demo_animations_anims\stand_LOSER.smd" {
	fps 30
	"ACT_MP_STAND_LOSERSTATE" 1
	loop
}

$sequence "stand_ITEM1" "demo_animations_anims\stand_ITEM1.smd" {
	fps 30
	"ACT_MP_STAND_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "crouch_PRIMARY" "demo_animations_anims\crouch_PRIMARY.smd" {
	fps 30
	"ACT_MP_CROUCH_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "crouch_SECONDARY" "demo_animations_anims\crouch_SECONDARY.smd" {
	fps 30
	"ACT_MP_CROUCH_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE" "demo_animations_anims\crouch_MELEE.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "crouch_MELEE_ALLCLASS" "demo_animations_anims\crouch_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_CROUCH_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "crouch_LOSER" "demo_animations_anims\crouch_LOSER.smd" {
	fps 30
	"ACT_MP_CROUCH_LOSERSTATE" 1
	loop
}

$sequence "crouch_ITEM1" "demo_animations_anims\crouch_ITEM1.smd" {
	fps 30
	"ACT_MP_CROUCH_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "a_jumpstart_PRIMARY" "demo_animations_anims\a_jumpstart_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_PRIMARY" 1
}

$sequence "a_jumpfloat_PRIMARY" "demo_animations_anims\a_jumpfloat_PRIMARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_PRIMARY" 1
	loop
}

$sequence "jumplandPose_PRIMARY" "demo_animations_anims\jumplandPose_PRIMARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_PRIMARY" "demo_animations_anims\jumpland_PRIMARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_PRIMARY" 1
	// delta
}

$sequence "a_jumpstart_SECONDARY" "demo_animations_anims\a_jumpstart_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_START_SECONDARY" 1
}

$sequence "a_jumpfloat_SECONDARY" "demo_animations_anims\a_jumpfloat_SECONDARY.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_SECONDARY" 1
	loop
}

$sequence "jumplandPose_SECONDARY" "demo_animations_anims\jumplandPose_SECONDARY.smd" {
	fps 30
	loop
}

$sequence "jumpland_SECONDARY" "demo_animations_anims\jumpland_SECONDARY.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_SECONDARY" 1
	// delta
}

$sequence "a_jumpstart_MELEE" "demo_animations_anims\a_jumpstart_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE" 1
}

$sequence "a_jumpfloat_MELEE" "demo_animations_anims\a_jumpfloat_MELEE.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE" 1
	loop
}

$sequence "jumplandPose_MELEE" "demo_animations_anims\jumplandPose_MELEE.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE" "demo_animations_anims\jumpland_MELEE.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE" 1
	// delta
}

$sequence "a_jumpstart_MELEE_ALLCLASS" "demo_animations_anims\a_jumpstart_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_START_MELEE_ALLCLASS" 1
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpfloat_MELEE_ALLCLASS" "demo_animations_anims\a_jumpfloat_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS" 1
	loop
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "jumplandPose_MELEE_ALLCLASS" "demo_animations_anims\jumplandPose_MELEE_ALLCLASS.smd" {
	fps 30
	loop
}

$sequence "jumpland_MELEE_ALLCLASS" "demo_animations_anims\jumpland_MELEE_ALLCLASS.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_MELEE_ALLCLASS" 1
	// delta
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "a_jumpstart_LOSER" "demo_animations_anims\a_jumpstart_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_START_LOSERSTATE" 1
}

$sequence "a_jumpfloat_LOSER" "demo_animations_anims\a_jumpfloat_LOSER.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_LOSERSTATE" 1
	loop
}

$sequence "jumplandPose_LOSER" "demo_animations_anims\jumplandPose_LOSER.smd" {
	fps 30
	loop
}

$sequence "jumpland_LOSER" "demo_animations_anims\jumpland_LOSER.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_LOSERSTATE" 1
	// delta
}

$sequence "a_jumpstart_ITEM1" "demo_animations_anims\a_jumpstart_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_START_ITEM1" 1
}

$sequence "a_jumpfloat_ITEM1" "demo_animations_anims\a_jumpfloat_ITEM1.smd" {
	fps 30
	"ACT_MP_JUMP_FLOAT_ITEM1" 1
	loop
}

$sequence "jumplandPose_ITEM1" "demo_animations_anims\jumplandPose_ITEM1.smd" {
	fps 30
	loop
}

$sequence "jumpland_ITEM1" "demo_animations_anims\jumpland_ITEM1.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_JUMP_LAND_ITEM1" 1
	// delta
}

$sequence "PRIMARY_aimmatrix_swim" {
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_straight_up"
	"a_PRIMARY_aimmatrix_swim_up_right"
	"a_PRIMARY_aimmatrix_swim_up_center"
	"a_PRIMARY_aimmatrix_swim_up_left"
	"a_PRIMARY_aimmatrix_swim_mid_right"
	"a_PRIMARY_aimmatrix_swim_mid_center"
	"a_PRIMARY_aimmatrix_swim_mid_left"
	"a_PRIMARY_aimmatrix_swim_down_right"
	"a_PRIMARY_aimmatrix_swim_down_center"
	"a_PRIMARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_PRIMARY" {
	"a_swimCenter_PRIMARY"
	fps 30
	loop
}

$sequence "swim_PRIMARY" {
	"a_swimSW_PRIMARY"
	"a_swimS_PRIMARY"
	"a_swimSE_PRIMARY"
	"a_swimW_PRIMARY"
	"a_swimCenter_PRIMARY"
	"a_swimE_PRIMARY"
	"a_swimNW_PRIMARY"
	"a_swimN_PRIMARY"
	"a_swimNE_PRIMARY"
	fps 30
	"ACT_MP_SWIM_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "SECONDARY_aimmatrix_swim" {
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_straight_up"
	"a_SECONDARY_aimmatrix_swim_up_right"
	"a_SECONDARY_aimmatrix_swim_up_center"
	"a_SECONDARY_aimmatrix_swim_up_left"
	"a_SECONDARY_aimmatrix_swim_mid_right"
	"a_SECONDARY_aimmatrix_swim_mid_center"
	"a_SECONDARY_aimmatrix_swim_mid_left"
	"a_SECONDARY_aimmatrix_swim_down_right"
	"a_SECONDARY_aimmatrix_swim_down_center"
	"a_SECONDARY_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_SECONDARY" {
	"a_swimCenter_SECONDARY"
	fps 30
	loop
}

$sequence "swim_SECONDARY" {
	"a_swimSW_SECONDARY"
	"a_swimS_SECONDARY"
	"a_swimSE_SECONDARY"
	"a_swimW_SECONDARY"
	"a_swimCenter_SECONDARY"
	"a_swimE_SECONDARY"
	"a_swimNW_SECONDARY"
	"a_swimN_SECONDARY"
	"a_swimNE_SECONDARY"
	fps 30
	"ACT_MP_SWIM_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_swim"
}

$sequence "MELEE_aimmatrix_swim" {
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_straight_up"
	"a_MELEE_aimmatrix_swim_up_right"
	"a_MELEE_aimmatrix_swim_up_center"
	"a_MELEE_aimmatrix_swim_up_left"
	"a_MELEE_aimmatrix_swim_mid_right"
	"a_MELEE_aimmatrix_swim_mid_center"
	"a_MELEE_aimmatrix_swim_mid_left"
	"a_MELEE_aimmatrix_swim_down_right"
	"a_MELEE_aimmatrix_swim_down_center"
	"a_MELEE_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_MELEE" {
	"a_swimCenter_MELEE"
	fps 30
	loop
}

$sequence "swim_MELEE" {
	"a_swimSW_MELEE"
	"a_swimS_MELEE"
	"a_swimSE_MELEE"
	"a_swimW_MELEE"
	"a_swimCenter_MELEE"
	"a_swimE_MELEE"
	"a_swimNW_MELEE"
	"a_swimN_MELEE"
	"a_swimNE_MELEE"
	fps 30
	"ACT_MP_SWIM_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_swim"
}

$sequence "MELEE_ALLCLASS_aimmatrix_swim" {
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_straight_up"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_up_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_mid_left"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_right"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_center"
	"a_MELEE_ALLCLASS_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "s_swimAlign_MELEE_ALLCLASS" {
	"a_swimCenter_MELEE_ALLCLASS"
	fps 30
	loop
}

$sequence "swim_MELEE_ALLCLASS" {
	"a_swimSW_MELEE_ALLCLASS"
	"a_swimS_MELEE_ALLCLASS"
	"a_swimSE_MELEE_ALLCLASS"
	"a_swimW_MELEE_ALLCLASS"
	"a_swimCenter_MELEE_ALLCLASS"
	"a_swimE_MELEE_ALLCLASS"
	"a_swimNW_MELEE_ALLCLASS"
	"a_swimN_MELEE_ALLCLASS"
	"a_swimNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_SWIM_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_swim"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "ITEM1_aimmatrix_swim" {
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_straight_up"
	"a_ITEM1_aimmatrix_swim_up_right"
	"a_ITEM1_aimmatrix_swim_up_center"
	"a_ITEM1_aimmatrix_swim_up_left"
	"a_ITEM1_aimmatrix_swim_mid_right"
	"a_ITEM1_aimmatrix_swim_mid_center"
	"a_ITEM1_aimmatrix_swim_mid_left"
	"a_ITEM1_aimmatrix_swim_down_right"
	"a_ITEM1_aimmatrix_swim_down_center"
	"a_ITEM1_aimmatrix_swim_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "s_swimAlign_ITEM1" {
	"a_swimCenter_ITEM1"
	fps 30
	loop
}

$sequence "swim_ITEM1" {
	"a_swimSW_ITEM1"
	"a_swimS_ITEM1"
	"a_swimSE_ITEM1"
	"a_swimW_ITEM1"
	"a_swimCenter_ITEM1"
	"a_swimE_ITEM1"
	"a_swimNW_ITEM1"
	"a_swimN_ITEM1"
	"a_swimNE_ITEM1"
	fps 30
	"ACT_MP_SWIM_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_swim"
}

$sequence "s_swimAlign_LOSER" {
	"a_swimCenter_LOSER"
	fps 30
	loop
}

$sequence "swim_LOSER" {
	"a_swimSW_LOSER"
	"a_swimS_LOSER"
	"a_swimSE_LOSER"
	"a_swimW_LOSER"
	"a_swimCenter_LOSER"
	"a_swimE_LOSER"
	"a_swimNW_LOSER"
	"a_swimN_LOSER"
	"a_swimNE_LOSER"
	fps 30
	"ACT_MP_SWIM_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "run_PRIMARY" {
	"a_runSW_PRIMARY"
	"a_runS_PRIMARY"
	"a_runSE_PRIMARY"
	"a_runW_PRIMARY"
	"a_runCenter_PRIMARY"
	"a_runE_PRIMARY"
	"a_runNW_PRIMARY"
	"a_runN_PRIMARY"
	"a_runNE_PRIMARY"
	fps 30
	"ACT_MP_RUN_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_PRIMARY" {
	"a_crouch_walkSW_PRIMARY"
	"a_crouch_walkS_PRIMARY"
	"a_crouch_walkSE_PRIMARY"
	"a_crouch_walkW_PRIMARY"
	"a_crouch_walkCenter_PRIMARY"
	"a_crouch_walkE_PRIMARY"
	"a_crouch_walkNW_PRIMARY"
	"a_crouch_walkN_PRIMARY"
	"a_crouch_walkNE_PRIMARY"
	fps 30
	"ACT_MP_CROUCHWALK_PRIMARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "PRIMARY_aimmatrix_crouch_idle"
}

$sequence "run_SECONDARY" {
	"a_runSW_SECONDARY"
	"a_runS_SECONDARY"
	"a_runSE_SECONDARY"
	"a_runW_SECONDARY"
	"a_runCenter_SECONDARY"
	"a_runE_SECONDARY"
	"a_runNW_SECONDARY"
	"a_runN_SECONDARY"
	"a_runNE_SECONDARY"
	fps 30
	"ACT_MP_RUN_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_SECONDARY" {
	"a_crouch_walkSW_crouch_walk_SECONDARY"
	"a_crouch_walkS_crouch_walk_SECONDARY"
	"a_crouch_walkSE_crouch_walk_SECONDARY"
	"a_crouch_walkW_crouch_walk_SECONDARY"
	"a_crouch_walkCenter_crouch_walk_SECONDARY"
	"a_crouch_walkE_crouch_walk_SECONDARY"
	"a_crouch_walkNW_crouch_walk_SECONDARY"
	"a_crouch_walkN_crouch_walk_SECONDARY"
	"a_crouch_walkNE_crouch_walk_SECONDARY"
	fps 30
	"ACT_MP_CROUCHWALK_SECONDARY" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "SECONDARY_aimmatrix_crouch_idle"
}

$sequence "run_MELEE" {
	"a_runSW_MELEE"
	"a_runS_MELEE"
	"a_runSE_MELEE"
	"a_runW_MELEE"
	"a_runCenter_MELEE"
	"a_runE_MELEE"
	"a_runNW_MELEE"
	"a_runN_MELEE"
	"a_runNE_MELEE"
	fps 30
	"ACT_MP_RUN_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE" {
	"a_crouch_walkSW_crouch_walk_MELEE"
	"a_crouch_walkS_crouch_walk_MELEE"
	"a_crouch_walkSE_crouch_walk_MELEE"
	"a_crouch_walkW_crouch_walk_MELEE"
	"a_crouch_walkCenter_crouch_walk_MELEE"
	"a_crouch_walkE_crouch_walk_MELEE"
	"a_crouch_walkNW_crouch_walk_MELEE"
	"a_crouch_walkN_crouch_walk_MELEE"
	"a_crouch_walkNE_crouch_walk_MELEE"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_aimmatrix_crouch_idle"
}

$sequence "run_MELEE_ALLCLASS" {
	"a_runSW_MELEE_ALLCLASS"
	"a_runS_MELEE_ALLCLASS"
	"a_runSE_MELEE_ALLCLASS"
	"a_runW_MELEE_ALLCLASS"
	"a_runCenter_MELEE_ALLCLASS"
	"a_runE_MELEE_ALLCLASS"
	"a_runNW_MELEE_ALLCLASS"
	"a_runN_MELEE_ALLCLASS"
	"a_runNE_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_RUN_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_run"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_MELEE_ALLCLASS" {
	"a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkS_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkE_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkN_crouch_walk_MELEE_ALLCLASS"
	"a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS"
	fps 30
	"ACT_MP_CROUCHWALK_MELEE_ALLCLASS" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "MELEE_ALLCLASS_aimmatrix_crouch_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "run_LOSER" {
	"a_runSW_LOSER"
	"a_runS_LOSER"
	"a_runSE_LOSER"
	"a_runW_LOSER"
	"a_runCenter_LOSER"
	"a_runE_LOSER"
	"a_runNW_LOSER"
	"a_runN_LOSER"
	"a_runNE_LOSER"
	fps 30
	"ACT_MP_RUN_LOSERSTATE" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
}

$sequence "ITEM1_aimmatrix_run" {
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_straight_up"
	"a_ITEM1_aimmatrix_run_up_right"
	"a_ITEM1_aimmatrix_run_up_center"
	"a_ITEM1_aimmatrix_run_up_left"
	"a_ITEM1_aimmatrix_run_mid_right"
	"a_ITEM1_aimmatrix_run_mid_center"
	"a_ITEM1_aimmatrix_run_mid_left"
	"a_ITEM1_aimmatrix_run_down_right"
	"a_ITEM1_aimmatrix_run_down_center"
	"a_ITEM1_aimmatrix_run_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "run_ITEM1" {
	"a_runSW_ITEM1"
	"a_runS_ITEM1"
	"a_runSE_ITEM1"
	"a_runW_ITEM1"
	"a_runCenter_ITEM1"
	"a_runE_ITEM1"
	"a_runNW_ITEM1"
	"a_runN_ITEM1"
	"a_runNE_ITEM1"
	fps 30
	"ACT_MP_RUN_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_run"
	{ event 7001 7.00000011920929 "right" }
	{ event 7001 16.0000001192093 "left" }
}

$sequence "crouch_walk_ITEM1" {
	"a_crouch_walkSW_crouch_walk_ITEM1"
	"a_crouch_walkS_crouch_walk_ITEM1"
	"a_crouch_walkSE_crouch_walk_ITEM1"
	"a_crouch_walkW_crouch_walk_ITEM1"
	"a_crouch_walkCenter_crouch_walk_ITEM1"
	"a_crouch_walkE_crouch_walk_ITEM1"
	"a_crouch_walkNW_crouch_walk_ITEM1"
	"a_crouch_walkN_crouch_walk_ITEM1"
	"a_crouch_walkNE_crouch_walk_ITEM1"
	fps 30
	"ACT_MP_CROUCHWALK_ITEM1" 1
	loop
	blend "move_y" -1 1
	blend "move_x" -1 1
	// addlayer "ITEM1_aimmatrix_crouch_idle"
}

$sequence "PRIMARY_aimmatrix_airwalk" {
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_straight_up"
	"a_PRIMARY_aimmatrix_airwalk_up_right"
	"a_PRIMARY_aimmatrix_airwalk_up_center"
	"a_PRIMARY_aimmatrix_airwalk_up_left"
	"a_PRIMARY_aimmatrix_airwalk_mid_right"
	"a_PRIMARY_aimmatrix_airwalk_mid_center"
	"a_PRIMARY_aimmatrix_airwalk_mid_left"
	"a_PRIMARY_aimmatrix_airwalk_down_right"
	"a_PRIMARY_aimmatrix_airwalk_down_center"
	"a_PRIMARY_aimmatrix_airwalk_down_left"
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
	blendwidth 3
	blend "body_yaw" 45 -45
	blend "body_pitch" 90 -45
}

$sequence "airwalk_PRIMARY" "demo_animations_anims\airwalk_PRIMARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_PRIMARY" 1
	loop
	// addlayer "PRIMARY_aimmatrix_swim"
}

$sequence "airwalk_SECONDARY" "demo_animations_anims\airwalk_SECONDARY.smd" {
	fps 30
	"ACT_MP_AIRWALK_SECONDARY" 1
	loop
	// addlayer "SECONDARY_aimmatrix_idle"
}

$sequence "airwalk_MELEE" "demo_animations_anims\airwalk_MELEE.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE" 1
	loop
	// addlayer "MELEE_aimmatrix_idle"
}

$sequence "airwalk_MELEE_ALLCLASS" "demo_animations_anims\airwalk_MELEE_ALLCLASS.smd" {
	fps 30
	"ACT_MP_AIRWALK_MELEE_ALLCLASS" 1
	loop
	// addlayer "MELEE_ALLCLASS_aimmatrix_idle"
	// addlayer "r_armposes"
	// addlayer "r_handposes"
}

$sequence "airwalk_LOSER" "demo_animations_anims\airwalk_LOSER.smd" {
	fps 30
	"ACT_MP_AIRWALK_LOSERSTATE" 1
	loop
}

$sequence "airwalk_ITEM1" "demo_animations_anims\airwalk_ITEM1.smd" {
	fps 30
	"ACT_MP_AIRWALK_ITEM1" 1
	loop
	// addlayer "ITEM1_aimmatrix_idle"
}

$sequence "layer_dieviolent" "demo_animations_anims\layer_dieviolent.smd" {
	fps 30
	hidden
}

$sequence "dieviolent" "demo_animations_anims\dieviolent.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_DIEVIOLENT" 1
	// addlayer "layer_dieviolent"
	{ event AE_WPN_HIDE 1 "" }
	{ event AE_WPN_UNHIDE 64 "" }
}

$sequence "PRIMARY_death_headshot" "demo_animations_anims\PRIMARY_death_headshot.smd" {
	fps 30
}

$sequence "PRIMARY_death_backstab" "demo_animations_anims\PRIMARY_death_backstab.smd" {
	fps 30
}

$sequence "PRIMARY_death_burning" "demo_animations_anims\PRIMARY_death_burning.smd" {
	fps 30
}

$sequence "layer_gesture_PRIMARY_go_armL" "demo_animations_anims\layer_gesture_PRIMARY_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PRIMARY_go_runN_armL" "demo_animations_anims\layer_gesture_PRIMARY_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_go" "demo_animations_anims\gesture_PRIMARY_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY" 1
	// delta
	blendlayer "layer_gesture_PRIMARY_go_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_PRIMARY_help_armL" "demo_animations_anims\layer_gesture_PRIMARY_help_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PRIMARY_help_runN_armL" "demo_animations_anims\layer_gesture_PRIMARY_help_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_help" "demo_animations_anims\gesture_PRIMARY_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY" 1
	// delta
	blendlayer "layer_gesture_PRIMARY_help_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_help_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_help_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PRIMARY_cheer_armL" "demo_animations_anims\layer_gesture_PRIMARY_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PRIMARY_cheer_runN_armL" "demo_animations_anims\layer_gesture_PRIMARY_cheer_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_cheer" "demo_animations_anims\gesture_PRIMARY_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY" 1
	// delta
	blendlayer "layer_gesture_PRIMARY_cheer_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_cheer_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_cheer_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_PRIMARY_positive_armL" "demo_animations_anims\layer_gesture_PRIMARY_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_PRIMARY_positive_runN_armL" "demo_animations_anims\layer_gesture_PRIMARY_positive_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_PRIMARY_positive" "demo_animations_anims\gesture_PRIMARY_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY" 1
	// delta
	blendlayer "layer_gesture_PRIMARY_positive_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_positive_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_PRIMARY_positive_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_SECONDARY_go_armL" "demo_animations_anims\layer_gesture_SECONDARY_go_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_SECONDARY_go_runN_armL" "demo_animations_anims\layer_gesture_SECONDARY_go_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_go" "demo_animations_anims\gesture_SECONDARY_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_SECONDARY_go_armL" -2 -1 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_go_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
}

$sequence "layer_gesture_SECONDARY_help_armL" "demo_animations_anims\layer_gesture_SECONDARY_help_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_SECONDARY_help_runN_armL" "demo_animations_anims\layer_gesture_SECONDARY_help_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_help" "demo_animations_anims\gesture_SECONDARY_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_SECONDARY_help_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_help_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_help_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_SECONDARY_cheer_armL" "demo_animations_anims\layer_gesture_SECONDARY_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_SECONDARY_cheer_runN_armL" "demo_animations_anims\layer_gesture_SECONDARY_cheer_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_cheer" "demo_animations_anims\gesture_SECONDARY_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_SECONDARY_cheer_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_cheer_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_cheer_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_SECONDARY_positive_armL" "demo_animations_anims\layer_gesture_SECONDARY_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "layer_gesture_SECONDARY_positive_runN_armL" "demo_animations_anims\layer_gesture_SECONDARY_positive_runN_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_SECONDARY_positive" "demo_animations_anims\gesture_SECONDARY_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY" 1
	// delta
	blendlayer "layer_gesture_SECONDARY_positive_armL" -0.8 -0.2 0.2 0.8 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_positive_runN_armL" 0.2 0.8 1 2 spline poseparameter move_x
	blendlayer "layer_gesture_SECONDARY_positive_runN_armL" -2 -1 -0.8 -0.2 spline poseparameter move_x
}

$sequence "layer_gesture_MELEE_go_armL" "demo_animations_anims\layer_gesture_MELEE_go_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_go" "demo_animations_anims\gesture_MELEE_go.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FINGERPOINT_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_go_armL"
}

$sequence "layer_gesture_MELEE_cheer_armL" "demo_animations_anims\layer_gesture_MELEE_cheer_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_cheer" "demo_animations_anims\gesture_MELEE_cheer.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_FISTPUMP_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_cheer_armL"
}

$sequence "layer_gesture_MELEE_help_armL" "demo_animations_anims\layer_gesture_MELEE_help_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_help" "demo_animations_anims\gesture_MELEE_help.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_HANDMOUTH_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_help_armL"
}

$sequence "layer_gesture_MELEE_positive_armL" "demo_animations_anims\layer_gesture_MELEE_positive_armL.smd" {
	fps 30
	hidden
}

$sequence "gesture_MELEE_positive" "demo_animations_anims\gesture_MELEE_positive.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_GESTURE_VC_THUMBSUP_MELEE" 1
	// delta
	// addlayer "layer_gesture_MELEE_positive_armL"
}

$sequence "selectionmenu_startpose" "demo_animations_anims\selectionmenu_startpose.smd" {
	fps 30
}

$sequence "selectionmenu_anim01" "demo_animations_anims\selectionmenu_anim01.smd" {
	fps 30
	{ event AE_CL_PLAYSOUND 2.99999997019768 "Selection.DemoEquipment1" }
	{ event AE_CL_PLAYSOUND 30.0000010728836 "Selection.DemoClipSpin" }
	{ event AE_CL_PLAYSOUND 61.0000019073486 "Selection.DemoEquipment2" }
}

$sequence "selectionmenu_idle" "demo_animations_anims\selectionmenu_idle.smd" {
	fps 30
	loop
}

$sequence "armslayer_throw_fire" "demo_animations_anims\armslayer_throw_fire.smd" {
	fps 30
	hidden
}

$sequence "throw_fire" "demo_animations_anims\throw_fire.smd" {
	fps 30
	// subtract "a_reference" 0
	"ACT_MP_THROW" 1
	// delta
	// addlayer "armslayer_throw_fire"
	blendlayer "r_handposes" 0 0 0.28 0.4 spline
}

$sequence "layer_taunt01" "demo_animations_anims\layer_taunt01.smd" {
	fps 30
	hidden
}

$sequence "taunt01" "demo_animations_anims\taunt01.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt01"
	{ event 5004 25.0000002831221 "Taunt.Demo01FootStompLight" }
	{ event 5004 41.0000011026859 "Taunt.Demo01FootSpin" }
	{ event 5004 66.0000031590462 "Taunt.Demo01HandClap" }
	{ event 5004 72.0000028014183 "Taunt.Demo01HandClap2" }
}

$sequence "layer_taunt02" "demo_animations_anims\layer_taunt02.smd" {
	fps 30
	hidden
}

$sequence "taunt02" "demo_animations_anims\taunt02.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt02"
	{ event AE_CL_BODYGROUP_SET_VALUE 20.0000007450581 "smile 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE 60.0000002980232 "smile 0" }
}

$sequence "layer_taunt03" "demo_animations_anims\layer_taunt03.smd" {
	fps 30
	hidden
}

$sequence "taunt03" "demo_animations_anims\taunt03.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt03"
	{ event 5004 22.9999999701977 "Taunt.Demo03BottleCatch" }
	{ event 5004 48.0000011622906 "Taunt.Demo03BottleSlosh" }
	{ event 5004 111.000001430511 "Taunt.Demo03BottleAh" }
}

$sequence "layer_taunt04" "demo_animations_anims\layer_taunt04.smd" {
	fps 30
	hidden
}

$sequence "taunt04" "demo_animations_anims\taunt04.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt04"
}

$sequence "taunt06" "demo_animations_anims\taunt06.smd" {
	fps 30
	// addlayer "MELEE_aimmatrix_idle"
	blendlayer "MELEE_aimmatrix_idle" 0.96 1 1 1 spline
	{ event AE_WPN_HIDE 1.00000002421439 "" }
	{ event AE_WPN_UNHIDE 74.0000009536743 "" }
}

$sequence "layer_taunt08" "demo_animations_anims\layer_taunt08.smd" {
	fps 30
	hidden
}

$sequence "taunt08" "demo_animations_anims\taunt08.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt08"
	{ event 5004 9.00000022351742 "Taunt.Demo01FootStompLight" }
	{ event 5004 27.0000014305115 "Taunt.Demo01FootStompLight" }
	{ event 5004 35.0000009536743 "Taunt.Demo01FootStompLight" }
	{ event 5004 35.0000009536743 "Taunt.DemoShakeIt" }
	{ event 5004 41.0000005960464 "Taunt.DemoShakeIt" }
	{ event 5004 51 "Taunt.DemoShakeIt" }
}

$sequence "layer_taunt09" "demo_animations_anims\layer_taunt09.smd" {
	fps 30
	hidden
}

$sequence "taunt09" "demo_animations_anims\taunt09.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt09"
	{ event 5004 45 "Weapon_Sword.swing" }
	{ event 5004 55.0000004768372 "Weapon_Sword.swing" }
	{ event 5004 69.9999990463257 "Weapon_Sword.swing" }
}

$sequence "layer_taunt_replay" "demo_animations_anims\layer_taunt_replay.smd" {
	fps 30
	hidden
}

$sequence "taunt_replay" "demo_animations_anims\taunt_replay.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_replay"
	{ event AE_WPN_HIDE 0.999999977648258 "" }
	{ event AE_WPN_UNHIDE 99.0000009536743 "" }
}

$sequence "layer_taunt_laugh" "demo_animations_anims\layer_taunt_laugh.smd" {
	fps 30
	hidden
}

$sequence "taunt_laugh" "demo_animations_anims\taunt_laugh.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_laugh"
	{ event AE_WPN_HIDE 0.999999965541065 "" }
	{ event AE_WPN_UNHIDE 159 "" }
}

$sequence "layer_taunt11_howl" "demo_animations_anims\layer_taunt11_howl.smd" {
	fps 30
	hidden
}

$sequence "taunt11_howl" "demo_animations_anims\taunt11_howl.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt11_howl"
	{ event AE_WPN_HIDE 0.999999968335032 "" }
	{ event AE_WPN_UNHIDE 165 "" }
}

$sequence "taunt_brutallegendinterior" "demo_animations_anims\taunt_brutallegendinterior.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendin" "demo_animations_anims\taunt_brutallegendin.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendout" "demo_animations_anims\taunt_brutallegendout.smd" {
	fps 30
	hidden
}

$sequence "taunt_brutallegendinblend" "demo_animations_anims\taunt_brutallegendinblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegendoutblend" "demo_animations_anims\taunt_brutallegendoutblend.smd" {
	fps 30
	// subtract "a_reference" 0
	// delta
	hidden
}

$sequence "taunt_brutallegend" "demo_animations_anims\taunt_brutallegend.smd" {
	fps 30
	// subtract "a_reference" 0
	blendlayer "taunt_brutallegendin" 0 0.031008 0.031008 0.031008 spline
	blendlayer "taunt_brutallegendinterior" 0.031008 0.031008 0.930233 0.930233 spline
	blendlayer "taunt_brutallegendout" 0.930233 0.930233 0.930233 1.007752 spline
	// addlayer "taunt_brutallegendinblend"
	// addlayer "taunt_brutallegendoutblend"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 4.99999998137355 "" }
	{ event AE_WPN_HIDE 119.000002920628 "" }
}

$sequence "taunt_highFiveStart" "demo_animations_anims\taunt_highFiveStart.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "taunt_highFiveStart_idle" "demo_animations_anims\taunt_highFiveStart_idle.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 137 "" }
}

$sequence "layer_taunt_highfiveSuccess" "demo_animations_anims\layer_taunt_highfiveSuccess.smd" {
	fps 30
	hidden
}

$sequence "taunt_highfiveSuccess" "demo_animations_anims\taunt_highfiveSuccess.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highfiveSuccess"
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 123.999997973442 "" }
}

$sequence "layer_taunt_highfiveSuccessFull" "demo_animations_anims\layer_taunt_highfiveSuccessFull.smd" {
	fps 30
	hidden
}

$sequence "taunt_highfiveSuccessFull" "demo_animations_anims\taunt_highfiveSuccessFull.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_highfiveSuccessFull"
	{ event AE_WPN_HIDE 1.00000004749745 "" }
	{ event AE_WPN_UNHIDE 123.999997973442 "" }
}

$sequence "taunt_conga" "demo_animations_anims\taunt_conga.smd" {
	fps 30.03
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_dosido_dance" "demo_animations_anims\layer_taunt_dosido_dance.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_dance" "demo_animations_anims\taunt_dosido_dance.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_dance"
	{ event AE_WPN_HIDE 1.00000001024455 "" }
	{ event AE_WPN_UNHIDE 261.000001430511 "" }
}

$sequence "layer_taunt_dosido_intro" "demo_animations_anims\layer_taunt_dosido_intro.smd" {
	fps 30
	hidden
}

$sequence "taunt_dosido_intro" "demo_animations_anims\taunt_dosido_intro.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_dosido_intro"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 92 "" }
}

$sequence "taunt_flip_start" "demo_animations_anims\taunt_flip_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_flip_success_initiator" "demo_animations_anims\layer_taunt_flip_success_initiator.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_initiator" "demo_animations_anims\taunt_flip_success_initiator.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_initiator"
	{ event AE_WPN_HIDE 0.999999954365194 "" }
	{ event AE_WPN_UNHIDE 110.000001192093 "" }
}

$sequence "layer_taunt_flip_success_receiver" "demo_animations_anims\layer_taunt_flip_success_receiver.smd" {
	fps 30
	hidden
}

$sequence "taunt_flip_success_receiver" "demo_animations_anims\taunt_flip_success_receiver.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_flip_success_receiver"
	{ event AE_WPN_HIDE 1.00000000325963 "" }
	{ event AE_WPN_UNHIDE 122.000001251698 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 58.0000010430813 "taunt_flip_land follow_attachment foot_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 38.0000012218952 "taunt_flip_trail follow_attachment back_lower" }
}

$sequence "taunt_rps_start" "demo_animations_anims\taunt_rps_start.smd" {
	fps 30
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock" "demo_animations_anims\layer_taunt_rps_rock.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock" "demo_animations_anims\taunt_rps_rock.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock"
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_paper" "demo_animations_anims\layer_taunt_rps_paper.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper" "demo_animations_anims\taunt_rps_paper.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper"
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_scissors" "demo_animations_anims\layer_taunt_rps_scissors.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors" "demo_animations_anims\taunt_rps_scissors.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors"
	{ event AE_WPN_HIDE 0 "" }
}

$sequence "layer_taunt_rps_rock_win" "demo_animations_anims\layer_taunt_rps_rock_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_win" "demo_animations_anims\taunt_rps_rock_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 100.000000119209 "" }
}

$sequence "layer_taunt_rps_paper_win" "demo_animations_anims\layer_taunt_rps_paper_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_win" "demo_animations_anims\taunt_rps_paper_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 100.000000119209 "" }
}

$sequence "layer_taunt_rps_scissors_win" "demo_animations_anims\layer_taunt_rps_scissors_win.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_win" "demo_animations_anims\taunt_rps_scissors_win.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_win"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 100.000000119209 "" }
}

$sequence "layer_taunt_rps_rock_lose" "demo_animations_anims\layer_taunt_rps_rock_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_rock_lose" "demo_animations_anims\taunt_rps_rock_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_rock_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103.000000119209 "" }
}

$sequence "layer_taunt_rps_paper_lose" "demo_animations_anims\layer_taunt_rps_paper_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_paper_lose" "demo_animations_anims\taunt_rps_paper_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_paper_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103.000000119209 "" }
}

$sequence "layer_taunt_rps_scissors_lose" "demo_animations_anims\layer_taunt_rps_scissors_lose.smd" {
	fps 30
	hidden
}

$sequence "taunt_rps_scissors_lose" "demo_animations_anims\taunt_rps_scissors_lose.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_rps_scissors_lose"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 103.000000119209 "" }
}

$sequence "layer_taunt_headbutt_start" "demo_animations_anims\layer_taunt_headbutt_start.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_start" "demo_animations_anims\taunt_headbutt_start.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_start"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 159 "" }
}

$sequence "layer_taunt_headbutt_success" "demo_animations_anims\layer_taunt_headbutt_success.smd" {
	fps 30
	hidden
}

$sequence "taunt_headbutt_success" "demo_animations_anims\taunt_headbutt_success.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_headbutt_success"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 56.0000019073486 "taunt_headbutt_impact follow_attachment head" }
	{ event AE_WPN_UNHIDE 148 "" }
}

$sequence "layer_taunt_nuke" "demo_animations_anims\layer_taunt_nuke.smd" {
	fps 30
	hidden
}

$sequence "taunt_nuke" "demo_animations_anims\taunt_nuke.smd" {
	fps 30
	// subtract "a_reference" 0
	// addlayer "layer_taunt_nuke"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 99.000002682209 "taunt_demo_nuke_powder follow_attachment effect_hand_L" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 99.000002682209 "taunt_demo_nuke_brew follow_attachment effect_hand_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 157.999998003244 "taunt_demo_nuke_lighter follow_attachment effect_hand_R" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 178.000006616116 "taunt_demo_nuke_vapors follow_attachment head" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 205.000001966953 "taunt_demo_nuke_shroomcloud follow_attachment head" }
	{ event AE_WPN_HIDE 302.999993860722 "" }
}

$sequence "layer_taunt_woohoo" "demo_animations_anims\layer_taunt_woohoo.smd" {
	fps 24
	hidden
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 5.99999993294477 "" }
	{ event AE_WPN_HIDE 138.999997913837 "" }
}

$sequence "taunt_woohoo" "demo_animations_anims\taunt_woohoo.smd" {
	fps 24
	// subtract "a_reference" 0
	// addlayer "layer_taunt_woohoo"
	{ event AE_WPN_HIDE 0 "" }
	{ event AE_WPN_UNHIDE 5.99999993294477 "" }
	{ event AE_WPN_HIDE 138.999997913837 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 9.99999988824129 "taunt_demo_beer_spray follow_attachment effect_hand_L" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 60.0000014603138 "taunt_demo_beer_spray follow_attachment effect_hand_L" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 100.000001013279 "taunt_demo_beer_spray follow_attachment effect_hand_L" }
}

$ikchain "rhand" "bip_hand_R" knee 0.757 0.653 -0.006
$ikchain "lhand" "bip_hand_L" knee 0.69 0.011 -0.724
$ikchain "rfoot" "bip_foot_R" knee 0.606 -0.795 0
$ikchain "lfoot" "bip_foot_L" knee 0.589 0 0.808

